### ISSUE TITLE
Ionic v7.0.0-beta.2 onRefreshToken gives new notifications instead of new tokens

### ISSUE THREAD

**Issue by dalobstah** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated#100]
onRefreshToken is activated with the same events as onNotification. onRefreshToken does not send refresh token events. This is for both iOS and Android.

**Comment by andrehtissot** [comment]
You are correct, thank you very much. Fix released [7.0.0-beta.3](https://www.npmjs.com/package/cordova-plugin-fcm-with-dependecy-updated/v/7.0.0-beta.3).
