### ISSUE TITLE
Put Installation and configuration details on top of the Readme file

### ISSUE THREAD

**Issue by Sampath-Lokuge** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated#102]
Hi,

Please put `Installation and configuration details` on top of the Readme file and release notes after that.

**Comment by andrehtissot** [comment]
I hope the rework on main Readme document has been satisfactory. Thank you for pointing it out.

**Comment by Sampath-Lokuge** [comment]
@andrehtissot Oh.. Awesome now. Top work. Thanks!
