### ISSUE TITLE
Firebase Messaging iOS SDK v7.0 will no longer support the FCM Direct Channel API

### ISSUE THREAD

**Issue by kjetil-pbl** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated#105]
Hi,

We recently received an email from the Firebase team stating that: Firebase Messaging iOS SDK version 7.0 will be a breaking change where the SDK will no longer support iOS Direct Channel API.

We are using this plugin for push notification for both android and iOs.  Will this plugin be impacted by this?

**Comment by andrehtissot** [comment]
It won't for sure if you have updated the plugin for v5 or newer.

If you didn't, although not recommended, it might still work but version of Firebase SDK itself might behave strangely.
