### ISSUE TITLE
IOS firebase module not found ionic 3

### ISSUE THREAD

**Issue by posdevelopers** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated#108]
Hi , it's 24 hours and i am stuck on the below issue with this plugin on ios , can anyone help me please please . i am using ionic 3 working fine on android , but on ios it is not building and give the below error , tried every thing , xcode 11.

fatal error:
      module 'Firebase' not found
@import Firebase;
 ~~~~~~~^~~~~~~~
1 error generated.

**Comment by andrehtissot** [comment]
1.Would you share your package.json?
2.Do you have cocoapods installed without sudo (not as root)?

**Comment by posdevelopers** [comment]
{
  "name": "QuickzLaundry",
  "version": "0.0.1",
  "author": "Ionic Framework",
  "homepage": "http://ionicframework.com/",
  "private": true,
  "scripts": {
    "start": "ionic-app-scripts serve",
    "clean": "ionic-app-scripts clean",
    "build": "ionic-app-scripts build",
    "lint": "ionic-app-scripts lint"
  },
  "dependencies": {
    "@angular/animations": "5.2.11",
    "@angular/common": "5.2.11",
    "@angular/compiler": "5.2.11",
    "@angular/compiler-cli": "5.2.11",
    "@angular/core": "5.2.11",
    "@angular/forms": "5.2.11",
    "@angular/http": "5.2.11",
    "@angular/platform-browser": "5.2.11",
    "@angular/platform-browser-dynamic": "5.2.11",
    "@ionic-native/card-io": "^4.20.0",
    "@ionic-native/core": "~4.20.0",
    "@ionic-native/date-picker": "^4.20.0",
    "@ionic-native/fcm": "^4.20.0",
    "@ionic-native/firebase-messaging": "^4.20.0",
    "@ionic-native/geolocation": "^4.20.0",
    "@ionic-native/local-notifications": "^4.20.0",
    "@ionic-native/network": "^4.20.0",
    "@ionic-native/splash-screen": "~4.20.0",
    "@ionic-native/status-bar": "~4.20.0",
    "@ionic/storage": "2.2.0",
    "axios": "^0.19.0",
    "cordova": "^8.1.0",
    "cordova-android": "8.1.0",
    "cordova-ios": "5.1.1",
    "cordova-plugin-androidx": "^1.0.2",
    "cordova-plugin-androidx-adapter": "^1.1.1",
    "cordova-plugin-badge": "^0.8.8",
    "cordova-plugin-datepicker": "^0.9.3",
    "cordova-plugin-device": "^2.0.2",
    "cordova-plugin-geolocation": "^4.0.2",
    "cordova-plugin-ionic-keyboard": "^2.2.0",
    "cordova-plugin-ionic-webview": "^4.2.1",
    "cordova-plugin-local-notification": "^0.9.0-beta.2",
    "cordova-plugin-network-information": "^2.0.2",
    "cordova-plugin-splashscreen": "^5.0.2",
    "cordova-plugin-statusbar": "^2.4.2",
    "cordova-plugin-whitelist": "^1.3.3",
    "date-fns": "^2.8.1",
    "ionic-angular": "3.9.5",
    "ionicons": "3.0.0",
    "ng2-search-filter": "^0.5.1",
    "rxjs": "5.5.11",
    "sw-toolbox": "3.6.0",
    "zone.js": "0.8.29"
  },
  "devDependencies": {
    "@ionic/app-scripts": "3.2.2",
    "cordova-plugin-device": "^2.0.2",
    "cordova-plugin-ionic-keyboard": "^2.2.0",
    "cordova-plugin-splashscreen": "^5.0.2",
    "cordova-plugin-statusbar": "^2.4.2",
    "cordova-plugin-whitelist": "^1.3.3",
    "node-sass": "^4.14.1",
    "typescript": "~2.6.2"
  },
  "description": "An Ionic project",
  "cordova": {
    "plugins": {
      "cordova-plugin-whitelist": {},
      "cordova-plugin-statusbar": {},
      "cordova-plugin-device": {},
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-ionic-keyboard": {},
      "cordova-plugin-datepicker": {},
      "cordova-plugin-geolocation": {},
      "cordova-plugin-local-notification": {},
      "cordova-plugin-network-information": {},
      "cordova-plugin-androidx": {},
      "cordova-plugin-androidx-adapter": {},
      "cordova-plugin-ionic-webview": {}
    },
    "platforms": [
      "android",
      "ios"
    ]
  }
}

**Comment by posdevelopers** [comment]
yes cocoa is installed and when i run pod install on ios folder then it is installing firebase

**Comment by andrehtissot** [comment]
That's so strange. Cordova should be able to install using cocoapods by itself on plugin install. I'll add an issue here to investigate this issue and maybe force it by script.

**Comment by andrehtissot** [comment]
After that you were able to build the app, right?

**Comment by posdevelopers** [comment]
Yes , i go to pod install and all dependcies are installed , now when i try to build using sudo ionic cordova build ios , then it is giving sandbox is not sync with podlock file

**Comment by posdevelopers** [comment]
diff: /Podfile.lock: No such file or directory
diff: /Manifest.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.

**Comment by posdevelopers** [comment]
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 4.3, but the range of supported deployment target versions is 8.0 to 13.0.99. (in target 'nanopb' from project 'Pods')
** BUILD FAILED **


The following build commands failed:
        PhaseScriptExecution [CP]\ Check\ Pods\ Manifest.lock /var/root/Library/Developer/Xcode/DerivedData/Quick_Z_Laundry-gfzmljacvkqqjjbcgohzrydhchgv/Build/Intermediates.noindex/Quick\ Z\ Laundry.build/Debug-iphonesimulator/Quick\ Z\ Laundry.build/Script-EC5B9E52FBA74C42B5B00AD8.sh
(1 failure)

**Comment by posdevelopers** [comment]
Here is my cordova plugin list i am using :
cordova-plugin-androidx 1.0.2 "cordova-plugin-androidx"
cordova-plugin-androidx-adapter 1.1.1 "cordova-plugin-androidx-adapter"
cordova-plugin-badge 0.8.8 "Badge"
cordova-plugin-datepicker 0.9.3 "DatePicker"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-fcm-with-dependecy-updated 6.4.3 "Cordova FCM Push Plugin"
cordova-plugin-geolocation 4.0.2 "Geolocation"
cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.2.1 "cordova-plugin-ionic-webview"
cordova-plugin-local-notification 0.9.0-beta.2 "LocalNotification"
cordova-plugin-network-information 2.0.2 "Network Information"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"

**Comment by andrehtissot** [comment]
This is a very old app, which is still targetting iOS 4.3. This iOS version is not supported by cordova. And `cordova-plugin-fcm-with-dependecy-updated` only suports iOS 9+.

I suggest to open the project workspace in XCode and configure to target, at least, iOS 9. Which will probably cause many plugins to fail unless upgraded.

**Comment by posdevelopers** [comment]
i am targeting ios 11 from xcode

**Comment by posdevelopers** [comment]
Now i am facing error in Appdelegate+fcm file 
#import "AppDelegate+FCMPlugin.h"
#import "FCMPlugin.h"
#import "FCMPluginIOS9Support.h"
#import "FCMNotificationCenterDelegate.h"
#import <objc/runtime.h>
#import <Foundation/Foundation.h>

@import UserNotifications;
@import Firebase;
"Module firebase not found" , i am opening workspace as seen on the other links

**Comment by andrehtissot** [comment]
> i am targeting ios 11 from xcode

In the app, yes. But the "nanopb" dependency of a dependency you have is not. Although, this should be causing this particular issue.

**Comment by andrehtissot** [comment]
> Now i am facing error in Appdelegate+fcm file
> #import "AppDelegate+FCMPlugin.h"
> #import "FCMPlugin.h"
> #import "FCMPluginIOS9Support.h"
> #import "FCMNotificationCenterDelegate.h"
> #import <objc/runtime.h>
> #import <Foundation/Foundation.h>
> 
> @import UserNotifications;
> @import Firebase;
> "Module firebase not found" , i am opening workspace as seen on the other links

Ok, so you are opening the "QuickzLaundry.xcworkspace", right?

**Comment by posdevelopers** [comment]
yes i am opening xcworkspace

**Comment by andrehtissot** [comment]
Would you share your `Podfile` file?

**Comment by posdevelopers** [comment]
# DO NOT MODIFY -- auto-generated by Apache Cordova

platform :ios, '11.0'

target 'Quick Z Laundry' do
	project 'Quick Z Laundry.xcodeproj'
# Add the Firebase pod for Google Analytics
pod 'Firebase/Analytics'

# Add the pods for any other Firebase products you want to use in your app
# For example, to use Firebase Authentication and Cloud Firestore
pod 'Firebase/Auth'
pod 'Firebase/Firestore'
end

**Comment by andrehtissot** [comment]
Got it. You have another plugin that thinks that it is the only one that can use cocoapods :/

**Comment by andrehtissot** [comment]
Some plugins don't know how to work together. Having a plugin patching others to allow mutual execution is a weird way to go, but not sure there are others. :/

**Comment by posdevelopers** [comment]
Please help i just downgraded to 2.4.0 version and build succeeded but downgraded version have uiwebview so apple is rejecting it.

**Comment by andrehtissot** [comment]
v2.4.0 will also have issues with Firebase Messaging, fail to run on iOS 11, have far less features.

v2.4.0 only builds because it doesn't use cocoapods. Which is now being mishandled by another plugin. Downgrading is not the solution.

**Comment by andrehtissot** [comment]
In your Podfile, modify it to:

```
# DO NOT MODIFY -- auto-generated by Apache Cordova

platform :ios, '11.0'

target 'Quick Z Laundry' do
	project 'Quick Z Laundry.xcodeproj'
	# Add the Firebase pod for Google Analytics
	pod 'Firebase/Analytics'

	# Add the pods for any other Firebase products you want to use in your app
	# For example, to use Firebase Authentication and Cloud Firestore
	pod 'Firebase/Auth'
	pod 'Firebase/Firestore'
	pod 'Firebase/Messaging' # This is required for Push
end
```

And `pod install` again there.

**Comment by posdevelopers** [comment]
let me try this

**Comment by posdevelopers** [comment]
One thing more i would like to update you that this podfile is generated empty when i first try to build the app and then i edit it and add these lines

**Comment by posdevelopers** [comment]
Also one more thing latest cocoapod is not installing on my mac , so i have installed some old version

**Comment by posdevelopers** [comment]
pod --version result is 1.8.4

**Comment by posdevelopers** [comment]
i added above line and got the error

**Comment by posdevelopers** [comment]
### Plugins

```
cocoapods-clean       : 0.0.1
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# DO NOT MODIFY -- auto-generated by Apache Cordova

platform :ios, '11.0'

target 'Quick Z Laundry' do
        project 'Quick Z Laundry.xcodeproj'
# Add the Firebase pod for Google Analytics
pod 'Firebase/Analytics'

# Add the pods for any other Firebase products you want to use in your app
# For example, to use Firebase Authentication and Cloud Firestore
pod 'Firebase/Auth'
pod 'Firebase/Firestore'
pod 'Firebase/Messaging'
end
```

### Error

```
JSON::ParserError - A JSON text must at least contain two octets!
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/json/common.rb:156:in `initialize'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/json/common.rb:156:in `new'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/json/common.rb:156:in `parse'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/specification/json.rb:61:in `from_json'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/specification.rb:715:in `from_string'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/specification.rb:689:in `from_file'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/source.rb:186:in `specification'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/specification/set.rb:58:in `block in specification_name'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/specification/set.rb:56:in `each'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/specification/set.rb:56:in `specification_name'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/cdn_source.rb:212:in `search'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/source/aggregate.rb:83:in `block in search'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/source/aggregate.rb:83:in `select'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/source/aggregate.rb:83:in `search'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/resolver.rb:416:in `create_set_from_sources'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/resolver.rb:385:in `find_cached_set'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/resolver.rb:360:in `specifications_for_dependency'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/resolver.rb:165:in `search_for'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/resolver.rb:274:in `block in sort_dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/resolver.rb:267:in `each'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/resolver.rb:267:in `sort_by'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/resolver.rb:267:in `sort_dependencies'
/Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:53:in `block in sort_dependencies'
/Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:70:in `with_no_such_dependency_error_handling'
/Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:52:in `sort_dependencies'
/Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:754:in `push_state_for_requirements'
/Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:746:in `require_nested_dependencies_for'
/Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:729:in `activate_new_spec'
/Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:686:in `attempt_to_activate'
/Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:254:in `process_topmost_state'
/Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:182:in `resolve'
/Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolver.rb:43:in `resolve'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/resolver.rb:94:in `resolve'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:986:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:984:in `resolve_dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:410:in `analyze'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:234:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:233:in `resolve_dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:156:in `install!'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/command/install.rb:52:in `run'
/Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:22:in `load'
/usr/local/bin/pod:22:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=A+JSON+text+must+at+least+contain+two+octets%21&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
 - pod install-- JSON::ParserError - A JSON text must at least contain two octets!
   https://github.com/CocoaPods/CocoaPods/issues/6692 [closed] [13 comments]
   6 weeks ago

 - Searching for inspections failed: Failed to open TCP connection to api.github.com:443 (Connection refused - connect(2) for "api.github.com" port 443)
   https://github.com/CocoaPods/CocoaPods/issues/9609 [closed] [5 comments]
   20 Mar 2020

 - pod search not work JSON ParserError
   https://github.com/CocoaPods/CocoaPods/issues/5172 [closed] [10 comments]
   30 Aug 2018

**Comment by posdevelopers** [comment]
I am still getting the error after adding pod firebase/messaging

**Comment by posdevelopers** [comment]
i will delete and rebuild the project ,these are downloaded 
Installing Firebase (6.27.0)
Installing FirebaseCore (6.8.0)
Installing FirebaseCoreDiagnostics (1.4.0)
Installing FirebaseInstallations (1.4.0)
Installing FirebaseInstanceID (4.4.0)
Installing FirebaseMessaging (4.5.0)
Installing GoogleDataTransport (6.2.1)
Installing GoogleDataTransportCCTSupport (3.2.0)
Installing GoogleUtilities (6.6.0)
Installing PromisesObjC (1.2.9)
Installing Protobuf (3.12.0)
Installing nanopb (1.30905.0)

**Comment by posdevelopers** [comment]
here is my podlock file
PODS:
  - Firebase/CoreOnly (6.27.0):
    - FirebaseCore (= 6.8.0)
  - Firebase/Messaging (6.27.0):
    - Firebase/CoreOnly
    - FirebaseMessaging (~> 4.5.0)
  - FirebaseCore (6.8.0):
    - FirebaseCoreDiagnostics (~> 1.3)
    - GoogleUtilities/Environment (~> 6.5)
    - GoogleUtilities/Logger (~> 6.5)
  - FirebaseCoreDiagnostics (1.4.0):
    - GoogleDataTransportCCTSupport (~> 3.1)
    - GoogleUtilities/Environment (~> 6.5)
    - GoogleUtilities/Logger (~> 6.5)
    - nanopb (~> 1.30905.0)
  - FirebaseInstallations (1.4.0):
    - FirebaseCore (~> 6.8)
    - GoogleUtilities/Environment (~> 6.6)
    - GoogleUtilities/UserDefaults (~> 6.6)
    - PromisesObjC (~> 1.2)
  - FirebaseInstanceID (4.4.0):
    - FirebaseCore (~> 6.8)
    - FirebaseInstallations (~> 1.0)
    - GoogleUtilities/Environment (~> 6.5)
    - GoogleUtilities/UserDefaults (~> 6.5)
  - FirebaseMessaging (4.5.0):
    - FirebaseCore (~> 6.8)
    - FirebaseInstanceID (~> 4.3)
    - GoogleUtilities/AppDelegateSwizzler (~> 6.5)
    - GoogleUtilities/Environment (~> 6.5)
    - GoogleUtilities/Reachability (~> 6.5)
    - GoogleUtilities/UserDefaults (~> 6.5)
    - Protobuf (>= 3.9.2, ~> 3.9)
  - GoogleDataTransport (6.2.1)
  - GoogleDataTransportCCTSupport (3.2.0):
    - GoogleDataTransport (~> 6.1)
    - nanopb (~> 1.30905.0)
  - GoogleUtilities/AppDelegateSwizzler (6.6.0):
    - GoogleUtilities/Environment
    - GoogleUtilities/Logger
    - GoogleUtilities/Network
  - GoogleUtilities/Environment (6.6.0):
    - PromisesObjC (~> 1.2)
  - GoogleUtilities/Logger (6.6.0):
    - GoogleUtilities/Environment
  - GoogleUtilities/Network (6.6.0):
    - GoogleUtilities/Logger
    - "GoogleUtilities/NSData+zlib"
    - GoogleUtilities/Reachability
  - "GoogleUtilities/NSData+zlib (6.6.0)"
  - GoogleUtilities/Reachability (6.6.0):
    - GoogleUtilities/Logger
  - GoogleUtilities/UserDefaults (6.6.0):
    - GoogleUtilities/Logger
  - nanopb (1.30905.0):
    - nanopb/decode (= 1.30905.0)
    - nanopb/encode (= 1.30905.0)
  - nanopb/decode (1.30905.0)
  - nanopb/encode (1.30905.0)
  - PromisesObjC (1.2.9)
  - Protobuf (3.12.0)

DEPENDENCIES:
  - Firebase/Messaging

SPEC REPOS:
  https://cdn.cocoapods.org/:
    - Firebase
    - FirebaseCore
    - FirebaseCoreDiagnostics
    - FirebaseInstallations
    - FirebaseInstanceID
    - FirebaseMessaging
    - GoogleDataTransport
    - GoogleDataTransportCCTSupport
    - GoogleUtilities
    - nanopb
    - PromisesObjC
    - Protobuf

SPEC CHECKSUMS:
  Firebase: fc4cbf6f1592636431821ef9a3c557e4dfd9f268
  FirebaseCore: feda061cb1ee6d8ad4824f4a4a8ffbcfe284f595
  FirebaseCoreDiagnostics: 4505e4d4009b1d93f605088ee7d7764d5f0d1c84
  FirebaseInstallations: 293f567159b6d66d1c990f13bb868066096c94ec
  FirebaseInstanceID: 3b119bfe90e904851218159c9a4ecb847cc51d18
  FirebaseMessaging: ad9e1a80ea64905e01a0ce1b3eb76a2944544151
  GoogleDataTransport: 9a8a16f79feffc7f42096743de2a7c4815e84020
  GoogleDataTransportCCTSupport: 489c1265d2c85b68187a83a911913d190012158d
  GoogleUtilities: 39530bc0ad980530298e9c4af8549e991fd033b1
  nanopb: c43f40fadfe79e8b8db116583945847910cbabc9
  PromisesObjC: b48e0338dbbac2207e611750777895f7a5811b75
  Protobuf: 2793fcd0622a00b546c60e7cbbcc493e043e9bb9

PODFILE CHECKSUM: ced5e722d265e9d3328143105542747933ea87d1

COCOAPODS: 1.8.4

**Comment by andrehtissot** [comment]
1. cocoapods version 1.8.4 is good enough;
2. I didn't get it if you were able to install as you got a Podfile.lock that looks fine;
3. I'd recommend, if are you are still facing the "JSON::ParserError - A JSON text must at least contain two octets!" error, to upgrade your Ruby version, by either installing with rvm (https://rvm.io) or brew (https://brew.sh/)

**Comment by posdevelopers** [comment]
I uninstall and again install cocoapod so error is gone but when i try to build from xcworkspace then i got error firebase module not found

**Comment by joeljfernandes** [comment]
I am also getting the same issue on my ios app using ionic 3 and the latest cordova-ios platform. Is there any solution to this?
I have been struggling with this issue. Please help me.

'Firebase.h' file not found

Module 'Firebase' not found

**Comment by posdevelopers** [comment]
Same error stuck on this since 5 days

**Comment by joeljfernandes** [comment]
I dont know how to reinstall cocopods ....is it safe to reinstall the coco pods on the project?
What are the cli commands to do so?....

**Comment by posdevelopers** [comment]
I google it it's something like gem install cocoapod

**Comment by andrehtissot** [comment]
You have to run something like this:
1. Install RVM and follow the instructions
`\curl -sSL https://get.rvm.io | bash -s stable`
2. Install latest Ruby and follow the instructions
`rvm install ruby`
3. Install cocoapods
`gem install cocoapods`

The steps in between are informed when you finish install them, and are dependent of the development environment.

**Comment by posdevelopers** [comment]
Dear Please tell me how to resolve MODULE FIREBASE NOT FOUND error

**Comment by andrehtissot** [comment]
@posdevelopers, this is an issue related to your environment. You weren't able to install dependencies through Cocoapods. I'm working to help you, but you might need a more hands on support, which would be out of the scope of this free support.

I can, in the near future, provide hands on support by a remote desktop application/zoom using support hours claimed on patreon. Would you support that? And how much would you pledge to have issues like this fixed and prioritized?

**Comment by posdevelopers** [comment]
yes i can provide you anydesk remote session , and yes it's very urgent for me as i am stuck on this issue since two weeks

**Comment by posdevelopers** [comment]
can i integrate it without using cocoapods , https://firebase.google.com/download/ios , in this link it is stated that we can integrate the firebase sdk without using cocapods ?

**Comment by andrehtissot** [comment]
It's really not recommended to to through this route, as it'll impact on the size of your repository, or you'll have to share big chunk of files with your colleagues.

Did you try to follow the steps I mentioned here: https://github.com/andrehtissot/cordova-plugin-fcm-with-dependecy-updated/issues/108#issuecomment-651359785

**Comment by posdevelopers** [comment]
Yes i have followed above steps and it's installed updated version of cocoapod

**Comment by posdevelopers** [comment]
Now i am getting Module 'Firebase' not found

**Comment by posdevelopers** [comment]
It is giving error in FCMPlugin.m file , error in this line , @import Firebase, I am opening xcworkspace and all firebase sdk's are there in pod project

**Comment by posdevelopers** [comment]
Plugins/cordova-plugin-fcm-with-dependecy-updated/FCMPlugin.m:8:9: fatal error:
      module 'Firebase' not found
@import Firebase

**Comment by posdevelopers** [comment]
i think my project is not importing the pod dependencies like firebase and other modules , although libPods.a is there in LINK BINARY WITH LIBRARIES

**Comment by posdevelopers** [comment]
today error is changed from module firebase to #import "Firebase.h" firebase.h not found , i just reinstall the fcm plugin

**Comment by andrehtissot** [comment]
There shouldn't be any hard link.
Would you try to:
```bash
ionic cordova plugin remove cordova-plugin-fcm-with-dependecy-updated
rm -rf node_modules/cordova-plugin-fcm-with-dependecy-updated/
rm -rf plugins/cordova-plugin-fcm-with-dependecy-updated/
rm -rf platforms/ios/[APPLICATION NAME]/Plugins/cordova-plugin-fcm-with-dependecy-updated/
ionic cordova plugin add cordova-plugin-fcm-with-dependecy-updated
```

It doesn't make much sense, but maybe you are still fighting some old files.

**Comment by posdevelopers** [comment]
oh God, i am using sudo command to install fcm plugin , i removed it and now project is build successfully .

**Comment by andrehtissot** [comment]
Yeah, it's not recommended. Some dependencies, like cocoapods, even refuse to run with that level of access.

Please let me know if you face another issue.

**Comment by posdevelopers** [comment]
Thank you for wonderful support , let me know if i can use fcm plugin on ionic 3 like this

 import { FCM } from '@ionic-native/fcm';

**Comment by posdevelopers** [comment]
WARN: Ionic Native: tried calling FCM.getToken, but the FCM plugin is not installed.
2020-07-02 14:34:15.812495+0500 Kitabcha[1709:1335874] WARN: Install the FCM plugin: 'ionic cordova plugin add cordova-plugin-fcm-with-dependecy-updated'

**Comment by posdevelopers** [comment]
When i try on real device then it is giving me above error

**Comment by andrehtissot** [comment]
> Thank you for wonderful support , let me know if i can use fcm plugin on ionic 3 like this
> 
> import { FCM } from '@ionic-native/fcm';

No. @ionic-native/fcm is outdated.

Please import like:
```typescript
import { FCM } from 'cordova-plugin-fcm-with-dependecy-updated/ionic/v4';
```

**Comment by posdevelopers** [comment]
Let me try this thank you

**Comment by posdevelopers** [comment]
Hi i am trying this and having same error again

**Comment by andrehtissot** [comment]
@posdevelopers would you be more specific about which error you got again?

**Comment by posdevelopers** [comment]
Hi i am able to build and notification is received but when i am trying to upload it to app store then uiwebview email received from the apple

**Comment by posdevelopers** [comment]
previously without fcm it is uploaded to app store but after installing this plugin fcm with 7.0.5 version it is generating uiwebview error ,please help on this

**Comment by posdevelopers** [comment]
my cordova plugin list is :
com.telerik.plugins.nativepagetransitions 0.6.5 "Native Page Transitions"
cordova-plugin-android-permissions 1.0.2 "Permissions"
cordova-plugin-badge 0.8.8 "Badge"
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-fcm-with-dependecy-updated 7.0.5 "Cordova FCM Push Plugin"
cordova-plugin-fullscreen 1.1.0 "cordova-plugin-fullscreen"
cordova-plugin-geolocation 4.0.2 "Geolocation"
cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.2.1 "cordova-plugin-ionic-webview"
cordova-plugin-nativeaudio 3.0.9 "Cordova Native Audio"
cordova-plugin-nativestorage 2.3.2 "NativeStorage"
cordova-plugin-network-information 2.0.2 "Network Information"
cordova-plugin-splashscreen 5.0.4 "Splashscreen"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-vibration 3.1.1 "Vibration"
cordova-plugin-whitelist 1.3.4 "Whitelist"
cordova-sms-plugin 1.0.0 "Cordova SMS Plugin"
cordova-sqlite-storage 2.6.0 "Cordova sqlite storage plugin"
cordova.plugins.diagnostic 4.0.12 "Diagnostic"
mx.ferreyra.callnumber 0.0.2 "Cordova Call Number Plugin"

**Comment by posdevelopers** [comment]
already added WKWebViewOnly in config file and other things

**Comment by posdevelopers** [comment]
I have also received push notification everything is working fine but not be able to upload on app store and it is generating the error of uiwebview

**Comment by posdevelopers** [comment]
Hi i have resolved there is uiwebview in native transition plugin i removed it and now app is able to upload on app store and does not generate the warning of uiwebview depcreated 
https://github.com/Telerik-Verified-Plugins/NativePageTransitions
Thank you

**Comment by naveenm21** [comment]
Open **platfroms/ios/podfile**

```
# DO NOT MODIFY -- auto-generated by Apache Cordova
source 'https://github.com/CocoaPods/Specs.git'
source 'https://cdn.cocoapods.org/'
platform :ios, '11.0'
use_frameworks!
target 'Sampleapp' do
	project 'Sampleapp.xcodeproj'
	pod 'Firebase'
	pod 'Firebase/Analytics'
	pod 'Firebase/Messaging'
end

```

then `pod update`


hope it helps
