### ISSUE TITLE
after installing this plugin app throw this error.

### ISSUE THREAD

**Issue by sa-bangash** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated#109]
[cordova] Note: Some input files use or override a deprecated API.
[cordova] Note: Recompile with -Xlint:deprecation for details.
[cordova] D8: Program type already present: android.support.v4.os.ResultReceiver$MyResultReceiver
[cordova] 
[cordova] FAILURE: Build failed with an exception.
[cordova] 
[cordova] * What went wrong:
[cordova] Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
[cordova] > com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
[cordova]   Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
[cordova]   Program type already present: android.support.v4.os.ResultReceiver$MyResultReceiver

and also I  removed the platform and re-add the platform but still throw above issue.

**Comment by andrehtissot** [comment]
Relying on "android.support.v4" should not happen.
What I recommend, and have worked for others in a similar position, is to have it upgraded to androix on build, by adding the plugins:
```
cordova plugin add cordova-plugin-androidx
cordova plugin add cordova-plugin-androidx-adapter
```

More info can be found in the issue: https://github.com/andrehtissot/cordova-plugin-fcm-with-dependecy-updated/issues/72

If it doesn't work, let me know.
