### ISSUE TITLE
Cannot change the firebase project.

### ISSUE THREAD

**Issue by nekosgr93** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated#112]
English isn't my first language, so please excuse any mistakes.

I use ionic v5 with cordova-android 8.1.0.

I have two firebase project for different enviroments: **dev** & **stag**.

And there are two different google-service.json, **dev.json** & **stag.json**.
I only want apps in dev environment to receive messages that sent from dev project, not stag project. Vice versa.

How can I do this?

Build env :
ionic v5
cordova-cli 9.0.0
node 10.19.0
npm 6.13.4

cordova-android 8.1.0
cordova-plugin-fcm-with-dependecy-updated: 6.4.3

**Comment by andrehtissot** [comment]
What you could do for now is to add a pre-build step that copies the dev.json or stag.json file as one of this paths:
- `platforms/android/google-services.json`; or
- `platforms/android/app/google-services.json`.

This can become a feature, but it can be a little tricky. So not sure when this would be available.

**Comment by andrehtissot** [comment]
How do you currently run the app for each build?

**Comment by andrehtissot** [comment]
Usually, it's a part of CI/CD to replace the configuration file before building for production and uploading to the store.
Because sharing production credentials manually, or easily reachable, can lead to accidental leaking.

**Comment by nekosgr93** [comment]
I use a before build hook to replace the google-service.json file in android root directory with different project configs, which base on a custom environment variable.
ex: ENV=dev will use dev.json to replace the google-service.json in the android root.

Here is the code for this job:
```javascript
function changeGoogleService(env) {
  var argvs = process.argv;
  var filePath;
  var destPath;
  if (argvs.indexOf('android')) {
    filePath = './src/google-services-configs/' + env + '.json';
    destPath = [
      'platforms/android/google-services.json',
      'platforms/android/app/google-services.json'
    ];
  } else if (argvs.indexOf('ios')) {
    filePath = './src/google-services-configs/' + env + '.plist';
    destPath = [
      'GoogleService-Info.plist'
    ];
  }

  try {
    var stat = fs.statSync(filePath);
    if (!stat.isFile) {
      throw new Error('\n' + 'Google Service Config Error: ' + filePath + ' does not exist!');
    }
    destPath.forEach(function (dest) {
      fs.copyFileSync(filePath, dest);
    })
  } catch (err) {
    console.log(chalk.red('\n' + 'Google Service Config Error: ' + filePath + ' does not exist!'));
    process.exit(1);
  }
}
```

**Comment by nekosgr93** [comment]
Actually I have use the cordova-plugin-fcm-with-dependecy-updated@3.2.0 with my old ionic v3 project for a long time. And the hook above do the trick well. It can switch between projects with different environments.

But when I build a new app with cordova-plugin-fcm-with-dependecy-updated v6 or even higher, although the google-service.json changed in the android app root directory, either by hook or manually, does not change the firebase project it points to.

On the other hand, I notice that the file:
`platform/android/app/build/generated/res/google-services/${product flavor}/values/values.xml`
changed in cordova-plugin-fcm-with-dependecy-updated@3.2.0 but not in the later version. 

According to the google document, this file is generated by the google service plugin.
https://developers.google.com/android/guides/google-services-plugin#processing_the_json_file

So I think that maybe this is the plugin's issue. And found an open issue for this:
https://github.com/google/play-services-plugins/issues/144

Indeed, when I downgrade the google-service plugin to v3(also the version used by the fcm plugin v3), everything works fine. But when I upgrade to v4 or higher, the change in google-service.json does not reflect to the app.

**Comment by nekosgr93** [comment]
Currently the solution is use `cordova clean` before each build. It will clean the build resources and the sdk will use the google-service.json to generate a new one.
This works for me.

**Comment by andrehtissot** [comment]
Interesting... I'll try make a feature out of it in the future, as having it cleaning is less than ideal.
