### ISSUE TITLE
Plugin not installed

### ISSUE THREAD

**Issue by thiagosbrito** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated#113]
Hi,

I've been facing this `plugin_not_installed` error, tried to remove the plugin and re-add it again, although without success:

```
Native: tried calling FCM.hasPermission, but the FCM plugin is not installed.
```

Ionic-cli: version 5.4.16
Cordova: 9.0.0
Ng: 8.2.14

Can someone help me here?

**Comment by andrehtissot** [comment]
It is a ionic issue, not particular to this plugin.
I've been looking here https://github.com/ionic-team/ionic-native/issues/2038

How are you running the application?

**Comment by Lopuch** [comment]
Hello,
I have the same problem.
I run the application by calling ionic cordova run android --device
I tried to create a blank project to test it. Unfortunately with the same error.
I have FCM in app.module.ts providers.
I have google-service.json in root folder.
I call FCM by click on a button on my Home page. This is the source code:
`onButtonClick() {
        this.platform.ready().then(() => {
            console.log('Before');
            this.fcm.onTokenRefresh().subscribe(token => {
                console.log('refreshToken: ', token);
            });
            console.log('After');
        });
    }`

Console output:
FCM: has been created
FCM: Ready!
Ionic Native: deviceready event fired after 0 ms
Angular is running in the development mode. Call enableProdMode() to enable the production mode.
// Now I click the button
Before
(warning) Native: tried calling FCM.onTokenRefresh, but the FCM plugin is not installed.
(warning) Install the FCM plugin: 'ionic cordova plugin add cordova-plugin-fcm-with-dependecy-updated'
After
(error) ERROR plugin_not_installed

**Comment by Zerokk** [comment]
Same problem here...

**Comment by monsieurPaon** [comment]
Same problem 

WARN: Native: tried calling FCM.requestPushPermissionIOS, but the FCM plugin is not installed.
WARN: Install the FCM plugin: 'ionic cordova plugin add cordova-plugin-fcm-with-dependecy-updated'
WARN: Native: tried calling FCM.onTokenRefresh, but the FCM plugin is not installed.
WARN: Install the FCM plugin: 'ionic cordova plugin add cordova-plugin-fcm-with-dependecy-updated'
WARN: Native: tried calling FCM.onNotification, but the FCM plugin is not installed.
WARN: Install the FCM plugin: 'ionic cordova plugin add cordova-plugin-fcm-with-dependecy-updated'

etc etc..

    "cordova-plugin-fcm-with-dependecy-updated": "^7.0.1",
    "@ionic-native/fcm": "^5.27.0",

**Comment by firoz2580** [comment]
It seems like this plugin got some changes 2 days ago.

You just have to change the import statement.

New import: 
import { FCM } from "cordova-plugin-fcm-with-dependecy-updated/ionic/ngx";

And in constructor: 
constructor(private fcm: FCM, private platform: Platform){ }

Make sure to call any method from fcm after the device is ready.
i.e: 
this.platform.ready().then(() => {
   this.fcm.getToken()
      .then(deviceId => {})
      .catch(err => console.error(err))
}

See https://github.com/andrehtissot/cordova-plugin-fcm-with-dependecy-updated#with-ionic.

**Comment by monsieurPaon** [comment]
@firoz2580 i have update with exactly the same code, now we don't have error regarding plugin installation. But now the app didn't load stay on white screen on ionic 4.

**Comment by monsieurPaon** [comment]
Moreover import { FCM } from "cordova-plugin-fcm-with-dependecy-updated/ionic/v4" didn't work. ngx look ok.

**Comment by firoz2580** [comment]
@monsieurPaon Even I had the white screen issue, that was because this.fcm.onNotification() was called before device ready on my service file.

Is there any error/info on the console when you used ngx?

**Comment by andrehtissot** [comment]
Yes, due to issues of having the features working on older ionic versions, the ionic support was included as part of the main plugin. Hence, it's recommended to uninstall @ionic-native/fcm and import for the specific platform to be used on:
- "cordova-plugin-fcm-with-dependecy-updated/ionic" for Ionic 5;
- "cordova-plugin-fcm-with-dependecy-updated/ionic/ngx" for Ionic 5 with Angular; or
- "cordova-plugin-fcm-with-dependecy-updated/ionic/v4" for Ionic 4 or 3.

**Comment by monsieurPaon** [comment]
I'm on ionic 4 and "cordova-plugin-fcm-with-dependecy-updated/ionic/ngx" is the only working, but after building my ios version i don't received any notification, and the getToken received is not validate for firebase.

Curl response with a freshtoken from getToken method => {"multicast_id":6447992020040170454,"success":0,"failure":1,"canonical_ids":0,"results":[{"error":"NotRegistered"}]}%

**Comment by andrehtissot** [comment]
Did you call FCM.requestPushPermission()?

**Comment by monsieurPaon** [comment]
Yes for sure,  push permission request result: Yes
2020-06-30 12:34:29.668069-0400 myapp[40321:11152780] FCM: Ready!
2020-06-30 12:34:29.668162-0400 myapp[40321:11152780] start Js Event Bridge
2020-06-30 12:34:29.668242-0400 myapp[40321:11152780] haspermissiontrue

**Comment by monsieurPaon** [comment]
```
 public async setup() {
        return new Promise(async resolve => {
            return new Promise(resolve => {
                console.log('in promise');
                if (this.platform.is('cordova')) {
                    console.log('in cordova');
                    if (this.platform.is('ios')) {
                        console.log('in ios');
                        this.firebase.requestPushPermission().then((res => console.log('haspermission' + res)));
                    }

                    this.onTokenRefresh().subscribe(token => {
                        this.theToken = token;
                        console.log('onTokenRefresh()' + token);
                        resolve(true);
                    });
                }
                resolve(false);
            });
        });
    }
```

and call it from app.component.ts 

```
initializeApp() {
        this.platform.ready().then(() => {
            this.statusBar.styleDefault();
            this.splashScreen.hide();
            this.notificationSetup();
            this.initRoute();
        });
    }

private notificationSetup() {
        const presentToast = async (head, msg) => {
            const toast = await this.toastCtrl.create({
                message: msg,
                header: head,
                color: 'dark',
                duration: 4000
            });
            toast.present();
        };

        console.log('in setup before service');
        this.fcmService.setup().then(() => {
            console.log('in setup in service');

            this.fcmService.onNotifications().subscribe(notif => {
                console.log('notif is  ' + notif);
                if (notif.wasTapped) {
                    //Notification was received on device tray and tapped by the user.
                    alert(JSON.stringify(notif));
                    presentToast('heads up', JSON.stringify(notif));
                } else {
                    presentToast('heads up', JSON.stringify(notif));
                }
                presentToast("heads up", JSON.stringify(notif));
            });
        });
    }
```

**Comment by monsieurPaon** [comment]
Ok now i have update and take exactly the same configuration as your exemple. But i didn't received any notifications. I will open an issue related to it.

**Comment by elkhalifte** [comment]
Am having the same issue

**Comment by andrehtissot** [comment]
@monsieurPaon 
Would you share how you have the imports in both files?

AFAIK, your setup could be rewritten as:
```typescript
public async setup() {
    const permission = await this.firebase.requestPushPermission()
    console.log('hasPermission: ' + permission)
    const token = await this.firebase.getToken()
    console.log('token: ' + token);
}
```

**Comment by elkhalifte** [comment]
i had the same issue in my ionic 5 app and i fixed the problem like this :

i remplaced 

`import { FCM } from '@ionic-native/fcm/ngx';`

with 

`import { FCM } from 'cordova-plugin-fcm-with-dependecy-updated/ionic/ngx';`

**Comment by andrehtissot** [comment]
It's practically impossible for the ionic team to keep their wrapper compatible with cordova-plugin-fcm-with-dependecy-updated and on older versions o ionic. That's the reason I've implemented support for ionic as part of this plugin.

**Comment by CedLP** [comment]
> i had the same issue in my ionic 5 app and i fixed the problem like this :
> 
> i remplaced
> 
> `import { FCM } from '@ionic-native/fcm/ngx';`
> 
> with
> 
> `import { FCM } from 'cordova-plugin-fcm-with-dependecy-updated/ionic/ngx';`

thanks @elkhalifte you are the best it's work

**Comment by CedLP** [comment]
but now in postman i have a error "data" key "from" is a reserved keyword

in my body i hav ethis 
{
  "notification":{
    "title":"Ionic 4 Notification",
    "body":"Notification sent from POSTMAN",
    "sound":"default",
    "click_action":"FCM_PLUGIN_ACTIVITY",
    "icon":"fcm_push_icon"
  },
  "data":{
    "from":"codewithabdul.com"
  },
  "to":"mytoken",
  "priority":"high"
}

**Comment by tiagotrigger** [comment]
Hey guys, I'm having this problem as well.

I'm using the setup() method like @andrehtissot and the imports like @elkhalifte.
But the error is that firebase service is undefined.

```
const permission = await this.firebase.requestPushPermission()
TypeError: Cannot read property 'requestPushPermission' of undefined
```

**Comment by efaustor** [comment]
> i had the same issue in my ionic 5 app and i fixed the problem like this :
> 
> i remplaced
> 
> `import { FCM } from '@ionic-native/fcm/ngx';`
> 
> with
> 
> `import { FCM } from 'cordova-plugin-fcm-with-dependecy-updated/ionic/ngx';`

You help me a lot!

**Comment by StarlleyDev** [comment]
> i had the same issue in my ionic 5 app and i fixed the problem like this :
> 
> i remplaced
> 
> `import { FCM } from '@ionic-native/fcm/ngx';`
> 
> with
> 
> `import { FCM } from 'cordova-plugin-fcm-with-dependecy-updated/ionic/ngx';`

Tanks....
