### ISSUE TITLE
Will this plugin work with wkwebview for ionic 3 app?

### ISSUE THREAD

**Issue by Sagar-Khenat** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated#115]
Hello,
We are having an ionic 3 app, in which we had used cordova-plugin-firebase, when we submitted our app to appstore, it gave us the uiwebview warning.Came to know about this plugin from ionic native documentation, I wanted to know if we can use this for our ionic 3 project and if by using it I won't receive the uiwebview warning.Which versionof this plugin should I use for our ionic 3 app?
Any suggestions will be really helpful.

**Comment by andrehtissot** [comment]
Any version after 6.0.1 (https://github.com/andrehtissot/cordova-plugin-fcm-with-dependecy-updated/releases/tag/v6.0.1) will have the UIWebView replaced, in favor of WKWebView.

Although, to have support for ionic 3 and the new features, I'd recommend to install the newer version 7.0.2 (being release tonight), which you can import as "cordova-plugin-fcm-with-dependecy-updated/ionic/v4".

Please take a look on the features section, specially https://github.com/andrehtissot/cordova-plugin-fcm-with-dependecy-updated/blob/master/README.md#with-ionic
