### ISSUE TITLE
Ionic 3 AOT build fail: Function expressions are not supported in decorators in 'FCM'

### ISSUE THREAD

**Issue by matheuskt** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated#116]
Ionic 3 application. Have already made the changes of the new version.

This error is being thrown when trying to build the IOS and Android release build:

```
src/app/app.module.ts(230,5): 

Error during template compile of 'AppModule' Function expressions are not supported in decorators in 'FCM' 

'FCM' references 'ɵ0' 'ɵ0' contains the error at 
            cordova-plugin-fcm-with-dependecy-updated/ionic/v4/FCM.js.ts(5,12) 

Consider changing the function expression an exported function.
```

This is happening only to the production build. ```ionic cordova build ios --prod --release```.

The build is successful while building it with ```ionic cordova build ios```.

**Comment by matheuskt** [comment]
Changing the ```ionic/v4/FCM.js``` file content to the following made it work for me:

```
import { __decorate } from "tslib";
import { Injectable } from '@angular/core';
import { Plugin } from '@ionic-native/core';
import { Subject } from 'rxjs';

function FCM() {
}
FCM.prototype.clearAllNotifications = function () {
    return window.FCM.clearAllNotifications();
};
FCM.prototype.createNotificationChannel = function (channelConfig) {
    return window.FCM.createNotificationChannel(channelConfig);
};
FCM.prototype.getAPNSToken = function () {
    return window.FCM.getAPNSToken();
};
FCM.prototype.getInitialPushPayload = function () {
    return window.FCM.getInitialPushPayload();
};
FCM.prototype.getToken = function () {
    return window.FCM.getToken();
};
FCM.prototype.hasPermission = function () {
    return window.FCM.hasPermission();
};
FCM.prototype.onNotification = function (options) {
    var observable = new Subject();
    var handler = function (payload) { return observable.next(payload); };
    window.FCM.onNotification(handler, options);
    return observable;
};
FCM.prototype.onTokenRefresh = function (options) {
    var observable = new Subject();
    window.FCM.onTokenRefresh(function (token) { return observable.next(token); }, options);
    return observable;
};
FCM.prototype.requestPushPermission = function (options) {
    return window.FCM.requestPushPermission(options);
};
FCM.prototype.subscribeToTopic = function (topic) {
    return window.FCM.subscribeToTopic(topic);
};
FCM.prototype.unsubscribeFromTopic = function (topic) {
    return window.FCM.unsubscribeFromTopic(topic);
};
FCM = __decorate([
    Plugin({
        pluginName: 'FCM',
        plugin: 'cordova-plugin-fcm-with-dependecy-updated',
        pluginRef: 'FCM',
        repo: 'https://github.com/andrehtissot/cordova-plugin-fcm-with-dependecy-updated',
        platforms: ['Android', 'iOS'],
    }),
    Injectable()
], FCM);

export { FCM };
```

**Comment by andrehtissot** [comment]
Thank you for sharing. 
I'll use this to create a ".../ionic/v3" version soon.

And please, if you can test also on iOS, it would help get sorting any small issues.

**Comment by asamarcos** [comment]
> Changing the `ionic/v4/FCM.js` file's content to the following made it work for me:

Didn't work for me.

Ionic:

   Ionic CLI          : 6.10.1
   Ionic Framework    : ionic-angular 3.9.10
   @ionic/app-scripts : 3.2.4

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 1.2.1, (and 23 other plugins)

Utility:

   cordova-res : 0.11.0
   native-run  : 1.0.0

System:

   Android SDK Tools : 26.1.1
   NodeJS            : v12.16.2
   npm               : 6.9.0
   OS                : Windows 10

**Comment by Stephane84** [comment]
I have this bug too.
Just running `npm run build --prod` before to add platform show the mistake
In my case :

```
[09:26:38]  typescript error 
            Cannot find type definition file for '@types'. 

[09:26:38]  ionic-app-script task: "build" 
[09:26:38]  Error: Failed to transpile TypeScript 
Error: Failed to transpile TypeScript
    at errorCheckProgram (/Users/macmini/steph/ngc/cordova-plugin-fcm-with-dependecy-updated-ionic-v3-example-master/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:119:39)
    at Object.<anonymous> (/Users/macmini/steph/ngc/cordova-plugin-fcm-with-dependecy-updated-ionic-v3-example-master/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:89:21)
    at step (/Users/macmini/steph/ngc/cordova-plugin-fcm-with-dependecy-updated-ionic-v3-example-master/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:32:23)
    at Object.next (/Users/macmini/steph/ngc/cordova-plugin-fcm-with-dependecy-updated-ionic-v3-example-master/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:13:53)
    at fulfilled (/Users/macmini/steph/ngc/cordova-plugin-fcm-with-dependecy-updated-ionic-v3-example-master/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:4:58)
[ERROR] An error occurred while running subprocess ionic-app-scripts
```

I test replacing the content of FCM.js in node_modules/cordova-plugin-fcm-with-dependecy-updated/ionic/v4 but still have the error.

@asamarcos , is it the good file path ? You seem to have the same problem before ?

**Comment by andrehtissot** [comment]
@matheuskt @asamarcos
For the new version v7.0.3, the .../ionic/v4 build looks exactly like commented above. So no need to have a local patch after upgrading.

@Stephane84
Looks like your version of typescript doesn't allow _subpackages_.
I recommend to upgrade to the later version of typescript, as usually brings a lot of useful features and very few, if any, breaking changes.

**Comment by Stephane84** [comment]
@andrehtissot , it's with your ionic3 exemple : https://github.com/andrehtissot/cordova-plugin-fcm-with-dependecy-updated-ionic-v3-example
I Just git clone, `npm install` and `npm run build --prod` to produce this stack
Typescript is in version 3.9.5

**Comment by Stephane84** [comment]
I see here : https://stackoverflow.com/questions/56426772/cannot-find-type-definition-file-for-types to downgrade ionic/app-scripts from 3.2.4 to 3.2.3 and it works with the exemple, but broke my app with another error :

```
typescript error
            Can't resolve all parameters for MyApp in
            F:/Dev/Git/mobile/master/mobile-app/mobile-app-v2/src/app/app.component.ts: ([object Object], [object
            Object], [object Object], [object Object], [object Object], [object Object], ? , [object
```
? corresponding to FCM injection in constructor. I need to update typescript i think, but it broke my app elsewhere...

**Comment by andrehtissot** [comment]
I tried to debug the build code of @ionic/app-scripts to exhaustion, unsuccessfully.

Would you clone https://github.com/andrehtissot/cordova-plugin-fcm-with-dependecy-updated-ionic-v3-example and get it facing the same issue you have in your project?

**Comment by Stephane84** [comment]
Well, trying to reproduce my last bug on the exemple to give you a repo, finally, i can't reproduce it.

After many reseach, i think that i did test with wrong version of the plugin 7.0.2 and / or, one of my import was not ionic/v4 but ionic/ngx

This morning, verifying all slowly, i forget nothing, and now everything works well !!! version 7.0.3 is perfect.

Thanks a lot.

**Comment by matheuskt** [comment]
> Thank you for sharing.
> I'll use this to create a ".../ionic/v3" version soon.
> 
> And please, if you can test also on iOS, it would help get sorting any small issues.

Sorry I couldn't reply sooner, but the build was also successful on IOS since this was a problem with Angular AoT. Thanks for fixing it!
