### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by xeux** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated#117]
Running the command `ionic cordova plugin add cordova-plugin-fcm-with-dependecy-updated` return The system cannot execute the specified program, after Running command: install_ionic_dependencies.sh.

The scripts folder does not have the sh file.

Running: Windows 10, Ionic 5 in Command Prompt.

**Comment by xeux** [comment]
Solved using version 6.4.3, it does not have the .sh in the plugin.xml

**Comment by andrehtissot** [comment]
install_ionic_dependencies.sh is bash, 'cause even on Windows, I've been running bash (https://git-scm.com/downloads) for almost a decade. As there is nothing too bash-specific there, I belive it could have a `.bat` version with the same code

**Comment by andrehtissot** [comment]
This incompatibility is going to be addressed soon.

**Comment by andrehtissot** [comment]
You can follow the issue #119
