### ISSUE TITLE
Runtime warning: The default Firebase app has not yet been configured

### ISSUE THREAD

**Issue by bigleesan** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated#120]
Hello.
Spent a lot of time to build my project for IOS.
and I saved GoogleService-Info.plist in folder ( Project -> Resources )
I cannot find any reason why this would happen. Here is the code:

2020-07-09 09:53:20.006416+1200 pushtest[11839:871372] 6.27.0 - [Firebase/Core][I-COR000003] The default Firebase app has not yet been configured. Add [FIRApp configure]; (FirebaseApp.configure() in Swift) to your application initialization. Read more: https://goo.gl/ctyzm8.

Thanks.

//=======================================================
// ios environment
//=======================================================
cordova-lib@9.0.1 with:
cordova-common@3.2.1
cordova-create@2.0.0
cordova-fetch@2.0.1
cordova-serve@3.0.0

Environment:
OS: darwin
Node: v12.16.1
npm: 6.13.4

iOS platform:
Xcode 11.5

**Comment by andrehtissot** [comment]
It's not an issue, it's a expected warning.

The firebase configuration is slightly delayed to avoid deadlock with Watchdog:
https://github.com/andrehtissot/cordova-plugin-fcm-with-dependecy-updated/releases/tag/v4.6.3
