### ISSUE TITLE
Force show in foreground

### ISSUE THREAD

**Issue by felipeguerrero87** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated#125]
Hi

have this plugin force show notification in foreground?

I have my application that need notification in foreground

Can I force the notification view to the foreground?

**Comment by andrehtissot** [comment]
I recommend, instead, that you used in combination with https://github.com/katzer/cordova-plugin-local-notifications.

This second plugin allows you do show your foreground notifications with all the bells and whistles.
