### ISSUE TITLE
Sound notification on DND

### ISSUE THREAD

**Issue by felipeguerrero87** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated#126]
Hi

I need the push notification to have sound even when DND is activated, for a critical process

how can you configure this with this plugin?

thank

**Comment by andrehtissot** [comment]
You can't force it.
You can set the priority and, for android, importance, increasing the chance of it being presented.

But it always depends on the OS to decide to show it or not.

On Android you might have custom OS versions that might allow you.

As an non-first-party app on a smartphone, the user will always be able to set the level of annoyance of notifications, sound being one of them.
