### ISSUE TITLE
When will the onTokenRefresh() method be called. Using this plugin for our ionic 3 app

### ISSUE THREAD

**Issue by Sagar-Khenat** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated#127]
Hi @andrehtissot , I am using this fcm plugin instead of the cordova-plugin-firebase for our ionic 3 project, as we receive the uiwebview warnings with the firebase plugin. I have used version  "cordova-plugin-fcm-with-dependecy-updated": "7.0.2" and used it in our function as import { FCM } from "cordova-plugin-fcm-with-dependecy-updated/ionic/v4";
After the user has logged in we are calling the getToken() method as:

```javascript
async getToken() {
	var token;
	if (this.platform.is('android')) {
		token = await this.fcm.getToken();
	}
	this.fcm.onTokenRefresh().subscribe((token) => {
		this.sendPushNotification(token);
		console.log("onTokenRefresh success =======================>",token);
	});
}
```

As you can see in the function above, I am sending the token to backend, in the onTokenRefresh() function for receiving the notifications on the device, wanted to know how the onTokenRefresh method will work, as the cordova-plugin-firebase always called the onTokenRefresh method when the user is logging in. Also we have an API call when the user is logging out from the app.
I also wanted to know how we can send push messages in the foreground as well as in background. While sending push, in the backend we are using curl method as:

```php
$fields = array(
	'registration_ids'  => $registration_id,
	'notification' => array (
		"body" => $data['message'],
		"title" => $data['title'],
		"icon" => "myicon"
	)
);

$ch = curl_init();
curl_setopt( $ch, CURLOPT_URL, 'https://fcm.googleapis.com/fcm/send');
curl_setopt( $ch, CURLOPT_POST, true );
curl_setopt( $ch, CURLOPT_HTTPHEADER, $headers );
curl_setopt( $ch, CURLOPT_RETURNTRANSFER, false );
curl_setopt( $ch, CURLOPT_SSL_VERIFYPEER, false );
curl_setopt( $ch, CURLOPT_POSTFIELDS, json_encode( $fields ) );		
$result = curl_exec($ch );
```

Any suggestions will be really helpful.

**Comment by andrehtissot** [comment]
I recommend you to change the app code slightly like:
```javascript
async getToken() {
	if (!this.platform.is('cordova')) {
        // Only runs on Android and iOS builds
        return;
	}

    const token = await this.fcm.getToken();
    if (token) {
        // If it's already defined, it'll be sent right away
        console.log("sendPushNotification success =======================>", token);
		this.sendPushNotification(token);
    }

	this.fcm.onTokenRefresh().subscribe((token) => {
        // When it's defined, or updated, it'll be sent
		this.sendPushNotification(token);
		console.log("onTokenRefresh success =======================>", token);
	});
}
```

**Comment by andrehtissot** [comment]
On the server side, I'd also recommend a few changes:
```php

$fields = array(
    'registration_ids'  => array( $registration_id ),
    "notification" => (
        "title" => $data['message'],
        "body" => $data['message'],
        "icon" => "myicon",
        "click_action" => "FCM_PLUGIN_ACTIVITY", // Required for tapping behavior on Android
    ),
    "data" => ( // Required non-empty data param for Android, to enable notification being passed on from OS to the app
        "something" => "something", 
    ),
);

$ch = curl_init();
curl_setopt( $ch, CURLOPT_URL, 'https://fcm.googleapis.com/fcm/send');
curl_setopt( $ch, CURLOPT_POST, true );
curl_setopt( $ch, CURLOPT_HTTPHEADER, $headers );
curl_setopt( $ch, CURLOPT_RETURNTRANSFER, false );
curl_setopt( $ch, CURLOPT_SSL_VERIFYPEER, false );
curl_setopt( $ch, CURLOPT_POSTFIELDS, json_encode( $fields ) );		
$result = curl_exec($ch );
```

**Comment by andrehtissot** [comment]
Please let me know if find any issues.

**Comment by Sagar-Khenat** [comment]
Thank you @andrehtissot  for your prompt reply, I will check and update you for these changes.

**Comment by Sagar-Khenat** [comment]
Hi @andrehtissot , after your suggestions, I added your plugin and made changes on the frontend side. On the server side, I made this change:
$fields = array(
			'registration_ids'  => $registration_id,
			'notification' => array (
					"body" => $data['message'],
					"title" => $data['title'],
					"icon" => "myicon",
					//TODO: Add data here for fcm plugin
					"click_action" => "FCM_PLUGIN_ACTIVITY", // Required for tapping behavior on Android
			),
			//TODO:Data payload shown here for fcm plugin changes
			'data' => array ( 
				// Required non-empty data param for Android, to enable notification being passed on from OS to the app
				"body" => $data['message'] 
			)
);

After the changes, I am able to receive push notifications when the app is in BACKGROUND mode. But I am not receiving the notifications when my app is open and in FOREGROUND mode.
The function onNotification() is getting called when the app is open and in FOREGROUND mode though.Please let me know if I have done the changes correctly, or if I have to add some more steps.

**Comment by andrehtissot** [comment]
What you described looks like the expected behavior: https://github.com/andrehtissot/cordova-plugin-fcm-with-dependecy-updated#how-it-works

**Comment by Sagar-Khenat** [comment]
Ok @andrehtissot , Mainly I wanted to use your plugin for our iOS app. So without using the cordova-plugin-local notifications, will the fcm plugin work for both when app is in foreground and background?

**Comment by andrehtissot** [comment]
Yes.
