### ISSUE TITLE
Ionic 5 implementation Error on Android

### ISSUE THREAD

**Issue by RichardBoyder** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated#129]
Hi Andre

How do I use the plugin now in ionic 5?

**Comment by RichardBoyder** [comment]
im using 
 "@ionic/angular": "^5.1.0",

**Comment by RichardBoyder** [comment]
I've tried using it straight after import like this but doesn't work:

import { FCM } from "cordova-plugin-fcm-with-dependecy-updated/ionic";

then inside the class I call:

async obtainFCMToken() {
 await FCM.requestPushPermission().then(response => {
   });
}

**Comment by RichardBoyder** [comment]
**import { FCMPluginOnIonic } from "cordova-plugin-fcm-with-dependecy-updated/ionic";**

also added it to **app.component.ts** and added **FCMPluginOnIonic** in **provider** section.

It works perfectly in Apple with no errors.

@andrehtissot  Its not working in Android I get a error:
<img width="1519" alt="Screenshot 2020-07-16 at 21 59 43" src="https://user-images.githubusercontent.com/16017411/87716801-a9c9cb80-c7af-11ea-8f28-583ee45de69c.png">

So the actual code:
 this.fcm.requestPushPermission().then(response =>{.  Works in Android, I get a True

however when I try  **this.fcm.getToken().then(token => {.**  Android throws the error above.

**Comment by andrehtissot** [comment]
That's an issue I've never seen before.
But I'd check if the google-services.json files is correct, as the "sender id", mentioned in the error message, is one of the values there configured.

**Comment by andrehtissot** [comment]
Please let me know if re-downloading the `google-services.json` and comparing to the current one you have in the app shows no difference.

**Comment by RichardBoyder** [comment]
> Please let me know if re-downloading the `google-services.json` and comparing to the current one you have in the app shows no difference.

@andrehtissot  Yeah I redownloaded the google-services.json from firebase console.. made sure its prod application and they are identical. 

Double checked. And I downloaded the apple plist from same page... so for sure same :) 

ive installed the latest version :

**ionic cordova plugin add cordova-plugin-fcm-with-dependecy-updated@latest**

Am I calling the correct thing in my post above?  using **FCMPluginOnIonic**

**Comment by RichardBoyder** [comment]
ive tried this as well same deal.
import { FCM } from "cordova-plugin-fcm-with-dependecy-updated/ionic";

FCM.requestPushPermission().then(response =>{
      console.log(response);
      if(response){
        FCM.getToken().then(token => {
          this.storeFCMTokenToClient(token);
        });
        FCM.onTokenRefresh().subscribe(token => {
          this.storeFCMTokenToClient(token);
        });
    
        FCM.onNotification().subscribe(data => {
          if (data.wasTapped) {
            this.presentAlertCreateBadge(data); // Google Cloud messaging console
          } else {
            this.presentAlertCreateBadge(data); // Google Cloud messaging console
          }
        });
      }
    });

**Comment by andrehtissot** [comment]
> Am I calling the correct thing in my post above? using **FCMPluginOnIonic**

Thank you @RichardBoyder  for pointing it out. I didn't notice it last time.
The import should be FCM, like:
```typescript
import { FCM } from "cordova-plugin-fcm-with-dependecy-updated/ionic";
```

**Comment by andrehtissot** [comment]
> ```ts
> import { FCM } from "cordova-plugin-fcm-with-dependecy-updated/ionic";
> 
> FCM.requestPushPermission().then(response => {
> 	console.log(response);
> 	if(response){
> 		FCM.getToken().then(token => {
> 			this.storeFCMTokenToClient(token);
> 		});
> 		FCM.onTokenRefresh().subscribe(token => {
> 			this.storeFCMTokenToClient(token);
> 		});
> 
> 		FCM.onNotification().subscribe(data => {
> 			if (data.wasTapped) {
> 				this.presentAlertCreateBadge(data); // Google Cloud messaging console
> 			} else {
> 				this.presentAlertCreateBadge(data); // Google Cloud messaging console
> 			}
> 		});
> 	}
> });
> ```

This code seems good.

As you described, it also triggers `INVALID_SENDER` native android error. Of which I'll have to search for solutions.

**Comment by RichardBoyder** [comment]
Thankyou Andre  for your effort . It is always appreciated.

**Comment by RichardBoyder** [comment]
I reverted to 6.0.4 and also refreshed my firebase apps removed and readied ... so it works again. 

Ill reinstall the latest plugin and test again and let you know how it goes.

Im not sure why the error is gone now... but ill keep you updated @andrehtissot

**Comment by andrehtissot** [comment]
Issue closed due to inactivity.
