### ISSUE TITLE
I cant make it works in ios device..

### ISSUE THREAD

**Issue by andrehtissot** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated#131]
I cant make it works in ios device..
It's a cordova only project.. i use 2 plugins: this (cordova-plugin-fcm-with-dependecy-updated) and inappbrowser..

I get the FCM token, i can send to this token with curl but it's not showing in device..

I requestPermission, add callback to onNotification and not make it work.

My device is a iphone 6s plus with ios in version 13.3.1

_Originally posted by @medeirosrafael in https://github.com/andrehtissot/cordova-plugin-fcm-with-dependecy-updated/issues/75#issuecomment-658940474_

**Comment by andrehtissot** [comment]
Hi @medeirosrafael, did you try to run the https://github.com/andrehtissot/cordova-plugin-fcm-with-dependecy-updated-app-example app with your google configuration files?

**Comment by AbdullaevTimur** [comment]
I have the same issue. I try to run **"app-example".**
```
cordova-plugin-fcm-with-dependecy-updated % FB_SERVER_KEY="AAAAxXXAPA91bEYoHV3Wd55HZc1S4PI1yQdMMclf8dB48WEm1oj01g7XjNXJpKJK52R8J1jqhTq0Mqp73bMwgyn_YEDplZYBdMbLb2tUd4jAovYyTEgrX7AW868BExTM4NddmXXXXXXXX" TARGET="/topics/ios" php tools/notify-both.php

fields:Array
(
    [notification] => Array
        (
            [title] => Notification title
            [body] => Notification body
            [click_action] => FCM_PLUGIN_ACTIVITY
        )

    [data] => Array
        (
            [param1] => value1
            [param2] => value2
        )

    [to] => /topics/ios
    [priority] => high
)


result:Array
(
    [message_id] => 8905242065049337999
)
```

But i did not recive anuthing on my iOS device (iphone 6s plus)

**Comment by andrehtissot** [comment]
@AbdullaevTimur
How did you got the iOS application installed on the device?

On iOS, Push notifications only works locally with a special certificate (https://customersupport.doubledutch.me/hc/en-us/articles/229495568-iOS-How-to-Create-a-Push-Notification-Certificate), or from builds installed from TestFlight or Apple Store. And only on real devices. Apple's rules.

**Comment by medeirosrafael** [comment]
> Hi @medeirosrafael, did you try to run the https://github.com/andrehtissot/cordova-plugin-fcm-with-dependecy-updated-app-example app with your google configuration files?

Apparently my problem was on firebase console with apple's CERTs..
I did make a fully fresh install (new certs, etc), and now it's working.
Thanks!

**Comment by andrehtissot** [comment]
Issue closed due to inactivity.
