### ISSUE TITLE
AddressBook dependency needed ? 

### ISSUE THREAD

**Issue by QuentinFarizon** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated#133]
Hello, and first of all many thanks for the great work on this plugin

I was just wondering why the dependency on AddressBook is needed ? https://github.com/andrehtissot/cordova-plugin-fcm-with-dependecy-updated/blob/master/plugin.xml#L134

It has been deprecated since ios 9 and gives warning when building : https://stackoverflow.com/questions/35078777/address-book-ui-framework-deprecated-methods

**Comment by andrehtissot** [comment]
I believe they haven't been necessary for some time.
A new version will be released soon with those removed.
