### ISSUE TITLE
Send notifications can't be send from Device with ionic-native HTTP

### ISSUE THREAD

**Issue by NLueg** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated#134]
Hi there! I know, that this is a bit off-topic, but some kind related anyway ...
I use this plugin to listen to topics and push-notifications in general and this works fine for my case. But the problem is, that I can't send notifications to topics with firebase.
I did a bit of research for this problem and the existing issues always have a typo or something like that. I think this is not the case here.

I currently try to send a notification to a specific user by sending a notification to the specific topic of the user.
I have the following code.

```typescript
  import { HTTP } from "@ionic-native/http/ngx";

  constructor(private http: HTTP) {}

  public sendNotification(uid: string) {
    const data = {
      notification: {
        title: "Test",
        body: "Test Message",
        sound: "default",
      },
      to: "/topics/" + uid,
      priority: "high",
    };

    const options = {
      Authorization:
        "key=<my-key>",
    };

    const url = "https://fcm.googleapis.com/fcm/send";

    return this.http
      .post(url, data, options)
      .then((response) => console.log("Response: ", response))
      .catch((err) => console.log("Error:", err));
  }
```

I always receive the following response from firebase:

```json
{
    "multicast_id": 3896795376476842347,
    "success": 0,
    "failure": 1,
    "canonical_ids": 0,
    "results": [
        {
            "error": "InvalidRegistration"
        }
    ]
}
```

When I send the **exact same** data with postman, it works without any problems.
Am I doing anything wrong?

Thank you for your response.

**Comment by andrehtissot** [comment]
Try the options as bellow:
```typescript
const options = {
	"Authorization:key": "<my-key>",
	"Content-Type": "application/json"
};
```

**Comment by NLueg** [comment]
Same result 😔  So you don't see any problem inside my code too?

**Comment by andrehtissot** [comment]
There is another thing you could try:
Instead of using: `to: "/topics/" + uid,` you can try `topic: uid,`

**Comment by NLueg** [comment]
That doesn't work with Postman too ... Then I get the same error as mentioned above but now it's reasonable 😄 
The `uid` where I try to send the notification too is a custom topic I defined for every user based on the firebase user-id.
Based on the documentation such requests should start with `/topics/` which is the case in my code.

**Comment by andrehtissot** [comment]
Did you try to send, from the app, to a device by it's FCM token?

**Comment by NLueg** [comment]
Yes, that works without any problems ... it all seams like firebase is handling the same request from postman and from my ionic-app differently ... does this make any sense?

**Comment by andrehtissot** [comment]
It kind of does. As postman also sends some headers by default.
Would you share your Postman call a cURL command?

**Comment by NLueg** [comment]
@andrehtissot I finally fixed it! 😍  Not verify satisfying but I just changed the http-native-client with the angular `HttpClient` and it works directly. As it is not required that I use the native-client I will just work with the angular-client.
I really have no idea why the behavior of both clients is that different but that's ok for me 😄 

So my final code is this one:

```typescript
  import { HttpClient } from "@angular/common/http";

  constructor(private http: HttpClient) {}

  public sendNotification(uid: string, title: string, body: string) {
    const data = {
      notification: {
        title,
        body,
      },
      to: "/topics/" + uid,
      priority: "high",
    };

    this.log.debug("Will send notification", data);

    const options = {
      Authorization:
        "key=<my-key>",
      "Content-Type": "application/json",
    };

    const url = "https://fcm.googleapis.com/fcm/send";

    return this.http
      .post(url, data, { headers: options })
      .subscribe((response) => console.log("Response: ", response));
  }
```

Thank you very much for your help anyway!
