### ISSUE TITLE
Is there a demo/tutorial?

### ISSUE THREAD

**Issue by senniswpg** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated#135]
I have an Ionic 4 app that had this working with v2.4.x, and I have come up to v6.4.1 to deal with the deprecated iOS wkwebview module, but clearly more has changed than I thought between the two version.

I can get the token, but I can't get the onNotification to fire.

I'm going to move up to 7.0.x shorty as I see discussion of it being a problem with v6.4 when the app is in the foreground. 
Is there a demo/tutorial that works with v6.4 or v.7.0 I can check out to stare and compare my code with to see where I might be going wrong?

**Comment by andrehtissot** [comment]
Not specifically for Ionic 4, but the app code itself shouldn't be too different from the ones you can find in the example apps https://github.com/andrehtissot/cordova-plugin-fcm-with-dependecy-updated#example-apps

Let me know if you find any issues.
