### ISSUE TITLE
local variable exception is accessed from within inner class; needs to be declared final

### ISSUE THREAD

**Issue by prteekagni** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated#136]
[cordova] D:\development\photorewards\photorewards\platforms\android\app\src\main\java\com\gae\scaffolder\plugin\FCMPlugin.java:230: error: local variable exception is accessed from within inner class; needs to be declared final
[cordova]                 put("message", exception.getMessage());
[cordova]                                ^
[cordova] D:\development\photorewards\photorewards\platforms\android\app\src\main\java\com\gae\scaffolder\plugin\FCMPlugin.java:231: error: local variable exception is accessed from within inner class; needs to be declared final
[cordova]                 put("cause", exception.getClass().getName());
[cordova]                              ^
[cordova] D:\development\photorewards\photorewards\platforms\android\app\src\main\java\com\gae\scaffolder\plugin\FCMPlugin.java:232: error: local variable exception is accessed from within inner class; needs to be declared final
[cordova]                 put("stacktrace", exception.getStackTrace().toString());

**Comment by andrehtissot** [comment]
The fix was released as 7.0.9.
