### ISSUE TITLE
Cocoapods source changed after upgrading.

### ISSUE THREAD

**Issue by andrehtissot** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated#141]
BTW, @andrehtissot, When I moved from 7.0.3 to 7.0.9 I got an issue during 'cordova platform add ios' and I found that the cause is the change in plugin.xml:
from: source url="https://cdn.cocoapods.org"
to: source url="https://github.com/CocoaPods/Specs.git"

I'm using the plugin on 2 projects (and different build machines):

- One project is only with cordova, and with the new source url when running 'platform add ios', right after it adds this fcm plugin, and 'Running command: pod install" it thrown an error:
`19:50:06 Installing "cordova-plugin-fcm-with-dependecy-updated" for ios
19:50:08 Running command: pod install --verbose
19:50:09 Failed to install 'cordova-plugin-fcm-with-dependecy-updated': Error: pod: Command failed with exit code 31
19:50:09     at ChildProcess.whenDone (/Users/FrontendJenkins/.jenkins/workspace/_WeR_Production/mobile/node_modules/cordova-common/src/superspawn.js:135:23)
19:50:09     at emitTwo (events.js:106:13)
19:50:09     at ChildProcess.emit (events.js:191:7)
19:50:09     at maybeClose (internal/child_process.js:877:16)
19:50:09     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
19:50:09 pod: Command failed with exit code 31`

- The other project is Ionic with cordova, and with the new source url when running 'platform add ios', right after it adds this fcm plugin, and 'Running command: pod install" it just hangs on this message:
`Installing "cordova-plugin-fcm-with-dependecy-updated" for ios
Running command: pod install --verbose
Cloning into' cocoapods'...`

So I'm using version 7.0.9 but with the old url - "https://cdn.cocoapods.org"
is it ok?
Thanks.

_Originally posted by @itziks00 in https://github.com/andrehtissot/cordova-plugin-fcm-with-dependecy-updated/issues/138#issuecomment-665485813_

**Comment by andrehtissot** [comment]
Yes @itziks00, that was intentional.

Unfortunately, the CDN is not as reliable as expected, even if the running version of cocoapods supports it.
For this reason, the cocoapods source auto-cdnfy was removed from the project https://github.com/andrehtissot/cordova-plugin-fcm-with-dependecy-updated#version-707-17072020.

This functionality is still available as a standalone plugin https://github.com/andrehtissot/cordova-plugin-cocoapods-cdn

**Comment by itziks00** [comment]
Thanks,
- So why do you think it I have these failures using the full version of 7.0.9 with the new url?
- Is it a risk to use the complete 7.0.9 source, only with the old cdn?

- Not related - Is it possible add additional parameter to the payload sent to browser, except the 'wasTapped'?
  a 'foreground' parameter tells if the push callback in the browser was done when the app was on background?
  the wasTapped isn't enough in my case to determine it.
In android, I added this code, but I don't know what to do in iOS...
`data.put("wasTapped", true);
 **data.put("foreground", !FCMPlugin.isBackground());**`

Thank you!

**Comment by andrehtissot** [comment]
Both should work most of the time.
CDN is much faster, but there were a few rare times when the service was unavailable.

So, the auto-switch to CDN was removed from the project and is now completely optional.

**Comment by andrehtissot** [comment]
> Thanks,
> 
>     * So why do you think it I have these failures using the full version of 7.0.9 with the new url?

Cocoapods have a messy cache system. Sometimes, the only way is to delete its cache folder.

>     * Is it a risk to use the complete 7.0.9 source, only with the old cdn, if it's the only thing works for me right now?

Both should work 99% of the time.

CDN is much faster, but there were a few rare times when the service was unavailable.

So, the auto-switch to CDN was removed from the project and is now completely optional.

>     * Not related - Is it possible add additional parameter to the payload sent to browser, except the 'wasTapped'?
>       a 'foreground' parameter tells if the push callback in the browser was done when the app was on background?
>       the wasTapped isn't enough in my case to determine it and handle some logic I need.
>       In android, I added this code, but I don't know what to do in iOS...
>       **`data.put("wasTapped", true);  data.put("foreground", !FCMPlugin.isBackground());`**


> Thank you!

**Comment by andrehtissot** [comment]
Also, if you have more than one concern, please create more than one github issue. Keeps the focus specific and helps others to search for solutions later.

**Comment by itziks00** [comment]
Thanks. I'll try clean the cache and update if it helped. I'll open another issue for the other question. Thank you.

**Comment by itziks00** [comment]
@andrehtissot clearing the cache didn't help, but currently I did a lot of builds using the old url - "https://cdn.cocoapods.org" and it always work (full 7.0.9 changes with this url change only).
So basically it should be OK, but only if I'll have issues when it's not available then I'll have to make the changes?
Thanks.

**Comment by andrehtissot** [comment]
> So basically it should be OK, but only if I'll have issues when it's not available then I'll have to make the changes?
I'm sorry, I didn't get it. Was it a question?
