### ISSUE TITLE
iOS >Build error  > Firebase not found

### ISSUE THREAD

**Issue by michaelpeterlee** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated#145]
Upgraded from v4 and now we cannot build iOS.

Plugins > AppDelegate+FCMPlugin.m

![image](https://user-images.githubusercontent.com/19398181/88991788-bc0e4280-d335-11ea-8cf8-e9fb88bd7c33.png)

**Comment by shanthan25** [comment]
use cocoapods to install compatible firebase sdk version

**Comment by andrehtissot** [comment]
@michaelpeterlee 
You you please share the console log of the execution of this line:
```bash
cordova plugin remove cordova-plugin-fcm-with-dependecy-updated; cordova plugin add cordova-plugin-fcm-with-dependecy-updated
```

... Or if you are running with Ionic:
```bash
ionic cordova plugin remove cordova-plugin-fcm-with-dependecy-updated; ionic cordova plugin add cordova-plugin-fcm-with-dependecy-updated
```

**Comment by michaelpeterlee** [comment]
```
bash-3.2# ionic cordova plugin remove cordova-plugin-fcm-with-dependecy-updated; ionic cordova plugin add cordova-plugin-fcm-with-dependecy-updated
> cordova plugin remove cordova-plugin-fcm-with-dependecy-updated
Uninstalling cordova-plugin-fcm-with-dependecy-updated from android
Android Studio project detected
Subproject Path: CordovaLib
Subproject Path: app
Uninstalling cordova-plugin-fcm-with-dependecy-updated from ios
Removing "cordova-plugin-fcm-with-dependecy-updated"
Removing plugin cordova-plugin-fcm-with-dependecy-updated from config.xml file...
Removing cordova-plugin-fcm-with-dependecy-updated from package.json
> cordova plugin add cordova-plugin-fcm-with-dependecy-updated
Installing "cordova-plugin-fcm-with-dependecy-updated" for android
Plugin doesn't support this project's cordova-android version. cordova-android: 7.1.4, failed version requirement: >=8.0.0
Skipping 'cordova-plugin-fcm-with-dependecy-updated' for android
Installing "cordova-plugin-fcm-with-dependecy-updated" for ios
Running command: /Users/mike/desktop/workspace/biolchim/biolchim-cdv/plugins/cordova-plugin-fcm-with-dependecy-updated/scripts/install_ionic_dependencies.bat /Users/mike/desktop/workspace/biolchim/biolchim-cdv
added 49 packages from 36 contributors and audited 50 packages in 2.003s

2 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

added 49 packages from 36 contributors and audited 50 packages in 2.181s

2 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

added 49 packages from 36 contributors and audited 50 packages in 2.599s

2 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

Adding cordova-plugin-fcm-with-dependecy-updated to package.json
Saved plugin info for "cordova-plugin-fcm-with-dependecy-updated" to config.xml
Android Studio project detected

```

**Comment by monokaijs** [comment]
Add this line between do - end into your Podfile (located at CordovaProject/platforms/ios/)
`pod 'Firebase/Messaging'`
![image](https://user-images.githubusercontent.com/42785824/89249907-a05cb200-d63d-11ea-9aa4-49d5c6b79ba3.png)

Open terminal, navigate to above directory, run this command:
`pod install`

Good luck!

**Comment by michaelpeterlee** [comment]
Our project is built with 'root' user, updated to CocoaPods pre-release and the Cordova iOS project is now broken. We since discovered that 4.1.0 actually works still [we suffered an interim FCM problem where they did not issue notifications in a timely manner], so downgraded; This should just simply work like prior versions.

**Comment by andrehtissot** [comment]
> discovered that 4.1.0 actually works still

It might, but it's not recommended to be used and it won't be accepted on the Apple Store as it uses the old UIWebView.

> [we suffered an interim FCM problem where they did not issue notifications in a timely manner], so downgraded; This should just simply work like prior versions.

The google SDK, in older versions, embedded into the plugin.
Which is not recommended by Google and, probably, a license issue.


Another workaround, of which I can't recommend, but it would be far better than downgrading this plugin's version is to install cordova-plugin-cocoapods-support, which should force the installation of cocoapods dependencies.

**Comment by ss-dc** [comment]
We had the same issue as our CI builds are performed in cloud, in order to fix we added the below to our config.xml

![image](https://user-images.githubusercontent.com/62385352/90486253-9a33fe80-e130-11ea-9983-cc201be81e76.png)

and we are using the below cocapod plugin to restore pods:

**cordova-plugin-cocoapod-supportx**

**Comment by michaelpeterlee** [comment]
v4.1.0 of this plugin has been accepted by Apple for many apps we are associated with.

**Comment by michaelpeterlee** [comment]
The deadline for updating UIWebView based apps has been extended by an unknown time: https://developer.apple.com/news/?id=edwud51q

**Comment by michaelpeterlee** [comment]
This plugin now works when building for iOS on M1 macOS.
