### ISSUE TITLE
Improve FCM.hasPermission() on Android

### ISSUE THREAD

**Issue by andrehtissot** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated#147]
Verify implementation of
- https://github.com/dpa99c/cordova-diagnostic-plugin#isremotenotificationsenabled

And if it would be interesting to internalize into this plugin.

**Comment by andrehtissot** [comment]
Thanks to @bwojtyca for mentioning this plugin.

**Comment by expcapitaldev** [comment]
@andrehtissot  hi! Any updates?  We can help with PR if it is need

**Comment by andrehtissot** [comment]
It's implemented and it'll be available in the next update.
