### ISSUE TITLE
Wake screen / Turn on screen during notification on Android

### ISSUE THREAD

**Issue by itziksha** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated#149]
Hi @andrehtissot 
I'm using plugin version 7.0.9.
When I worked with older version and old FCM BE API, the method "MyFirebaseMessagingService.onMessageReceived" was called when push was received on foreground and background (killed or not).
We had an option to send notification as 'data' and not 'notification' in the BE API payload, and handle the notification ourselves.

In this method, I created a notification myself using the NotificationManager, to show notification and also turned the screen on in case it was closed (using PowerManager wakeLock), when the app was on background or killed.

In our app it's not enough to play sound but we need to turn the screen on due to very important security notifications.

In the new version, due to the new FCM v1 API, notification isn't created in "onMessageReceived" but the BE send the notification with all params.
"onMessageReceived" method is being called now only when the app is on **foreground and not on background anymore.** and we couldn't find a solution for that in [FCM V1 API](https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages)
So, I moved the wake up screen code to the "MyFirebaseMessagingService.onCreate" method, but onCreate is being called only once. So, if the app is killed, it works once, **but if it's on background and screen is off, I can't turn the screen on.**

Do you have any suggestion how to make it, or where should I put the wake screen code so it will be called every time I have notification on background (killed or not)? Maybe something to change in the BE API to support 'data' messages as before?
(BTW, in iOS it seems it's always wakes the screen by the OS)

Thanks!

**Comment by andrehtissot** [comment]
To be able to receive into MyFirebaseMessagingService.onMessageReceived when the app is closed, the Push cannot have "notification".

My suggestion, for your case is to change your push payload to something like:
```json
{
  "token": "[FCM token]",
  "data":{
    "title":"Notification title to create notification mannually with",
    "body":"Notification body to create notification mannually with",
    "param1":"value1",
    "param2":"value2"
  },
  "ios": {
    "notification":{
      "title":"Notification title",
      "body":"Notification body",
      "sound":"default",
    }
  }
}
```

Let me know if you need anything else.
