### ISSUE TITLE
When user taps on a notification and app is closed, the push is lost

### ISSUE THREAD

**Issue by andrehtissot** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated#155]
Same here, when app is in foreground or background the onNotification works (calling wasTapped if App open from Notification) but when App is closed and the user clicks in the push notification the App open but onNotification or getInitialPushPayload didn't works

_Originally posted by @AngelBarrera in https://github.com/andrehtissot/cordova-plugin-fcm-with-dependecy-updated/issues/144#issuecomment-673736988_

**Comment by andrehtissot** [comment]
What I understood from your comment:
```
When
	Both
		App is closed
	And
		user clicks in the push notification
Then
	Both
		the App opens
	And
		neither onNotification or getInitialPushPayload work*
```
Let me know if I got it wrong.


And you defined "**work**" as: `It contains the wasTapped attribute`. Am I correct?

Also, is that issue coming from the app running on iOS and/or Android, and which OS versions?

**Comment by DaedalusAB** [comment]
Hi @andrehtissot 
I've spend some hours trying to figure this out. Could you please include a pointer about this in the github readme (for me, it wasn't common knowledge)

Thank you!

**Comment by lubakpoleng** [comment]
same here

**Comment by lubakpoleng** [comment]
Hi @andrehtissot , I think when app minimize click on notification, subscribe executed

**Comment by lubakpoleng** [comment]
@andrehtissot btw i'm on android 10

**Comment by lubakpoleng** [comment]
Hi @andrehtissot, thanks for response, i'm able to make it work. need to set priority to high. tested via postman

**Comment by freescout-helpdesk** [comment]
Same issue here, `priority` is set to "high".
