### ISSUE TITLE
Ionic banner notification in Android

### ISSUE THREAD

**Issue by nosTa1337** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated#161]
Hi,

is there any possibility to show the notification as a banner on the top? I have searched for this issue now for several hours and cannot find a solution. 

I have made it work to get the notifications. But when the device is active notifications are only shown in the tray and I do not get a popup like message or banner as if e.g. I will receive a whatsapp message. Therefore it may not be visible on first sight that a new notification has arrived.

Current behaviour:

![2020-08-24 15_14_39-SM G960F](https://user-images.githubusercontent.com/13113717/91049002-cbbf3500-e61c-11ea-9ec1-27a0b57edacc.png)

![2020-08-24 15_14_55-SM G960F](https://user-images.githubusercontent.com/13113717/91049007-cd88f880-e61c-11ea-9e93-48a5bb672917.png)

Expected behaviour:
![2020-08-24 15_15_05-SM G960F](https://user-images.githubusercontent.com/13113717/91049026-d5489d00-e61c-11ea-99a7-e0b94b82de9e.png)

Best regards,
Philipp

**Comment by nosTa1337** [comment]
Nevermind. Sometimes the user is the problem.

I found out that un der the app notifications I had to click "others" to set up all the options for this notification (like vibration, popup etc).

**Comment by luisVargasGu** [comment]
> Nevermind. Sometimes the user is the problem.
> 
> I found out that un der the app notifications I had to click "others" to set up all the options for this notification (like vibration, popup etc).

Could you expand on what you did?

Under the app notification settings on my phone I only see "Allow notification dot" and It didn't change what the incoming notification looked like or enable a banner?
