### ISSUE TITLE
plugin_not_installed error in ionic 6 

### ISSUE THREAD

**Issue by danijel2017** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated#162]
I installed cordova-plugin-fcm-with-dependecy-updated and @ionic-native/fcm

if I used "import { FCM } from 'cordova-plugin-fcm-with-dependecy-updated/ionic/ngx' "
I faced this error
![image](https://user-images.githubusercontent.com/38466352/91068896-83793480-e667-11ea-875b-05b5598800b7.png)

If I used "import { FCM } from '@ionic-native/fcm/ngx';"
I got plugin_not_installed error
![Screenshot_1](https://user-images.githubusercontent.com/38466352/91069184-a86da780-e667-11ea-8c26-eda1e5679d82.png)

It is critical error to use FCM push notification
How can I solve this problem
Please help me

**Comment by andrehtissot** [comment]
The package `@ionic-native/fcm` shouldn't be used with `cordova-plugin-fcm-with-dependecy-updated@7+`.

The import is correct as 
```typescript
import { FCM } from 'cordova-plugin-fcm-with-dependecy-updated/ionic/ngx'
```

The error message is an Firebase SDK error.
Did you add the correct `google-services.json` to the root project?

Would you provide a git repository with the same application dependencies for debugging?

**Comment by ayushmishra1803** [comment]
install the following plugin first 1 cordova plugin add cordova-plugin-androidx 2 cordova plugin add cordova-plugin-androidx-adapter now import fcm as import { FCM } from "cordova-plugin-fcm-with-dependecy-updated/ionic/ngx"; remove platforms and add them again then build the project again
