### ISSUE TITLE
No notification data (event), if app was completely closed

### ISSUE THREAD

**Issue by philippk2604** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated#163]
**Describe the bug**
If the app was completely closed and a push notification receives, the notification shows correctly in the header. If I tap on the notification, the app starts, but no data of "onNotification" is available in the javascript callback (javascript event not firing)
So the app cannot switch to the correct page.

**To Reproduce**
1. Kill app
2. Send a push notification to the app
3. Tap on the notification to start the app
4. App shows the "home page" (normally index.html), but the javascript event "onNotification" is not firing.

**Expected behavior**
The "onNotification" event is fired an the app can dispatch for example to the correct page or can read the data of the notification payload.

**Environment (please complete the following information):**
 - Developer OS and version: Windows 10
 - Mobile OS and version: Android 10
 - Cordova CLI version (cordova --version): 10.0.0

**Package.json**
[package.zip](https://github.com/andrehtissot/cordova-plugin-fcm-with-dependecy-updated/files/5125837/package.zip)

Best regards,
Philipp

**Comment by taskbox-joe** [comment]
I think that, from a cold start you need to call
```
FCM.getInitialPushPayload().
    .then(pushNotification => {
        // react to push notification
    });
```

**Comment by philippk2604** [comment]
> I think that, from a cold start you need to call
> 
> ```
> FCM.getInitialPushPayload().
>     .then(pushNotification => {
>         // react to push notification
>     });
> ```

Hi taskbox-joe.

Thanks for the hint.
But sorry, I'm unable to receive the data of the notification.

Maybe you have another hint for me?

Normally I get the data via:
`
FCM.onNotification(function(data) {
 ...
 // for example: data.wasTapped or another custom data-value
});
`

**Comment by chuongpnt** [comment]
same here , it worked on foreground and background . But when i closed app and receive notification and i tapped on this notification it redirect me to homepage ( not the page i want) . try to move .onNotification outside this.platform but it show Cannot read property 'onNotification' of undefined

    this.platform.ready().then(() => {

	if (this.platform.is("cordova")) {

		this.fcm.requestPushPermission();
		
		this.fcm.onTokenRefresh().subscribe(fcmToken => {				
			this.saveFCM(fcmToken, hotelIds).then((data: any) => {

			}, err => alert('no save token: ' + err));
			localStorage.setItem('fcmToken', fcmToken);
			this.fcmToken = fcmToken;
		});
		
		this.fcm.onNotification().subscribe((data) => { 
		alert(JSON.stringify(data, null, 4));
			if(data.wasTapped) {
				this.hotelChanged(data.hotel_id , data.booking_id);		
				this.router.navigateByUrl('/menu/booking-details/' + data.booking_id);
			}
		});
	}
    });

**Comment by ismailcse11** [comment]
same problem  for me.

**Comment by andrehtissot** [comment]
@chuongpnt presented a very clear case here. Of which is subscribing to change events, but not fetching already set values.

It's important to react to events, like `onNotification` (https://github.com/andrehtissot/cordova-plugin-fcm-with-dependecy-updated-ionic-v5-example/blob/master/src/app/home/home.page.ts#L36) and `onTokenRefresh` (https://github.com/andrehtissot/cordova-plugin-fcm-with-dependecy-updated-ionic-v5-example/blob/master/src/app/home/home.page.ts#L30).

But if you are subscribing after the information has been received natively, the event will not be retriggered.

For these cases, you can fetch the current data. Like in `getToken` (https://github.com/andrehtissot/cordova-plugin-fcm-with-dependecy-updated-ionic-v5-example/blob/master/src/app/home/home.page.ts#L44) and `getInitialPushPayload` (https://github.com/andrehtissot/cordova-plugin-fcm-with-dependecy-updated-ionic-v5-example/blob/master/src/app/home/home.page.ts#L47).

Let me know if you face the same issues with the example apps.
