### ISSUE TITLE
Why is Firebase Analytics only included for iOS?

### ISSUE THREAD

**Issue by aml25** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated#164]
I'm digging through trying to understand why Firebase isn't recording any activity for Android but recording all for iOS. And I noticed this in `plugin.xml` for the plugin itself

```
<platform name="ios">
    <pods>
	<pod name="Firebase/Analytics" spec="~> 6.3.0" />
	<pod name="Firebase/Messaging" spec="~> 6.3.0" />
    </pods>
</platform>
```

There's no mention of Firebase Analytics for Android configurations.

**Comment by andrehtissot** [comment]
It used to be required in the past. It seems to not be required anymore.

Thank you for letting me know.

**Comment by andrehtissot** [comment]
Dependency removed in the new 7.3.0 version. Thank you.

**Comment by aml25** [comment]
I was actually bringing it up hoping to see how we could include it for Android as well. It's working great for iOS (from what I can tell), but I need to use another plugin for Android, which is causing some compatibility issues with this one.

**Comment by andrehtissot** [comment]
@aml25
Which plugin you are you using? Maybe the incompatibility can be addressed.

**Comment by mfsbo** [comment]
Some plugins that initialise firebase will conflict as firebase instance is already initialised with given configuration. It would be good if you can either let firebase initialiser to be passed to plugin and it can use an existing initialised firebase instance or if it is not passed then initilise it and export it so user can have both firebase and fcm exported to their app so they can use the same instance with other plugins or on their own.
Only initialize Firebase if no firebase instance is passed and then export that instance back regardless of being initialised by this plugin or passed to you.
Let me know if there is a better solution to this. iOS analytics was giving good output on firebase dashboard and google analytics.

**Comment by andrehtissot** [comment]
Interesting, would you share which plugins are you using that conflict with this one? I can verify how difficult would it be to make them work together.

**Comment by mfsbo** [comment]
Please see #176 as one example.

**Comment by aml25** [comment]
I need to dig deeper into this, but one of the issues I'm seeing is that only iOS reports "notification" events by default. I believe this is happening due to this plugin including Analytics for iOS and not Android. Using cordova-plugin-firebase-analytics does fire Android events to Analytics, but it doesn't capture any notification events.
