### ISSUE TITLE
getInitialPushPayload() throws error at app start

### ISSUE THREAD

**Issue by enricodente** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated#165]
**Describe the bug**
When opening the app on Android from the launcher (not tested on iOS right now), at device ready, getInitialPushPayload() throws error with empty 'error' object. Then the app works ok and also detects foreground notifications.
If the app open trough a push notification, the error is not thrown.

**To Reproduce**
Code used at device ready (as in the example app):
```javascript
// Push notification handlers
FCM.getInitialPushPayload()
	.then((payload) => {
		if(payload.wasTapped){
			// do stuff
		}else{
			//Notification was received in foreground. Maybe the user needs to be notified.	  
			// do different stuff
		}
	})
	.catch((error) => {
		  alert(JSON.stringify(error, null, 2));
	});
```

**Expected behavior**
No errors at app startup.

**Screenshots**
NA

**Environment (please complete the following information):**
Everything @latest (cordova@10.0.0, cordova-android@9.0.0, this plugin @7.3.0, ...)

Also, one last note about a different issue: the app gets installed with "Enable sound" disabled, so all the notifications channels I create will never have a sound. The system I am testing on is a Xiaomi running Android 10.

**Comment by enricodente** [comment]
For the last issue, the "Allow sound" on notifications, looks like it's strictly related to Xiaomi MIUI OS, some references below:

https://stackoverflow.com/questions/53150950/enable-sound-button-in-notification-channel
https://stackoverflow.com/questions/57882970/android-push-notification-sound-is-missing-not-working-background-and-foregro
https://stackoverflow.com/questions/58715149/push-notifications-with-no-sound-on-miui
https://stackoverflow.com/questions/59669451/android-check-if-allow-sound-notification-setting-is-enabled-programmatically

**Comment by enricodente** [comment]
To anyone experiencing such issue, I managed to debug and get the error: it was thrown on check of `if(payload.wasTapped)`. Apparently at app launch getInitialPushPayload gets triggered with a null payload, so all I had to do was to add a check on that:

```
	FCM.getInitialPushPayload()
	.then((payload) => {
		// Check if payload is an object, solves the error thrown at startup
		if(typeof payload === 'object' && payload !== null) {
			if(payload.wasTapped){
                               .... do your stuff ....
                        }
                 }
           }.catch(...)
```
Hope this helps!

Still no luck with notificaiton sound on MIUI devices. There is a way to have it automatically activated, but I think it will need some works at plugin-level.

**Comment by andrehtissot** [comment]
Thank you for reaching out.
The documentation was updated, to avoid confusion in the future (https://github.com/andrehtissot/cordova-plugin-fcm-with-dependecy-updated/blob/master/README.md#fcmgetinitialpushpayload)


FCM.getInitialPushPayload() returns a promise.
The promise must be either resolved or rejected.
Not having any data, is not an error, so resolved it is.
Having no data is more of a `null`, as of the absence of data, than an "empty object".

**Comment by andrehtissot** [comment]
I've created an issue specific to the sound problem. #169

**Comment by stsness** [comment]
Hi! With getInitialPushPayload() I always get null result...
In some states are normal but after kill app, open notification then open app and it must return payload if I am not wrong
I am testing over ionic V3 example of this plugin and iOS device. What is it happening?
