### ISSUE TITLE
Initial push payload doesn't contain the latest notification but a previous only-data message

### ISSUE THREAD

**Issue by lena0204** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated#168]
**Describe the bug / Steps to reproduce**
The app is not running (closed) and I first send a data message (only data payload) and then a normal notification. I then click on the notification to launch the app. The initial payload as given by the plugin matches the one of the (older) data message and not the notification used to launch the app.
The behaviour was observed on Android with both my own app and the Ionic 5 example app and a Java backend for sending the messages. I have not tested iOS so far.

**Expected behavior**
I would expect the initial payload to contain the payload of the latest notification (the normal notification used to launch the app). 

**Possible cause**
By looking in the code I found out that messages with only data payload will trigger the onMessageReceived of the Android service even when the app is closed. So there the initial payload is set. When the notification later is used to launch the app sendPushPayload is called which should set the initial payload, **but only if it isn't set already**, which it is, due to the previous data notification. (The call is in FCMPlugin.java in sendPushPayload.) Is this the expected behaviour? 

**Environment**
 - Developer OS and version: Windows 10
 - Mobile OS and version: Android Emulator 10
 - Cordova CLI version (cordova --version): 9.0.0
 - Ionic version: 5
 - Plugin version: 7.2

**Comment by andrehtissot** [comment]
It was a very easy, dumb, bug. Thank you very much for finding it out.

The fix is available from v7.3.1.
