### ISSUE TITLE
Cannot read property 'onNotification' of undefined

### ISSUE THREAD

**Issue by rajeshwarpatlolla** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated#172]
**Describe the bug**
When i am testing the app in live reload mode in ionic with `ionic cordova run android -l` everything is working fine. I am able to see notifications. **But when i build the apk and install, it's not showing any notifications and getting error `Cannot read property 'onNotification' of undefined`**

**To Reproduce**
Install this plugin, run in live reload mode everything works
Generate apk and install, notifications are not working

**Expected behavior**
Notifications should also work fine with apk

**Screenshots**
<img width="1157" alt="Screenshot 2020-09-14 at 12 24 31 AM" src="https://user-images.githubusercontent.com/9896335/93026049-abcdd080-f620-11ea-922f-278e31d0cc1e.png">

**Environment (please complete the following information):**
 - Developer OS and version: Mac OS latest version
 - Mobile OS and version: Android v10
 - Cordova CLI version (cordova --version): 10.0.0
 - Cocoapods version (pod --version): 1.9.1
 - Xcode version (xcodebuild  -version): 11.6

**Package.json**
`"cordova-plugin-fcm-with-dependecy-updated": "^7.3.1"`

<img width="543" alt="Screenshot 2020-09-14 at 12 25 51 AM" src="https://user-images.githubusercontent.com/9896335/93026060-d91a7e80-f620-11ea-9d7a-3d08581ac4fb.png">

**Comment by andrehtissot** [comment]
How to you import the FCM dependency?
