### ISSUE TITLE
Cocoapods and XCode

### ISSUE THREAD

**Issue by freescout-helpdesk** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated#174]
When creating an iOS app in Firebase, it gives you some instructions for XCode:
- Runs `pod init` and `pod install`
- Add some code to `AppDelegate` class

Is it required to do `pod init` and `pod install` commands?

Where can we find `AppDelegate` class?

**Comment by andrehtissot** [comment]
This plugin describes the pod dependencies on "plugin.xml" file.
Cordova reads from it and triggers the `pod install`.

The SDKs install and "AppDelegate" configuration is automatic.

Just make sure you have a cocoapods version 1.8 or higher and cordova v9 or higher.

**Comment by freescout-helpdesk** [comment]
Thanks
