### ISSUE TITLE
iOS: Provisioning profile "Demo Development" doesn't support the Push Notifications capability

### ISSUE THREAD

**Issue by freescout-helpdesk** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated#175]
When building an iOS app via bitrise we are receiving the following error:

```
Check dependencies
Code Signing Error: Provisioning profile "FreeScout Development" doesn't support the Push Notifications capability.
Code Signing Error: Provisioning profile "FreeScout Development" doesn't include the aps-environment entitlement.
Code Signing Error: Code signing is required for product type 'Application' in SDK 'iOS 14.0'
```

What can be the reason?

**Comment by aliexalter** [comment]
@freescout-helpdesk Please make app identifier on apple developer account. On Identifier creation page select Notifications. After that edit the newly created identifier and setup notification certificates (one for development and one for production). Upload those certificates and provisions on bitrise to build with ios. Follow bitrsie docs for ios.

**Comment by freescout-helpdesk** [comment]
Thanks
