### ISSUE TITLE
BadgeNumber is Missing from api

### ISSUE THREAD

**Issue by golyo** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated#177]
Could you implement set and get badgeNumber ?

**Comment by andrehtissot** [comment]
This plugin looks very interesting https://www.npmjs.com/package/cordova-plugin-badge

Would you try it and let me know if it works for you?

**Comment by yujido123** [comment]
I'm using this plugin and cordova-plugin-badge.
here is my requirement: when iOS app run in background, i need to increase badge number when fcm receive notification. 
But the function 'onNotification' not fired (work fine in foreground). 
should i use other way to implement this requirement? like background mode?
