### ISSUE TITLE
No Push Notifications appear on iPhone. FCMPlugin is undefined

### ISSUE THREAD

**Issue by freescout-helpdesk** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated#180]
Successfully built an iOS app via Bitrise, installed via TestFlight on iphone, but no Push Notifications appear on the iphone device.

`cordova-plugin-fcm-with-dependecy-updated version`: 7.3.1

1) When installing the app on iPhone it does not ask permissions to send Push Notifications. Also in the iphone's "Settings > Notifications" there is no my app listed. Is it ok? If no, how to fix this?

2) When building an app on Bitrise we used regular "App Store" Certificate and corresponding Provisioning Profile, as Apple does not allow to create Provisioning Profile for the a Push Certificate. Is it ok?

Thanks

**Comment by freescout-helpdesk** [comment]
```
document.addEventListener('deviceready', function() {
    alert('FCMPlugin='+typeof(FCMPlugin));
}, false);
```

Shows: `FCMPlugin=undefined`

**Comment by andrehtissot** [comment]
I believe I'm missing some context. Would you fill the bug template?

https://github.com/andrehtissot/cordova-plugin-fcm-with-dependecy-updated/issues/new?assignees=&labels=&template=bug_report.md&title=

**Comment by freescout-helpdesk** [comment]
**Describe the bug**
No Push Notifications appear on iPhone. FCMPlugin is undefined in JS.

**To Reproduce**
Build the iOS app and do the following in JS:
```
document.addEventListener('deviceready', function() {
    alert('FCMPlugin='+typeof(FCMPlugin));
}, false);
```

**Expected behavior**
FCMPlugin should be defined and push notifications, sent from Firebase Console to iOS devices, should appear on the device.

**Environment (please complete the following information):**
 - Developer OS and version: MacOS Mojave 10.14.6
 - Mobile OS and version: iOS 12.4.4 (iPhone)
 - Cordova CLI version (cordova --version): 9.0.0
 - Cocoapods version (pod --version): 1.8.4
 - Xcode version (xcodebuild  -version): Xcode 11.2.1 Build version 11B500

**Package.json**
```
{
  "name": "net.freescout.app",
  "version": "1.0.0",
  "displayName": "FreeScout",
  "cordova": {
    "plugins": {
      "cordova-plugin-inappbrowser": {},
      "cordova-plugin-whitelist": {},
      "cordova-plugin-wkwebview-engine": {},
      "cordova-plugin-fcm-with-dependecy-updated": {}
    },
    "platforms": [
      "android",
      "cordova-ios",
      "ios"
    ]
  },
  "dependencies": {
    "cordova-android": "8.1.0",
    "cordova-ios": "^5.1.1",
    "cordova-plugin-fcm-with-dependecy-updated": "^7.3.1",
    "cordova-plugin-inappbrowser": "^3.2.0",
    "cordova-plugin-whitelist": "^1.3.4",
    "cordova-plugin-wkwebview-engine": "^1.2.1"
  },
  "devDependencies": {}
}
```

**Comment by freescout-helpdesk** [comment]
The following commands work fine:
```
cordova plugin remove cordova-plugin-fcm-with-dependecy-updated
cordova plugin add cordova-plugin-fcm-with-dependecy-updated
cordova requirements ios --verbose
```
`"cordova-plugin-fcm-with-dependecy-updated": "^7.3.1",` is present in package.json, but missing in `config.xml`:
```
    <plugin name="cordova-plugin-inappbrowser" spec="3.2.0" />
    <plugin name="cordova-plugin-wkwebview-engine" spec="1.2.1" />
    <plugin name="cordova-plugin-whitelist" spec="1.3.4" />
    <engine name="cordova-ios" spec="5.1.1" />
    <engine name="android" spec="^8.1.0" />
```

Is this expected behaviour?

**Comment by freescout-helpdesk** [comment]
**cordova-plugin-fcm-with-dependecy-updated** is present in /Users/vagrant/git/platforms/ios/cordova_plugins.js:
```
cordova.define('cordova/plugin_list', function(require, exports, module) {
  module.exports = [
    {
      "id": "cordova-plugin-inappbrowser.inappbrowser",
      "file": "plugins/cordova-plugin-inappbrowser/www/inappbrowser.js",
      "pluginId": "cordova-plugin-inappbrowser",
      "clobbers": [
        "cordova.InAppBrowser.open",
        "window.open"
      ]
    },
    {
      "id": "cordova-plugin-fcm-with-dependecy-updated.FCMPlugin",
      "file": "plugins/cordova-plugin-fcm-with-dependecy-updated/www/FCMPlugin.js",
      "pluginId": "cordova-plugin-fcm-with-dependecy-updated",
      "clobbers": [
        "FCM"
      ]
    },
    {
      "id": "cordova-plugin-wkwebview-engine.ios-wkwebview-exec",
      "file": "plugins/cordova-plugin-wkwebview-engine/src/www/ios/ios-wkwebview-exec.js",
      "pluginId": "cordova-plugin-wkwebview-engine",
      "clobbers": [
        "cordova.exec"
      ]
    },
    {
      "id": "cordova-plugin-wkwebview-engine.ios-wkwebview",
      "file": "plugins/cordova-plugin-wkwebview-engine/src/www/ios/ios-wkwebview.js",
      "pluginId": "cordova-plugin-wkwebview-engine",
      "clobbers": [
        "window.WkWebView"
      ]
    }
  ];
  module.exports.metadata = {
    "cordova-plugin-inappbrowser": "3.2.0",
    "cordova-plugin-whitelist": "1.3.4",
    "cordova-plugin-fcm-with-dependecy-updated": "7.3.1",
    "cordova-plugin-wkwebview-engine": "1.2.1"
  };
});
```

**Comment by freescout-helpdesk** [comment]
Before `FCMPlugin` was used. Should we use `FCM` now? What is the difference?

Should we use `FCMPlugin.requestPushPermissionIOS()` function or `FCM.requestPushPermission()`?

**Comment by freescout-helpdesk** [comment]
We are using `FCMPlugin` instead of `FCM` - this is the reason of the problem.

Can you tell in which version `FCMPlugin` has been renamed into `FCM`?

**Comment by andrehtissot** [comment]
> We are using `FCMPlugin` instead of `FCM` - this is the reason of the problem.
> 
> Can you tell in which version `FCMPlugin` has been renamed into `FCM`?

Version 7.
