### ISSUE TITLE
Force FCM.requestPushPermission() to display the modal dialog again

### ISSUE THREAD

**Issue by freescout-helpdesk** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated#181]
If user clicks "No" in the `FCM.requestPushPermission()` modal dialog, when `FCM.requestPushPermission()` is executed next time, modal dialog is not displayed. Is it possible to force `FCM.requestPushPermission()` to display modal dialog again?

**Comment by andrehtissot** [comment]
No. That's by Apple's design.

Once the user has blocked the Push notification, there is no way to re-request. Unless the user re-installs the app.

Therefore the interest to first capture the interest of the user, before requesting Push permission.
