### ISSUE TITLE
Execution failed for task ':app:compileReleaseJavaWithJavac'.

### ISSUE THREAD

**Issue by ahmedfarag2010** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated#182]
I tried the steps and got this error when try "**ionic cordova build android --release**"
And here is the full error

![1](https://user-images.githubusercontent.com/17453891/94630508-476c6b80-02c6-11eb-8afb-b5571daf1959.png)

And here is app.module and home.component

![2](https://user-images.githubusercontent.com/17453891/94630526-55ba8780-02c6-11eb-9be2-f71813d760f8.png)

![3](https://user-images.githubusercontent.com/17453891/94630528-58b57800-02c6-11eb-92e6-1c319e765de2.png)

**Comment by andrehtissot** [comment]
As you can see in the image, the error is thrown from the ionic java code and not from this plugin.
![Screenshot 2020-10-12 at 22 42 12](https://user-images.githubusercontent.com/1174345/95788672-41ba5100-0cdc-11eb-8924-cc3b4cabde35.png)
