### ISSUE TITLE
groovy.lang.MissingPropertyException: No such property: ANDROID_GRADLE_TOOLS_VERSION for class: java.lang.Object

### ISSUE THREAD

**Issue by Luca8991** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated#197]
**Describe the bug**
Keep getting this error when executing the Gradle Sync in Android Studio

**To Reproduce**
1. `npm i cordova-plugin-fcm-with-dependecy-updated`
2. `npm install @ionic-native/fcm`
3. followed [this guide](https://www.positronx.io/ionic-firebase-fcm-push-notification-tutorial-with-example/) to implement FCM in my Ionic app
4. `ionic build`
5. `ionic cap copy android`
6. `ionic cap open android`
7. See error when Android Studio tries to sync Gradle

**Expected behavior**
I expected to compile correctly the app and test it on my smartphone

**Screenshots**
![Screenshot from 2020-11-21 09 40 17-oscurata](https://user-images.githubusercontent.com/12596698/99871939-627c9d00-2bde-11eb-8e2f-76a8e7d80008.png)

**Environment (please complete the following information):**
 - Developer OS and version: elementary OS 5.1.7 Hera (Built on Ubuntu 18.04.4 LTS)
 - Mobile OS and version: Android 8.0.0
 - Cordova CLI version (cordova --version): 10.0.0

**Package.json**
```
{
  "name": "myproject",
  "version": "0.0.1",
  "author": "Ionic Framework",
  "homepage": "https://ionicframework.com/",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "start:ionic": "npx ionic serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "postinstall": "npx jetify"
  },
  "private": true,
  "dependencies": {
    "@agm/core": "^3.0.0-beta.0",
    "@angular/common": "~10.0.0",
    "@angular/core": "~10.0.0",
    "@angular/fire": "^6.0.4",
    "@angular/forms": "~10.0.0",
    "@angular/platform-browser": "~10.0.0",
    "@angular/platform-browser-dynamic": "~10.0.0",
    "@angular/router": "~10.0.0",
    "@capacitor/android": "^2.4.2",
    "@capacitor/core": "2.4.2",
    "@ionic-native/core": "^5.29.0",
    "@ionic-native/facebook": "^5.29.0",
    "@ionic-native/fcm": "^5.30.0",
    "@ionic-native/firebase-authentication": "^5.29.0",
    "@ionic-native/splash-screen": "^5.0.0",
    "@ionic-native/status-bar": "^5.0.0",
    "@ionic/angular": "^5.4.1",
    "cordova-plugin-facebook4": "^6.4.0",
    "cordova-plugin-fcm-with-dependecy-updated": "^7.6.0",
    "cordova-plugin-firebase-authentication": "^3.6.0",
    "cordova-support-android-plugin": "^1.0.2",
    "firebase": "^8.0.0",
    "ngx-image-cropper": "^3.2.1",
    "rxjs": "~6.5.5",
    "tslib": "^2.0.0",
    "zone.js": "~0.10.3"
  },
  "devDependencies": {
    "@angular-devkit/architect": ">= 0.900 < 0.1100",
    "@angular-devkit/build-angular": "^0.1002.0",
    "@angular/cli": "~10.0.5",
    "@angular/compiler": "~10.0.0",
    "@angular/compiler-cli": "~10.0.0",
    "@angular/language-service": "~10.0.0",
    "@capacitor/cli": "2.4.2",
    "@ionic/angular-toolkit": "^2.3.0",
    "@ionic/lab": "3.2.9",
    "@types/googlemaps": "^3.39.13",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^12.11.1",
    "codelyzer": "^6.0.0",
    "firebase-tools": "^8.0.0",
    "fuzzy": "^0.1.3",
    "inquirer": "^6.2.2",
    "inquirer-autocomplete-prompt": "^1.0.1",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~5.0.0",
    "jetifier": "^1.6.6",
    "karma": "~5.0.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "~3.3.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "open": "^7.0.3",
    "protractor": "~7.0.0",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~3.9.5"
  },
  "description": "An Ionic project"
}

```

**Comment by leorsida** [comment]
did you try to pass lib versions on installation script?

cordova plugin add cordova-plugin-fcm-with-dependecy-updated \
  --variable ANDROID_DEFAULT_NOTIFICATION_ICON="@mipmap/ic_launcher" \
  --variable ANDROID_FIREBASE_BOM_VERSION="26.0.0" \
  --variable ANDROID_GOOGLE_SERVICES_VERSION="4.3.4" \
  --variable ANDROID_GRADLE_TOOLS_VERSION="4.1.0" \
  --variable IOS_FIREBASE_MESSAGING_VERSION="~> 7.0.0"

**Comment by Luca8991** [comment]
I can't because I'm using Capacitor and I have to add the plugin with this command:
`npm install cordova-plugin-fcm-with-dependecy-updated`
(from [here](https://ionicframework.com/docs/native/fcm))

**Comment by andrehtissot** [comment]
Currently, this plugin is not compatible with Capacitor
