### ISSUE TITLE
I'm experiencing the same issue after accidentally updating cocapods.

### ISSUE THREAD

**Issue by andrehtissot** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated#199]
I'm experiencing the same issue after accidentally updating cocapods.

I've tried to downgrade using:
> sudo gem uninstall cocoapods
> sudo gem install cocoapods -v 1.9.0

as suggested:

```
sudo gem list cocoapods

*** LOCAL GEMS ***

cocoapods (1.9.0)
cocoapods-clean (0.0.1)
cocoapods-core (1.9.3, 1.9.0)
cocoapods-deintegrate (1.0.4)
cocoapods-downloader (1.3.0)
cocoapods-plugins (1.0.0)
cocoapods-search (1.0.0)
cocoapods-stats (1.1.0)
cocoapods-trunk (1.5.0)
cocoapods-try (1.2.0)
```

However when adding the platform via:

> cordova platform ios

I get:

```
Running command: pod install --verbose
Failed to install 'cordova-plugin-fcm-with-dependecy-updated': Error: pod: Command failed with exit code 1
    at ChildProcess.whenDone (/Users/user/Documents/Projects/Project/node_modules/cordova-common/src/superspawn.js:135:23)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1051:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)

```

_Originally posted by @BRadHoc in https://github.com/andrehtissot/cordova-plugin-fcm-with-dependecy-updated/issues/82#issuecomment-729792023_

**Comment by andrehtissot** [comment]
Would you try to uninstall `cordova-plugin-fcm-with-dependecy-updated` and reinstall `cordova-plugin-fcm-with-dependecy-updated`?

**Comment by ScottWaring** [comment]
Im running into the same issue.
Uninstalling and reinstalling does not resolve the error for me.
Has anyone found a solution?

**Comment by BRadHoc** [comment]
Sorry guys, been a tad distracted with work. I fixed it by downgrading to an earlier version of my project before I updated, so I'm assuming the update changed something the in gradle settings or something deep within the project.

Works as expected after the downgrade though

**Comment by andrehtissot** [comment]
Thank you for the update @BRadHoc. Let me know if you find out why that happened.
