### ISSUE TITLE
FIRMessaging received data-message, but FIRMessagingDelegate's-messaging:didReceiveMessage: not implemented

### ISSUE THREAD

**Issue by ostigley** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated#20]
Hi
I'm using v4.4.0, and everything is fine on Android, but I can see this in the ios logs: 

`FIRMessaging received data-message, but FIRMessagingDelegate's-messaging:didReceiveMessage: not implemented`

Any thoughts?

**Comment by andrehtissot** [comment]
I'll check. Thank you for creating the issue.

**Comment by andrehtissot** [comment]
This would be called only for IOS and the app is in the foreground. As a way to bypass the Apple Notification and send a data message to the app.

As it behaves as no other case, it'll be created a different method to listen to these.

**Comment by andrehtissot** [comment]
Would you kindly help me tested?

I've created a branch called "on-firebase-data-notification-ios-added" (https://github.com/andrehtissot/cordova-plugin-fcm-with-dependecy-updated/compare/v4.4.1...andrehtissot:on-firebase-data-notification-ios-added) which has the listener implemented as `onFirebaseDataNotificationIOS`.

**Comment by andrehtissot** [comment]
It's been a while, and the implementation seems safe enough to have it published as 5.6.0. So, when you are available, please check it out.
