### ISSUE TITLE
getToken() method returns null on iOS.

### ISSUE THREAD

**Issue by mozhn** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated#200]
I made all the settings. However, the getToken() method only returns the correct value when the application is opened for the first time. Returns null on subsequent application openings. When I checked to see if the token is valid or not, I saw it was valid. I have no idea why it is returning null. Thanks for the slightest help.

**Comment by AlexDziadyk** [comment]
+

**Comment by rsanahi** [comment]
Same issue

**Comment by shashikaxp** [comment]
Same issue, does anyone solve this ?

**Comment by RidClick** [comment]
please don't forget update your cocoapods before add platform ios

`pod repo update` 

on your app folder and then add platform

**Comment by andrehtissot** [comment]
The next update will extend the `get` behavior, to also wait until the value is not null.
