### ISSUE TITLE
onNotification not working in background 

### ISSUE THREAD

**Issue by speamy** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated#201]
**Describe the bug**
I want to increment the badge counter by one when a new notification is received. To realize this I have added cordova-plugin-badge. This should be executed when the app is closed. Unfortunately onNotification on IOS does not work for me if the app is in the background or closed. I think it is a bug that onNotification is not called when the app is in the background. Everything else works perfectly and the notifications will be delivered even when the app is closed.

```js
    document.addEventListener("deviceready", () => {
      FCM.onNotification((obj) => {
        cordova.plugins.notification.badge.increase(1)
      })
    })
```

**Package.json**
```json
{
  "name": "com.XXXXX",
  "displayName": "XXXXX",
  "version": "1.0.0",
  "description": "A sample Apache Cordova application that responds to the deviceready event.",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [
    "ecosystem:cordova"
  ],
  "author": "Apache Cordova Team",
  "license": "Apache-2.0",
  "devDependencies": {
    "cordova-ios": "^6.1.1",
    "cordova-plugin-badge": "git+https://github.com/katzer/cordova-plugin-badge.git",
    "cordova-plugin-fcm-with-dependecy-updated": "^7.6.0",
    "cordova-plugin-inappbrowser": "^4.0.0",
    "cordova-plugin-ionic-webview": "^5.0.0",
    "cordova-plugin-sign-in-with-apple": "^0.1.2",
    "cordova-plugin-statusbar": "git+https://github.com/apache/cordova-plugin-statusbar.git",
    "cordova-plugin-whitelist": "^1.3.4",
    "cordova-plugin-x-socialsharing": "^6.0.2",
    "es6-promise-plugin": "^4.2.2"
  },
  "cordova": {
    "plugins": {
      "cordova-plugin-whitelist": {},
      "cordova-plugin-ionic-webview": {},
      "cordova-plugin-sign-in-with-apple": {},
      "cordova-plugin-statusbar": {},
      "cordova-plugin-inappbrowser": {},
      "cordova-plugin-x-socialsharing": {
        "PHOTO_LIBRARY_ADD_USAGE_DESCRIPTION": "This app requires photo library access to function properly.",
        "PHOTO_LIBRARY_USAGE_DESCRIPTION": "This app requires photo library access to function properly."
      },
      "cordova-plugin-device": {},
      "cordova-plugin-fcm-with-dependecy-updated": {},
      "cordova-plugin-badge": {}
    },
    "platforms": [
      "ios"
    ]
  },
  "dependencies": {
    "cordova-plugin-device": "2.0.3"
  }
}%
```

**Comment by icemycoffee** [comment]
I second this one using version 6.4.3.
I can only confirm this when the app is in killed state, while from the background state no problems arise.

It also magically sometimes worked from background state. I looked into this problem quite a bit but could not figure out the cause. It seems to randomly work in some builds and in other builds it doesnt.

**Comment by codi0** [comment]
I'm seeing similar issues on v7.7.0, using cordova-android 9.0 build.

**FCM.onNotification is fired when:**
- App is in the foreground and a notification is received (wasTapped = false)
- App is brought into focus from the background by tapping a notification (wasTapped = true)

**FCM.onNotification does not fire when:**
- App is running in the background and notification received
- App is opened from killed state by tapping a notification

I'd previously been using 6.4.3, where onNotification did fire correctly in all scenarios, with the exception of from the killed state when CSP is enabled (due to use of the deprecated API using eval, which v7 has replaced).

**Comment by andrehtissot** [comment]
The `onNotification` behavior change was on purpose, as the event subscription has to happen before the event is triggered. 

In older versions, the subscription method was also re-triggering the event, which is would bring issues in the case of more than one subscription.
