### ISSUE TITLE
Push notifications not working on iOS after recent update

### ISSUE THREAD

**Issue by venkydeshmukh** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated#210]
**Describe the bug**
I was using cordova-plugin-fcm-with-dependecy-updated 4.6.0 version. It was working perfectly. But I started getting build issues recently due to update in pod. I followed issue [188](https://github.com/andrehtissot/cordova-plugin-fcm-with-dependecy-updated/issues/188).
I updated the plugin version to git+https://github.com/QuentinFarizon/cordova-plugin-fcm-with-dependecy-updated.git#fix_firebase_pod_version
The build issue is gone. But Ios app has stopped sending the push notifications. Android still works perfectly but there seems to be issue with IoS

**To Reproduce**
1. Use 4.6.0 version
2. update to git+https://github.com/QuentinFarizon/cordova-plugin-fcm-with-dependecy-updated.git#fix_firebase_pod_version
3. build the ipa using ionic appflow
4. No error is seen but app does not send push notifications

**Expected behavior**
As there is no change in the code, push notifications should be sent on IoS also

Developer OS and version: macOS 10.14.6 (Mojave)
Mobile OS and version: iOS 14.0.1
Cordova CLI version (cordova --version): 9.0.0
Cordova iOS version : 5.1.1
Cocoapods version (pod --version): -
Xcode version (xcodebuild -version): Xcode 11.1.x

**Package.json**
Please add your package.json, as to provide the dependencies version.

```
"cordova-android": "^8.1.0",
    "cordova-ios": "^5.1.1",
 "cordova-plugin-fcm-with-dependecy-updated": "git+https://github.com/QuentinFarizon/cordova-plugin-fcm-with-dependecy-updated.git#fix_firebase_pod_version",
   "@ionic-native/fcm": "^5.23.0",
```

```
"cordova": {
    "plugins": {
      "cordova-plugin-fcm-with-dependecy-updated": {
        "ANDROID_FCM_VERSION": "21.0.0",
        "ANDROID_FIREBASE_BOM_VERSION":"26.0.0",
        "ANDROID_GRADLE_TOOLS_VERSION": "4.1.0",
        "ANDROID_GOOGLE_SERVICES_VERSION": "4.3.4",
        "IOS_FIREBASE_MESSAGING_VERSION":"~> 7.0.0",
        "ANDROID_DEFAULT_NOTIFICATION_ICON": "@mipmap/ic_launcher"
      },
```

**Comment by camengadisaputra-dev** [comment]
Same thing happen, the token get from iOS, always fail to send
`{
  results: [ { error: [FirebaseMessagingError] } ],
  canonicalRegistrationTokenCount: 0,
  failureCount: 1,
  successCount: 0,
  multicastId: 9104948795448371000
}`

**Comment by erickmtz-developer** [comment]
I have the same problem, does anyone know how to solve it?

**Comment by camengadisaputra-dev** [comment]
Probably it has something todo with ios APN certificate

**Comment by mvaljento** [comment]
Same here. Notifications working with Android, but not with iOS. Using plugin version 7.7.0.

**Comment by andrehtissot** [comment]
@venkydeshmukh
I've noticed the fork you use is outdated. Is highly recommended to upgrade to v7.
