### ISSUE TITLE
Notification's not passing data (when killed)

### ISSUE THREAD

**Issue by BRadHoc** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated#211]
**Describe the bug**

> When the app is killed and a notification with data is sent and tapped, the notification listener event is created but does not fire.

**To Reproduce**
1. Setup alerts on creation of the listener, and inside the success function
2. Build and make sure the app is killed (not running).
3. Send a notification with data
4. Tap the notification
5. See the listener is created, but does not fire.
6. Background the app
7. Send the notification again
8. See the listener is created, and fires as expected.

**Expected behavior**

> The listener should fire causing the second alert to be displayed to the user.

**Environment (please complete the following information):**
 - Developer OS and version: MacOS Big Sur
 - Mobile OS and version: iOS 14.1
 - Cordova CLI version (cordova --version): 9.00
 - Cocoapods version (pod --version): 1.9.0
 - Xcode version (xcodebuild  -version): 12.2b4

**Comment by Alexuisis** [comment]
same issue with android 6.0, ionic 5 - neither onNotification triggering nor getInitialPushPayload returns any payload on status bar tap & app open after getting the notification.

**Comment by andrehtissot** [comment]
@BRadHoc
For the step `5. See the listener is created, but does not fire.`:
- Yes, if the event is received before the onNotification starts listening, it won't be triggered. For these notifications, you can use [FCM.getInitialPushPayload()](https://github.com/andrehtissot/cordova-plugin-fcm-with-dependecy-updated#fcmgetinitialpushpayload).

For the steps `7. Send the notification again` and `8. See the listener is created, and fires as expected.`:
- If the app is on the background, the code that listens to notification events has already already ran, hence it's listening the notification event that is received next.

@Alexuisis 
Neither `onNotification` or `getInitialPushPayload` will present any payload, they will only give the payload received.

A first moment, this behavior is expected. If there was any misunderstand, please open another ticket with more details. Thank you.
