### ISSUE TITLE
Cannot invoke method lastIndexOf() on null object

### ISSUE THREAD

**Issue by CaturViriyananda** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated#213]
i had this issue on cordova build:

> Configure project :app
+-----------------------------------------------------------------
| cordova-android-support-gradle-release: 27.+
+-----------------------------------------------------------------

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Script '/home/vir4un/cmiew/tanyaCwk/platforms/android/cordova-plugin-fcm-with-dependecy-updated/tanyacwk-FCMPlugin.gradle' line: 22

* What went wrong:
A problem occurred evaluating script.
> Cannot invoke method lastIndexOf() on null object

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':app'.
> compileSdkVersion is not specified. Please add it to build.gradle

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 27s
Command failed with exit code 1: /home/vir4un/cmiew/tanyaCwk/platforms/android/gradlew cdvBuildDebug -b /home/vir4un/cmiew/tanyaCwk/platforms/android/build.gradle

**Comment by CaturViriyananda** [comment]
i fix the issue by specifying android gradle version and by not using default preferences.

cordova plugin add cordova-plugin-fcm-with-dependecy-updated \
  --variable ANDROID_DEFAULT_NOTIFICATION_ICON="@mipmap/ic_launcher" \
  --variable ANDROID_FIREBASE_BOM_VERSION="26.0.0" \
  --variable ANDROID_GOOGLE_SERVICES_VERSION="4.3.4" \
  --variable ANDROID_GRADLE_TOOLS_VERSION="4.1.0" \
  --variable IOS_FIREBASE_MESSAGING_VERSION="~> 7.0.0"

**Comment by dkaushikl** [comment]
@CaturViriyananda I tried this, but no luck
