### ISSUE TITLE
Task :app:compileDebugJavaWithJavac FAILED only when using the plugin

### ISSUE THREAD

**Issue by copperstyle** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated#215]
Thought it was a problem with my app so i decided to create a new one and test it there but it didn't work.
I tried to add GradlePluginKotlinEnabled and AndroidXEnabled and run `ionic cordova prepare android` after removing android platform but it didn't fix my issue.

Configure project :app
FCMPlugin: Support for Gradle v4 or lower is deprecated. Please upgrade to a newer version.
Task :app:compileDebugJavaWithJavac
C:\Users\user\Desktop\app\platforms\android\app\src\main\java\com\ionicframework\cordova\webview\IonicWebViewEngine.java:11: error: package android.support.annotation does not exist
import android.support.annotation.RequiresApi;
^
C:\Users\user\Desktop\app\platforms\android\app\src\main\java\com\ionicframework\cordova\webview\IonicWebViewEngine.java:137: error: cannot find symbol
@RequiresApi(Build.VERSION_CODES.LOLLIPOP)
^
symbol: class RequiresApi
location: class IonicWebViewEngine.ServerClient
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
2 errors

Task :app:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
Compilation failed; see the compiler error output for details.

Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.5/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 25s
Command failed with exit code 1: C:\Users\user\Desktop\app\platforms\android\gradlew cdvBuildDebug -b C:\Users\user\Desktop\app\platforms\android\build.gradle
[ERROR] An error occurred while running subprocess cordova.

**Comment by CaturViriyananda** [comment]
i encounter this problem on my cordova app when i do : cordova plugin add , before cordova platform add.

i fixed it by adding the platform first and then the plugin.
cordova platform add android. and then cordova plugin add cordova-plugin-fcm-with-dependecy-updated \
  --variable ANDROID_DEFAULT_NOTIFICATION_ICON="@mipmap/ic_launcher" \
  --variable ANDROID_FIREBASE_BOM_VERSION="26.0.0" \
  --variable ANDROID_GOOGLE_SERVICES_VERSION="4.3.4" \
  --variable ANDROID_GRADLE_TOOLS_VERSION="4.1.0" \
  --variable IOS_FIREBASE_MESSAGING_VERSION="~> 7.0.0"

avoid the default variable value.
