### ISSUE TITLE
Not working with vue-cli-plugin-cordova

### ISSUE THREAD

**Issue by jringbox** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated#22]
Hello.

I'm having issues when using this plugin with vue-cli-plugin-cordova.  Essentially, I have a VueJS project with vue-cli-plugin-cordova added.

The firebase notifications are not being received through the android emulator.

The firebase notifications do work when the project is a cordova project and not a VueJS with a cordova plugin.  I double-checked all my configuations between the 2 and they appear to be the same yet one works and the other doesn't.

Just to be clear.  Since I have a VueJS with a cordova plugin, there's a src-cordova directory.  The cordova-plugin-fcm-with-dependecy-updated plugin was added from the src-cordova directory.  I did move the changes in the src-cordova/www/js/index.js to public/js/index.js.  I even tried adding the script `src="FCMPlugin.js"` to the public/index.html.  None of these changes generated notifications when emulating android.

I did add alerts to index.js which did appear (part of my troubleshooting).  I added "typeof (FCMPlugin) != 'undefined'" which evaluated true.  So the plugin is loading despite that FCMPlugin.onNotification never receives a notification.

In all of this effort, I don't know how to determine if that's the case or if there's some other setup/configuration issue that is broken.

I appreciate any help you can offer to resolve this issue.

**Comment by andrehtissot** [comment]
Would you consider creating a github repository of which I can clone and test it myself?

**Comment by jringbox** [comment]
I have it all figured out.

I uninstalled cordova-plugin-fcm-with-dependecy-updated and completely remove platforms/android.  Then I installed cordova-plugin-fcm which also installed cordova-plugin-fcm-with-dependecy-updated.  I did this just to be clean about everything and let cordova-plugin-fcm do any updates with cordova-plugin-fcm-with-dependecy-updated that might of been done if it was done alone.

I followed what was at this [link](https://stackoverflow.com/questions/56328069/the-chunk-argument-must-be-one-of-type-string-or-buffer-received-type-object).  This link mentions some bug issues with cordova-plugin-fcm, so I did the following:
 
1.  updated android/project.properties and android/app/build.gradle with version firebase-core:16.0.3 and firebase-messaging:17.6.0.  android/build.gradle didn't have any versions for this even though the article indicated it should.

2.  fixed the plugin script plugins/cordova-plugin-fcm/scripts/fcm_config_files_process.js as follows.  Result of bug in the application.
 
```
// change
var strings = fs.readFileSync("platforms/android/res/values/strings.xml").toString();
// to
var strings = fs.readFileSync("platforms/android/app/src/main/res/values/strings.xml").toString();

// AND

//change
fs.writeFileSync("platforms/android/res/values/strings.xml", strings);
//to
fs.writeFileSync("platforms/android/app/src/main/res/values/strings.xml", strings);
```
 
After that, copied google-services.json file to platforms/android/app/google-services.json.
 
Once this was all done, I rebuilt the app and everything worked.

I don't know why but cordova-plugin-fcm-with-dependecy-updated could not work by itself.  It needed cordova-plugin-fcm along with all the changes I just mentioned.

**Comment by andrehtissot** [comment]
I believe you didn't need the `cordova-plugin-fcm`, but, the fix you applied to `fcm_config_files_process.js` presented a support issue that persisted until 4.4.1.

I've refactored the `cordova-plugin-fcm-with-dependecy-updated`'s `fcm_config_files_process.js` with the support for the new path.

Would you try to:
- Uninstall cordova-plugin-fcm;
- Install cordova-plugin-fcm-with-dependecy-updated version 4.4.3;

Also, there should be no reason to downgrade the firebase-messaging version, which the post mentioned.

**Comment by jringbox** [comment]
Today is off day for me.  That will be first thing I will do tomorrow morning.  I definitely don't like the fact that I downgraded.  I definitely want to keep up with the latest firebase-messaging version.  I'll let you know what happens when I make the changes you mentioned.

**Comment by jringbox** [comment]
What what happened?  I got this after I made the changes and tried to build.  I see the latest is 4.5.0 which is what I'm using.

```
Execution failed for task ':app:mergeDebugResources'.
> [string/google_app_id] C:\clinicallink\temp\notifications\myApp\src-cordova\platforms\android\app\src\main\res\values\strings.xml       [string/google_app_id] C:\clinicallink\temp\notifications\myApp\src-cordova\platforms\android\app\build\generated\res\google-services\debug\values\values.xml: Error: Duplicate resources
> Task :app:mergeDebugResources FAILED
```

**Comment by andrehtissot** [comment]
This is a new bug, already reported.

**Comment by andrehtissot** [comment]
Due to a bug introduced in v4.4.3, the file `platforms/android/app/src/main/res/values/strings.xml` two tags are included on install, tags which, on build, are also included by cordova-android@8.x.x. Hence failing the build process.

To apply the fix, install the new version and remove these two tags from your values/strings.xml:
* `<string name="google_app_id">...</string>`
* `<string name="google_api_key">...</string>`

**Comment by andrehtissot** [comment]
If you still get issues, please reopen this ticket :)

But the duplication error should be resolved.

**Comment by jringbox** [comment]
I removed all the changes I had and just put your latest 4.5.1 version changes.  The messaging works without issue with fcm 19.  Thank goodness.  I really didn't like using an old version of firebase.  Thanks!

**Comment by andrehtissot** [comment]
Thank you for the patience :)
