### ISSUE TITLE
Not getting notification's title and body with `getInitialPushPayload()`

### ISSUE THREAD

**Issue by chiragsrvstv** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated#221]
Hello @andrehtissot! Thanks a lot for creating and maintaining this plugin. <br />
The issue that I am facing is, when my android application is killed and a notification arrives, after tapping it, the `fcm.getInitialPushPayload()`method  gives only the `data` payload that was sent along with the notification. For some reason it doesn't give me the notification's title and body. Here is the notification structure that I'm sending from my node backend using FCM SDK:
```JS
const notification = {
    tokens,
    notification: {
      title: category,
      body: message,
    },
    data: {
      device: 'my-device',
      type: 'my-type',
      color: 'primary',
      date: dayjs(date).fromNow(),
    },
    android: {
      notification: {
        click_action: 'FCM_PLUGIN_ACTIVITY',
      },
    },
  };
  ```

**Comment by icemycoffee** [comment]
Seems to be expected behavior.
I worked around it by adding "notification_title" and "notification_body" to my data payload and falling back to these values if "title" and/or "body" are not available directly from the notification payload

**Comment by chiragsrvstv** [comment]
Thanks @icemycoffee, that's what I'm doing too. 
Btw I don't quite get how is this an expected behaviour?

**Comment by andrehtissot** [comment]
Yes, @chiragsrvstv. Unfortunately this is a native Android limitation. the "notification" part of the payload is not given to the application, and, therefore, not given by getInitialPushPayload().
