### ISSUE TITLE
Xcode 12.4

### ISSUE THREAD

**Issue by abhaya123** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated#224]
My app was building fine for ios however after xcode 12.4 or big sur it throws an error for FCMPlugin while building.

cordova-plugin-fcm-with-dependecy-updated/FCMPlugin.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
xcodebuild: Command failed with exit code 65

**Comment by RidClick** [comment]
try 
`pod repo update `
in the app folder before add platform ios
then 
`ionic cordova prepare ios`
and finally build

**Comment by andrehtissot** [comment]
Build tested on XCode 12.4 without issues.
