### ISSUE TITLE
Build Failed - Cannot invoke method lastIndexOf() on null object & compileSdkVersion is not specified. Please add it to build.gradle

### ISSUE THREAD

**Issue by iamkbkarthikeyan** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated#227]
**Describe the bug**

**To Reproduce**

**Expected behavior**
After completing fcm integration, i can't build the app. I got 2 exceptions,

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Script 'F:\Ionic Cordova\goMart - Full App\platforms\android\cordova-plugin-fcm-with-dependecy-updated\gomartapp-FCMPlugin.gradle' line: 22

* What went wrong:
A problem occurred evaluating script.
> Cannot invoke method lastIndexOf() on null object

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to 
get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':app'.
> compileSdkVersion is not specified. Please add it to build.gradle

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to 
get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 8s
Command failed with exit code 1: F:\Ionic Cordova\goMart - Full App\platforms\android\gradlew cdvBuildDebug -b F:\Ionic Cordova\goMart - Full App\platforms\android\build.gradle
[ERROR] An error occurred while running subprocess cordova.

        cordova.cmd build android --debug exited with exit code 1.

        Re-running this command with the --verbose flag may provide more information.

**Environment:**
 - Developer OS and version: Windows 10 Pro
 - Mobile OS and version: Android 9
 - Cordova CLI version (cordova --version): 10.0.0

**Package.json**

{
  "name": "XXXX",
  "version": "1.1.0",
  "author": "Shivam ITS",
  "homepage": "https://shivamits.com/",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "~10.0.0",
    "@angular/core": "~10.0.0",
    "@angular/forms": "~10.0.0",
    "@angular/platform-browser": "~10.0.0",
    "@angular/platform-browser-dynamic": "~10.0.0",
    "@angular/router": "~10.0.0",
    "@ionic-native/camera": "^5.30.0",
    "@ionic-native/core": "^5.0.0",
    "@ionic-native/fcm": "^5.31.1",
    "@ionic-native/file": "^5.30.0",
    "@ionic-native/file-transfer": "^5.30.0",
    "@ionic-native/google-plus": "^5.30.0",
    "@ionic-native/splash-screen": "^5.0.0",
    "@ionic-native/status-bar": "^5.0.0",
    "@ionic/angular": "^5.0.0",
    "@ngx-translate/core": "^13.0.0",
    "@ngx-translate/http-loader": "^6.0.0",
    "animate.css": "^4.1.1",
    "ng-lazyload-image": "^9.1.0",
    "rxjs": "~6.5.5",
    "tslib": "^2.0.0",
    "zone.js": "~0.10.3"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1000.0",
    "@angular/cli": "~10.0.5",
    "@angular/compiler": "~10.0.0",
    "@angular/compiler-cli": "~10.0.0",
    "@angular/language-service": "~10.0.0",
    "@ionic/angular-toolkit": "^2.3.0",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^12.11.1",
    "codelyzer": "^6.0.0",
    "com.razorpay.cordova": "^1.4.12",
    "cordova-browser": "^6.0.0",
    "cordova-plugin-camera": "^5.0.1",
    "cordova-plugin-device": "^2.0.2",
    "cordova-plugin-fcm-with-dependecy-updated": "^7.8.0",
    "cordova-plugin-file": "^6.0.2",
    "cordova-plugin-file-transfer": "^1.7.1",
    "cordova-plugin-googleplus": "^8.5.1",
    "cordova-plugin-ionic-keyboard": "^2.2.0",
    "cordova-plugin-ionic-webview": "^4.2.1",
    "cordova-plugin-splashscreen": "^5.0.2",
    "cordova-plugin-statusbar": "^2.4.2",
    "cordova-plugin-whitelist": "^1.3.3",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~5.0.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "~3.3.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "protractor": "~7.0.0",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~3.9.5",
    "web": "0.0.2"
  },
  "description": "An eCommerce App",
  "cordova": {
    "plugins": {
      "cordova-plugin-whitelist": {},
      "cordova-plugin-statusbar": {},
      "cordova-plugin-device": {},
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-ionic-webview": {
        "ANDROID_SUPPORT_ANNOTATIONS_VERSION": "27.+"
      },
      "cordova-plugin-ionic-keyboard": {},
      "cordova-plugin-googleplus": {
        "REVERSED_CLIENT_ID": "XXXX",
        "WEB_APPLICATION_CLIENT_ID": "XXXX",
        "PLAY_SERVICES_VERSION": "15.0.1"
      },
      "cordova-plugin-camera": {
        "ANDROID_SUPPORT_V4_VERSION": "27.+"
      },
      "cordova-plugin-file": {},
      "cordova-plugin-file-transfer": {},
      "com.razorpay.cordova": {},
      "cordova-plugin-fcm-with-dependecy-updated": {}
    },
    "platforms": []
  }
}

**Comment by iamkbkarthikeyan** [comment]
I tried to add variables,
        
        "ANDROID_DEFAULT_NOTIFICATION_ICON": "@mipmap/ic_launcher",
        "ANDROID_FIREBASE_BOM_VERSION": "26.0.0",
        "ANDROID_GOOGLE_SERVICES_VERSION": "4.3.4",
        "ANDROID_GRADLE_TOOLS_VERSION": "4.1.0",
        "IOS_FIREBASE_MESSAGING_VERSION": "~> 7.0.0"

But, Now getting this following issue.

> Configure project :app
FCMPlugin: Support for Gradle v4 or lower is deprecated. Please upgrade to a newer version.
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not find com.google.firebase:firebase-messaging:null.
     Required by:
         project :app

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to 
get full insights.

**Comment by mvaljento** [comment]
I think I just ran to the same issue after upgrading to version 7.8.0:

```
> Configure project :app
FCMPlugin: Support for Gradle v4 or lower is deprecated. Please upgrade to a newer version.
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not find com.google.firebase:firebase-messaging:null.
     Required by:
         project :app

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
Command failed with exit code 1: /Users/mikkoville/project/onskebo/platforms/android/gradlew cdvBuildDebug -b /Users/mikkoville/project/onskebo/platforms/android/build.gradle
Error: Command failed with exit code 1: /Users/mikkoville/project/onskebo/platforms/android/gradlew cdvBuildDebug -b /Users/mikkoville/project/onskebo/platforms/android/build.gradle
    at makeError (/Users/mikkoville/project/onskebo/platforms/android/cordova/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/Users/mikkoville/project/onskebo/platforms/android/cordova/node_modules/execa/index.js:114:26)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[ERROR] An error occurred while running subprocess cordova.
```

**Comment by iamkbkarthikeyan** [comment]
Thanks, @mvaljento. It's resolved!
