### ISSUE TITLE
Nullability Specifier 'nonnull' conflicts with existing specifier 'nullable' AppDelegate+FCMPlugin.m

### ISSUE THREAD

**Issue by ozamamurzleen** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated#233]
Hello, thanks for the plugin it works well on Android. BUT I am unable to integrate with IOS:

I have iOS 6.0.0 platform
And using cordova-plugin-fcm-with-dependecy-updated@7.0.9 or cordova-plugin-fcm-with-dependecy-updated@7.0.1

Please see attached screenshots of the error.

![IMG_20210303_033014](https://user-images.githubusercontent.com/62137583/109725283-bbdb6b80-7bd2-11eb-83bb-4556d055300d.jpg)
![IMG_20210303_033009](https://user-images.githubusercontent.com/62137583/109725300-c0a01f80-7bd2-11eb-95ef-9aff624b0e30.jpg)

Please any help appreciated, I am stuck on this for more than 1 day.

**Comment by josevavia** [comment]
Same problem here in a Ionic project:

```
    "cordova-plugin-fcm-with-dependecy-updated": "^7.8.0",
```

```
Ionic:

   Ionic CLI                     : 5.4.1 
   Ionic Framework               : @ionic/angular 5.6.0
   @angular-devkit/build-angular : 0.901.15
   @angular-devkit/schematics    : 9.1.15
   @angular/cli                  : 9.1.15
   @ionic/angular-toolkit        : 2.3.3

Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : ios 6.2.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, cordova-plugin-ionic 5.4.7, (and 14 other plugins)

Utility:

   cordova-res : 0.15.3 
   native-run  : 1.3.0 

System:

   ios-sim : 8.0.2
   NodeJS  : v12.13.1
   npm     : 6.12.1
   OS      : macOS
   Xcode   : Xcode 12.4 Build version 12D4e
```

**Comment by josevavia** [comment]
@ozamamurzleen which macOS version do you have?

I have two macs:
-With macOS Big Sur 11.2.2 this problem disappears (but I am blocked with: https://github.com/andrehtissot/cordova-plugin-fcm-with-dependecy-updated/issues/232)
- With macOS Big Sur 11.2.1 this problem occurs

I am desesperate...

**Comment by ozamamurzleen** [comment]
I have changed the method signature in AppDelegate+FCMPlugin.h file this:

- (void)messaging:(nonnull FIRMessaging *)messaging didReceiveRegistrationToken:(nonnull NSString *)deviceToken {

to this:

- (void)messaging:(nonnull FIRMessaging *)messaging didReceiveRegistrationToken:(NSString * _Nullable)deviceToken {

And my app compiled and push notifications started working.

@josevavia i hope it works for you as well.
