### ISSUE TITLE
Installing plugin fails on iOS

### ISSUE THREAD

**Issue by mleech** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated#238]
**Describe the bug**
I recieve the following error when adding the plugin for ios:
```
Installing "cordova-plugin-fcm-with-dependecy-updated" for ios
Running command: pod install --verbose
Failed to install 'cordova-plugin-fcm-with-dependecy-updated': Error: pod: Command failed with exit code 1
    at ChildProcess.whenDone (/Users/martin/dev/testcordova/Testing/node_modules/cordova-common/src/superspawn.js:135:23)
    at ChildProcess.emit (node:events:378:20)
    at maybeClose (node:internal/child_process:1067:16)
    at Socket.<anonymous> (node:internal/child_process:453:11)
    at Socket.emit (node:events:378:20)
    at Pipe.<anonymous> (node:net:665:12)
pod: Command failed with exit code 1
```

Same error as in https://github.com/andrehtissot/cordova-plugin-fcm-with-dependecy-updated/issues/82

My cocoapods version is 1.10.1. 
I've run `pod repo update`.

Can reproduce issue on on a fresh ionic cordova example project.

**To Reproduce**
1. Set up a fresh ionic project: `ionic start` (I selected the conference app)
2. Add iOS platform `ionic cordova platform add ios` 
3. Add plugin: `ionic cordova plugin add cordova-plugin-fcm-with-dependecy-updated`
4. I get the error shown above

**Expected behavior**
Plugin should install without error.

**Screenshots**
N/A

**Environment (please complete the following information):**
- Cocoapods version (pod --version): 1.10.1
- Cordova CLI version      : 10.0.0
- Developer OS and version: MacOS Catalina
 - Xcode version (xcodebuild  -version): Xcode 12.4 Build version 12D4e

**Comment by luciendub** [comment]
Same error here..

**Comment by dguzman1012** [comment]
Hello @mleech , did you use another iOS cordova plugin in your project beside this one?

I had a similar issue, and it was hard to me to figured out what is going on:

In my case, the problem was for a conflict with another cordova plugin which uses CocoaPod dependencies as well. CocoaPod has updated it main repositories to add support to "trunk specs repo" (a CDN versions). In fact many other plugins are already updated the source reference to the CDN version.


In order to solve this I had to make a [fork](https://github.com/ProjectCORTeam/cordova-plugin-fcm-with-dependecy-updated) and of course, a [Pull Request](https://github.com/andrehtissot/cordova-plugin-fcm-with-dependecy-updated/pull/237) with the proposed changes.

Hope you can solve this!

Cheers.

**Comment by mleech** [comment]
Thanks @dguzman1012 , hopefully your PR will resolve this issue.
When reproducing the issue with the cordova example conference app I had no other plugins other than those the example used.
The contents of the `package.json` file are: 
```
{
  "name": "ionic-conference-app",
  "version": "0.0.0",
  "description": "Ionic Conference App",
  "author": "Ionic Team <hi@ionicframework.com>",
  "license": "Apache-2.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "postinstall": "webdriver-manager update --standalone false --gecko false"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/ionic-team/ionic-conference-app.git"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "^8.2.14",
    "@angular/core": "^8.2.14",
    "@angular/forms": "^8.2.14",
    "@angular/platform-browser": "^8.2.14",
    "@angular/platform-browser-dynamic": "^8.2.14",
    "@angular/pwa": "^0.803.23",
    "@angular/router": "^8.2.14",
    "@angular/service-worker": "^8.2.14",
    "@ionic-native/core": "5.0.0-beta.15",
    "@ionic-native/in-app-browser": "5.0.0-beta.15",
    "@ionic-native/splash-screen": "5.0.0-beta.15",
    "@ionic-native/status-bar": "5.0.0-beta.15",
    "@ionic/angular": "^5.1.1",
    "@ionic/storage": "^2.1.3",
    "cordova-android": "^8.1.0",
    "cordova-ios": "^5.1.1",
    "cordova-plugin-device": "^2.0.3",
    "cordova-plugin-inappbrowser": "^3.2.0",
    "cordova-plugin-ionic-keyboard": "^2.2.0",
    "cordova-plugin-ionic-webview": "^4.1.3",
    "cordova-plugin-splashscreen": "^5.0.3",
    "cordova-plugin-statusbar": "^2.4.3",
    "cordova-plugin-whitelist": "^1.3.4",
    "core-js": "^3.6.4",
    "rxjs": "^6.5.4",
    "sw-toolbox": "3.6.0",
    "tslib": "^1.10.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/architect": "^0.803.23",
    "@angular-devkit/build-angular": "^0.803.23",
    "@angular-devkit/core": "^8.3.23",
    "@angular-devkit/schematics": "^8.3.23",
    "@angular/cli": "^8.3.23",
    "@angular/compiler": "^8.2.14",
    "@angular/compiler-cli": "^8.2.14",
    "@angular/language-service": "^8.2.14",
    "@ionic/angular-toolkit": "^2.1.2",
    "@ionic/lab": "^2.0.19",
    "@types/jasmine": "3.4.6",
    "@types/jasminewd2": "2.0.8",
    "@types/node": "^12.12.26",
    "codelyzer": "^5.2.1",
    "cordova-plugin-fcm-with-dependecy-updated": "^7.8.0",
    "jasmine-core": "^3.5.0",
    "jasmine-spec-reporter": "4.2.1",
    "karma": "4.4.1",
    "karma-chrome-launcher": "^3.1.0",
    "karma-coverage-istanbul-reporter": "2.1.1",
    "karma-jasmine": "2.0.1",
    "karma-jasmine-html-reporter": "1.4.2",
    "protractor": "^5.4.3",
    "puppeteer": "^1.20.0",
    "ts-node": "8.5.0",
    "tslint": "^5.20.1",
    "typescript": "~3.5.3"
  },
  "cordova": {
    "platforms": [
      "ios",
      "android"
    ],
    "plugins": {
      "cordova-plugin-device": {},
      "cordova-plugin-inappbrowser": {},
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-whitelist": {},
      "cordova-plugin-ionic-webview": {
        "ANDROID_SUPPORT_ANNOTATIONS_VERSION": "27.+"
      },
      "cordova-plugin-statusbar": {},
      "cordova-plugin-ionic-keyboard": {}
    }
  }
}
```

**Comment by dguzman1012** [comment]
Ok. What version of CocoaPod do you have? You can always try to make a `pod setup` or `pod init` in your project.

Hint: Try to move to your iOS folder inside the project 'platforms/ios' and run `pod install --verbose` in order to see more details from this error.

**Comment by mleech** [comment]
@dguzman1012 Thank you for the `pod install --verbose` hint.
This led me to get this error:
```
ArgumentError - Illformed requirement "$IOS_FIREBASE_MESSAGING_VERSION"
``` 

which led me to this issue: https://github.com/andrehtissot/cordova-plugin-fcm-with-dependecy-updated/issues/202
which it seems this issue is a duplicate of.

Specifying version 7.5.0 of the plugin works around the issue for now:
```
ionic cordova plugin add cordova-plugin-fcm-with-dependecy-updated@7.5.0
```

Closing this one as a duplicate of #202 which is still open.

**Comment by dguzman1012** [comment]
Hey @mleech !! Yes, I had that issue too, and that's why I left the firebase version been handled by the Google Utilities in My fork. 

It's nice you have found a workaround!

Happy coding

**Comment by dineshmaths1** [comment]
Any solution am facing same issue how to fix?
