### ISSUE TITLE
Duplicate resources (string/google_app_id and string/google_api_key) as of v4.4.3

### ISSUE THREAD

**Issue by leMaik** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated#24]
First of all, thank you for all the work maintaining this library! :tada: 

Today, my builds started to fail suddenly (only for Android, iOS builds are not affected) due to duplicate resources in the `:app:mergeReleaseResources` gradle task. When I downgraded to v4.4.1, everything started working again.

I guess this is a regression in the refactoring of the file lookup, but I didn't find the cause while looking through the source code. For now, I downgraded to get my app to build again, but I'd appreciate any help though. :slightly_smiling_face:

**Comment by andrehtissot** [comment]
Would you tell me which other plugins you have installed? The conflict might only occur if there is other also adding the firebase app id and key.

Thank you for mentioning, it'll be investigated and fixed. :)

**Comment by leMaik** [comment]
Here's the list of other plugins. I don't see one that should also add the firebase app id and key. It doesn't happen if I keep all plugins and downgrade this one.

```
    "@gedysintraware/cordova-universal-links-plugin": "git+https://github.com/GEDYSIntraWare/cordova-universal-links-plugin.git",
    "cordova-android": "^8.1.0",
    "cordova-custom-config": "^5.1.0",
    "cordova-ios": "^5.0.1",
    "cordova-plugin-android-permissions": "^1.0.0",
    "cordova-plugin-camera-preview": "^0.11.0",
    "cordova-plugin-fcm-with-dependecy-updated": "4.4.1",  ← downgraded this one for now
    "cordova-plugin-headercolor": "^1.0.0",
    "cordova-plugin-inappbrowser": "^3.1.0",
    "cordova-plugin-ionic-keyboard": "2.2.0",
    "cordova-plugin-ionic-webview": "^4.1.1",
    "cordova-plugin-splashscreen": "^5.0.3",
    "cordova-plugin-statusbar": "^2.4.3"
```

**Comment by niccolofanton** [comment]
Hi, I'm having the same issue. This is my list
```
 "cordova-plugin-fcm-with-dependecy-updated": {
        "FCM_VERSION": "19.0.0",
        "GRADLE_TOOLS_VERSION": "3.5.3",
        "GOOGLE_SERVICES_VERSION": "4.3.3",
        "SUPPORT_LIBRARY_VERSION": "28.0.0",
        "ANDROID_DEFAULT_NOTIFICATION_ICON": "@mipmap/ic_launcher"
      },
      "cordova-plugin-whitelist": {},
      "cordova-plugin-statusbar": {},
      "cordova-plugin-device": {},
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-ionic-webview": {
        "ANDROID_SUPPORT_ANNOTATIONS_VERSION": "27.+"
      },
      "cordova-plugin-ionic-keyboard": {}
```

**Comment by andrehtissot** [comment]
Due to a bug introduced in v4.4.3, the file `platforms/android/app/src/main/res/values/strings.xml` two tags are included on install, tags which, on build, are also included by cordova-android@8.x.x. Hence failing the build process.

To apply the fix, install the new version and remove these two tags from your values/strings.xml:
* `<string name="google_app_id">...</string>`
* `<string name="google_api_key">...</string>`
