### ISSUE TITLE
Ringing alert style notification

### ISSUE THREAD

**Issue by coulson84** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated#249]
Hi, I have had a look at previous issues and a quick glance at the code but couldn't see an answer to this.

I am planning to put webRTC video calling in to an app and if a user is not currently using the app I'd like to be able to display a call style notification with continuing vibration and/or sound until it is answered or the user stops trying to ring them. Is there any way of doing this via the plug-in?

Thanks
Joe

**Comment by mozhn** [comment]
You can create your own declaration in onMessageReceived method.

**Comment by coulson84** [comment]
That would only work if the app was backgrounded though wouldn't it as the onMessageReceived method is a JS callback? If the app isn't open then it wouldn't work.

**Comment by mozhn** [comment]
You have to do [this in native code.](https://github.com/andrehtissot/cordova-plugin-fcm-with-dependecy-updated/blob/b17d06f64082129abfc0d2d13339c00637971f74/src/android/com/gae/scaffolder/plugin/MyFirebaseMessagingService.java#L34)

**Comment by coulson84** [comment]
Ah, nice. Thanks for the pointer 🙂
