### ISSUE TITLE
Notification badge for android and ios

### ISSUE THREAD

**Issue by MoradAbdelgaber** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated#25]
How could I setup badges with my notification ? I have tried to add badge in message payload , but nothing changed . I also tried to use badge plugin to be increased , but fcm.onNotification() method only works if app is opened ? Could you suggest the best way to handle this functionality , please ?

**Comment by andrehtissot** [comment]
I can check this week. Thank you for mentioning.

**Comment by andrehtissot** [comment]
For iOS, you can send with the push payload, the key `badge` (https://firebase.google.com/docs/cloud-messaging/http-server-ref#notification-payload-support).

For Android, badge is not widely supported, and the support that exists are accessible only programmatically (https://developer.android.com/training/notify-user/badges). Which can, yes, be used with this plugin. Unfortunately, not currently without some small changes.

Sorry for the delay
