### ISSUE TITLE
Icon of notification

### ISSUE THREAD

**Issue by leocharrua** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated#26]
Hello. How I can configure the icon of notification? What's the format of this file must be? And where it must be located in iOS and Android ionic platform folder?
Can I switch between different icons from my sender service?

Other question: I've tried in android emulator but didn't worked (nothing happens when I send the notification) ... in a real device is working ok. Do you know how this can be?

Thanks

**Comment by zinebAme** [comment]
did u resolves the probleme?

**Comment by leocharrua** [comment]
Hello. I was able to configure the notifications icon.

1) Generate icons with white color and transparent. You can use this app for this:

http://romannurik.github.io/AndroidAssetStudio/icons-notification.html

2) Copy the generated folders named drawable-... to the res folder:
                 platforms/android/app/src/main/res

3) When you send the FCM notification specifies:
                "icon": "fcm_push_icon",
		"color": "red",
for example.

Luck!!!

**Comment by andrehtissot** [comment]
Thank you @zinebAme for helping with the questions.

As for Android, you can set the default, by installing the plugin with the variable `ANDROID_DEFAULT_NOTIFICATION_ICON` set. As explained in https://github.com/andrehtissot/cordova-plugin-fcm-with-dependecy-updated#version-420-24022020.

To have the Push in an emulator, is always recommended to use an android image with "Google Play" or, for older android versions, "Google API".

Still need support for changing the icons on iOS?

**Comment by andrehtissot** [comment]
Closed issue due to inactivity.
