### ISSUE TITLE
ionic cordova while build     use of undeclared identifier 'FIRInstanceID' am getting this error 

### ISSUE THREAD

**Issue by dineshmaths1** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated#262]
platforms/ios/MyApp/Plugins/cordova-plugin-fcm-with-dependecy-updated/AppDelegate+FCMPlugin.m:215:7: error: 
      use of undeclared identifier 'FIRInstanceID'
    [[FIRInstanceID instanceID] deleteIDWithHandler:handler];
      ^
1 error generated.

** BUILD FAILED **

The following build commands failed:
	CompileC /Users/hanumantb/Library/Developer/Xcode/DerivedData/MyApp-hchilvbspocezlftfzdqggkqrecl/Build/Intermediates.noindex/MyApp.build/Debug-iphonesimulator/MyApp.build/Objects-normal/x86_64/AppDelegate+FCMPlugin.o /Users/hanumantb/Documents/titheeworking/platforms/ios/MyApp/Plugins/cordova-plugin-fcm-with-dependecy-updated/AppDelegate+FCMPlugin.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
xcodebuild: Command failed with exit code 65
[ERROR] An error occurred while running subprocess cordova.
        
        cordova build ios exited with exit code 65.

**Comment by nagasiNR** [comment]
@dineshmaths1 Hi! Have you found a solution for it?

**Comment by ramikhafagi96** [comment]
any updates on this?

**Comment by Peggy2344** [comment]
I solved this by 

`cordova plugin rm cordova-plugin-fcm-with-dependecy-updated`

and then

`cordova plugin add cordova-plugin-fcm-with-dependecy-updated`

just need to update the version of the plugin
