### ISSUE TITLE
FCM notification does not receives when the app is in foreground ionic 5 (ios)? need help

### ISSUE THREAD

**Issue by Ibni-Amin** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated#266]
I Installed cordova fcm plugin different version each one works fine in android but stuck in ios foreground notification in ionic 5 

**Expected behavior**
To receive notification on foreground

**Comment by Ibni-Amin** [comment]
while the the app is background, notification lands perfectly

**Comment by Loown** [comment]
Hi, Same issue here, but with android, when I'm in foreground, I receive notification like if I was background or killed, it doesn't trigger onNotification method, idk

**Comment by Ibni-Amin** [comment]
A few days ago it was perfect. I don't know this plugin issue. I realise that every version should be updated of installed packages with fcm.. I switched my app into capacitor and that's really worked fine.

**Comment by Loown** [comment]
Same here, ended up using firebaseX plugin, working perfectly ^^'
