### ISSUE TITLE
Cannot add extension with name 'googleServices', as there is an extension already registered with that name

### ISSUE THREAD

**Issue by selombanybah** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated#29]
Facing below exception while using FCM plugin. Any help is appreciated

> Configure project :app
FCM PLUGIN GRADLE TOOLS VERSION: 3.5.3Project evaluation failed including an error in afterEvaluate {}. Run with --stacktrace for details of the afterEvaluate {} error.

FAILURE: Build failed with an exception.

* Where:
Script '/path/to/project/platforms/android/cordova-plugin-fcm-with-dependecy-updated/osn-FCMPlugin.gradle' line: 56

* What went wrong:
A problem occurred evaluating script.
> Failed to apply plugin [class 'com.google.gms.googleservices.GoogleServicesPlugin']
   > Cannot add extension with name 'googleServices', as there is an extension already registered with that name.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
/path/to/project/platforms/android/gradlew: Command failed with exit code 1 Error output:
Project evaluation failed including an error in afterEvaluate {}. Run with --stacktrace for details of the afterEvaluate {} error.

FAILURE: Build failed with an exception.

* Where:
Script 'path/to/project/platforms/android/cordova-plugin-fcm-with-dependecy-updated/osn-FCMPlugin.gradle' line: 56

* What went wrong:
A problem occurred evaluating script.
> Failed to apply plugin [class 'com.google.gms.googleservices.GoogleServicesPlugin']
   > Cannot add extension with name 'googleServices', as there is an extension already registered with that name.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

**Comment by andrehtissot** [comment]
Improvement release as v4.5.5 to avoid, applying it twice.
Unfortunately, if another plugin applies the google service plugin *after* this one, there is no easy way to avoid.
Maybe checking other plugin's files, idk.
Don't want to be too invasive, by scanning other plugins, if I can avoid it.

Please try the new version, and if the error persist, please send me the list of plugins you have installed with their versions.
Thank you.
