### ISSUE TITLE
Phonegap Build fails because bad paths

### ISSUE THREAD

**Issue by escanda** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated#30]
In Phonegap Cloud Build, they use different paths than on a normal build in our local system. This does [FCMPlugin.gradle:1](https://github.com/andrehtissot/cordova-plugin-fcm-with-dependecy-updated/blob/master/src/android/FCMPlugin.gradle#L1)  and [FCMPlugin.gradle:6](https://github.com/andrehtissot/cordova-plugin-fcm-with-dependecy-updated/blob/master/src/android/FCMPlugin.gradle#L6) fail during the build process.

Would you make those statements optional whenever the file does not exist?

**Comment by andrehtissot** [comment]
Of course.
I'll also add a warning telling that the plugin variables would not be available.

I'll comment here as soon as soon as the version is published.

**Comment by andrehtissot** [comment]
Improvement release as v4.5.4. If any issues rise, let me know.

**Comment by escanda** [comment]
Thanks a lot!

**Comment by escanda** [comment]
By the way, you should create a donating badge so we can buy you some beers :)

**Comment by andrehtissot** [comment]
In the beginning I was against this, due to the fact that this repo was born as a fork and it'd be unfair to the initial maintainer.
But it has, thanks to this amazing community, grew a lot since then.

But thank you for the suggestion.
