### ISSUE TITLE
Delay asking for permission on installation

### ISSUE THREAD

**Issue by loama** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated#31]
Can I delay the prompt asking for permissions?
I don´t want to ask right after opening the application but after a few steps.

**Comment by andrehtissot** [comment]
We can have a iOS-specific js method to request permission, of course.

**Comment by andrehtissot** [comment]
I'll comment here as soon as soon as the feature is published.

**Comment by loama** [comment]
Thanks!

**Comment by andrehtissot** [comment]
Hi @loama, sorry for the delay, but the feature is now release as v6.0.0.

**Comment by loama** [comment]
Impressive, thanks @andrehtissot ! Will update right now
