### ISSUE TITLE
Wrong date on README

### ISSUE THREAD

**Issue by YemYigit** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated#32]
You may want to correct the date of version 4.5.1 :)

**Comment by andrehtissot** [comment]
My intention was to inform only changes to the plugin that add/change features.
Internal improvements are not that important for the new user.
Version-specific updates are available in the "releases" tab.
And the badge always reflects the last version available on npm, so it is, in a way, exposed in the Readme.

What do you think?

**Comment by YemYigit** [comment]
date for version 4.5.1 is 26.10.2019

however for 4.2.0 is 24.02.2020

i think you forgot to change date for 4.5.1, it can not be older than 4.2.0. am i wrong? :)

**Comment by andrehtissot** [comment]
Ohhh, now I got it. Thank you 😆
