### ISSUE TITLE
Could not get unknown property 'FCM_CORE_VERSION' 

### ISSUE THREAD

**Issue by francoborrelli** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated#34]
I am getting this error whenever i try to build a release version.

```
Error: /app/platforms/android/gradlew: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* Where:
Build file '/app/platforms/android/app/build.gradle' line: 299

* What went wrong:
A problem occurred evaluating project ':app'.
> Could not get unknown property 'FCM_CORE_VERSION' for object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

```
package.json

```
"cordova-plugin-fcm-with-dependecy-updated": {
                "FCM_CORE_VERSION": "16.0.9",
                "FCM_VERSION": "18.0.0",
                "GRADLE_TOOLS_VERSION": "3.5.0",
                "GOOGLE_SERVICES_VERSION": "4.2.0"
            }
```

**Comment by ritenv** [comment]
@francoborrelli this looks like some other package would conflicting. I could be wrong though.
Would you be able to share your full package.json contents?

**Comment by andrehtissot** [comment]
Thank you @francoborrelli, that will surely help :)

**Comment by francoborrelli** [comment]
I ended up solving the problem by manually adding the following lines to the `project.properties` file.
``
cordova.system.library.1=com.google.firebase:firebase-core:16.0.9
cordova.system.library.2=com.google.firebase:firebase-messaging:18.0.0
``

Thanks!
