### ISSUE TITLE
FirebaseMessaging: Notification pending intent canceled

### ISSUE THREAD

**Issue by kytwb** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated#35]
I am not sure how to debug the following:

```
04-06 16:58:28.907  1999  2781 I ActivityTaskManager: START u0 {act=FCM_PLUGIN_ACTIVITY flg=0x14000000 pkg=<redacted> (has extras)} from uid 10135
04-06 16:58:28.908  9646  9646 E FirebaseMessaging: Notification pending intent canceled
```

I found this was the issue leading to `onNotification` not being triggered for me. The rest is working properly (initialization, getToken):

```
[ng] [console.log]: "FCMPlugin.js: is created"
[ng] [console.log]: "FCMPlugin Ready OK"
[ng] [console.log]: "Ionic Native: deviceready event fired after 2200 ms"
[ng] [console.log]: "registerPushNotificationToken" "<redacted-token>"
```

**Comment by andrehtissot** [comment]
I'll investigate. Thanks for pointing it out.

**Comment by kytwb** [comment]
If you can point me in a direction to debug this, I'd be happy to help as well 🙏
Thank you!

**Comment by andrehtissot** [comment]
I've found the issue also mentioned here https://github.com/android/user-interface-samples/issues/98, which leads me to believe that your push payload might be presenting an unexpected structure.

Would you provide a Push payload example?

You should, of course, redact the sensitive information. But the structure, keys and value types, can be useful to understand this issue.

**Comment by kytwb** [comment]
If needed:

```
{
    "registration_ids":
    [
        "<redacted>"
    ],
    "data":
    {
        "show_in_foreground": true,
        "remote": true,
        "link": "<redacted>",
        "guid": "5939821c-415b-4f1e-acfc-0ebce3e58217",
        "NotificationType": "<redacted>",
        "objectId": 1103047868,
        "userId": 0
    },
    "notification":
    {
        "title": "<redacted>",
        "body": "<redacted>",
        "click_action": "FCM_PLUGIN_ACTIVITY",
        "sound": "default",
        "icon": "fcm_push_icon"
    },
    "priority": 10,
    "content_available": true
}
``

**Comment by andrehtissot** [comment]
Funny you have the same `click_action` defined, just like the example reported in https://stackoverflow.com/questions/56924836/firebase-api-push-doesnt-open-background-app-on-android-device.

Would you be able to avoid sending the `click_action` key?

**Comment by kytwb** [comment]
@andrehtissot From my understanding, not passing the click_action would just launch the app/bring back the app to the foreground when pressing the push notification, and not lunch the Java FmcPluginActivity, which would not be triggering `onNotification` is javascript-land.

**Comment by andrehtissot** [comment]
True. 🤔

**Comment by andrehtissot** [comment]
Do you have more than one FCM_PLUGIN_ACTIVITY action in your AndroidManifest.xml? (`<action android:name="FCM_PLUGIN_ACTIVITY" />`)?

**Comment by andrehtissot** [comment]
There is another way to get this feature.

Hi, I've written a simple implementation, which creates a notification, instead of relying on the click_action given.
Just to check if a solution like this could work in your case (https://github.com/andrehtissot/cordova-plugin-fcm-with-dependecy-updated/compare/master...andrehtissot:custom-notification-implementation).

So, from the root app directory, execute something like:
```bash
cd ..
git clone https://github.com/andrehtissot/cordova-plugin-fcm-with-dependecy-updated.git
cd -
cd ../cordova-plugin-fcm-with-dependecy-updated
git checkout custom-notification-implementation
cd -
ionic cordova plugin remove cordova-plugin-fcm-with-dependecy-updated
ionic cordova plugin add ../cordova-plugin-fcm-with-dependecy-updated
```

And please let me know if the error still happen. Not sure why it does, but this way it might not

**Comment by kytwb** [comment]
I went with FirebaseX in the meantime as I couldn't spend more time debugging 🙏 I hope I'll find the time to come back to it as it would be better for future iterations if we prove to be using only FCM.

**Comment by kytwb** [comment]
If someone ever run into this issue before though, you are welcome to test first and keep it going forward 🙏 Thank you for your assistance @andrehtissot!

**Comment by andrehtissot** [comment]
No problem, many changes are on the way.
