### ISSUE TITLE
Incompatibility with background-geolocation

### ISSUE THREAD

**Issue by jackie-d** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated#36]
The contemporary use of `cordova-plugin-fcm-with-dependecy-updated` together with the plugin `ionic-native/background-geolocation` causes the following error at build time:

```
platforms\android\app\src\main\java\com\marianhello\bgloc\data\BackgroundActivity.java:20: error: cannot access zzbfm
        confidence = activity.getConfidence();
                             ^
  class file for com.google.android.gms.internal.zzbfm not found
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error
:app:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.
```

**In order to solve that**, you will be required to use `cordova-android-play-services-gradle-release`
([link](https://github.com/dpa99c/cordova-android-play-services-gradle-release)) plugin.

You can install the plugin by 

`cordova plugin add cordova-android-play-services-gradle-release  --variable play-services-location=15.0.1`

and configure it as follows

package.json

```
      "cordova-plugin-fcm-with-dependecy-updated": {
        "FCM_VERSION": "19.0.0",
        "GRADLE_TOOLS_VERSION": "3.5.3",
        "GOOGLE_SERVICES_VERSION": "4.3.3",
        "SUPPORT_LIBRARY_VERSION": "28.0.0",
        "ANDROID_DEFAULT_NOTIFICATION_ICON": "@mipmap/ic_launcher"
      },
      "cordova-android-play-services-gradle-release": {
        "PLAY-SERVICES-LOCATION": "15.0.1"
      }
```

config.xml

```
    <plugin name="cordova-android-play-services-gradle-release" spec="~4.0.0">
        <variable name="PLAY-SERVICES-LOCATION" value="15.0.1" />
    </plugin>
```

Original post:
https://forum.ionicframework.com/t/getting-apk-build-failure-when-using-ionic-native-push-and-ionic-native-background-geolocation/175419/8

**Comment by jackie-d** [comment]
Note: I also had to add the following Android Library support and adapter by

```
ionic cordova plugin add cordova-plugin-androidx
ionic cordova plugin add cordova-plugin-androidx-adapter
```

to solve a Program type already present: android.support.v4.os.ResultReceiver$MyResultReceiver error.

This [dpa99c](https://github.com/dpa99c) guy really deserve a donation.

**Comment by andrehtissot** [comment]
I got the build working without `cordova-android-play-services-gradle-release`.

By default, the dependencies used by cordova-plugin-background-geolocation are quite old, so on install, I've set the required compatible version.
`ionic cordova plugin add @mauron85/cordova-plugin-background-geolocation --variable GOOGLE_PLAY_SERVICES_VERSION=17.0.0`

Unfortunatelly, the cordova-plugin-background-geolocation still uses old support packages, which are not available in androidx, hence the need for these:
`ionic cordova plugin add cordova-plugin-androidx`
`ionic cordova plugin add cordova-plugin-androidx-adapter`
