### ISSUE TITLE
Android Foreground notification not working.

### ISSUE THREAD

**Issue by smorris1709** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated#37]
I know the banner doesn't show by default when app is in the foreground but I'm not even getting my standard alert with json stringify data params.

when the app is closed the notification banner comes in but when I tap it no alert happening.
Works fine on ios but not android

I'm using cordova-android v8.0.0

**Comment by smorris1709** [comment]
>

**Comment by andrehtissot** [comment]
Did you found the issue? If you share others can find the solution for the same issue later :)

**Comment by smorris1709** [comment]
@andrehtissot No I haven't yet I thought I did solve it by removing and re adding the android platform and the plugin because it worked but then when I try to do it again and implement my actual functionality it doesn't work on android in the foreground. works on ios in both foreground and background but not on android even when I tap it doesn't do nothing.

**Comment by smorris1709** [comment]
@andretissot you got any idea why this would be the case?

**Comment by andrehtissot** [comment]
Would you kindly provide:

1. The android runtime log (`adb logcat`) of which you performed these actions, in sequence:
1.1. Booting the device *;
1.2. Starting the app;
1.3. Switching the app to the background, by opening another app;
1.4. Seeing the notification;
1.5. Tapping on the notification.

2. A Push payload example. Redacting the sensitive information, of course. But keeping the structure, keys and value types.

3. And after retrieving those, experiment with this special branch, of which I suggested in the comment https://github.com/andrehtissot/cordova-plugin-fcm-with-dependecy-updated/issues/35#issuecomment-610606389.

You might have been experiencing the same issue as https://github.com/andrehtissot/cordova-plugin-fcm-with-dependecy-updated/issues/35, of which I'm still investigating.


*If you are running the app in an emulator, make sure you are running from a image that contains Google Play or, for older android versions, Google API.

**Comment by smorris1709** [comment]
Here is the log of the app running note at the bottom where it says remove notification for unknown key

is where I tapped the notification.

`2020-04-10 20:39:27.370 23010-23303/? D/FCMPlugin: ==> FCMPlugin execute: ready
2020-04-10 20:39:27.372 23010-23010/? D/SystemWebChromeClient: webpack-internal:///./node_modules/@sentry/utils/dist/instrument.js: Line 112 : FCMPlugin.js: is created
2020-04-10 20:39:27.372 23010-23010/? I/chromium: [INFO:CONSOLE(112)] "FCMPlugin.js: is created", source: webpack-internal:///./node_modules/@sentry/utils/dist/instrument.js (112)
2020-04-10 20:39:27.396 23010-23010/? D/SystemWebChromeClient: webpack-internal:///./node_modules/@sentry/utils/dist/instrument.js: Line 112 : FCMPlugin Ready OK
2020-04-10 20:39:27.396 23010-23010/? I/chromium: [INFO:CONSOLE(112)] "FCMPlugin Ready OK", source: webpack-internal:///./node_modules/@sentry/utils/dist/instrument.js (112)
2020-04-10 20:39:27.640 23010-23303/? D/FCMPlugin: ==> FCMPlugin execute: registerNotification
2020-04-10 20:42:50.587 23010-23303/? D/FCMPlugin: ==> FCMPlugin execute: registerNotification
2020-04-10 20:42:50.693 23010-23303/? D/FCMPlugin: ==> FCMPlugin execute: registerNotification
2020-04-10 20:42:50.868 23010-23303/? D/FCMPlugin: ==> FCMPlugin execute: registerNotification
2020-04-10 20:42:50.995 23010-23303/? D/FCMPlugin: ==> FCMPlugin execute: registerNotification
2020-04-10 20:43:00.688 23010-23303/? D/FCMPlugin: ==> FCMPlugin execute: registerNotification
2020-04-10 20:43:00.756 23010-23303/? D/FCMPlugin: ==> FCMPlugin execute: registerNotification
2020-04-10 20:43:00.920 23010-23303/? D/FCMPlugin: ==> FCMPlugin execute: registerNotification
2020-04-10 20:43:01.001 23010-23303/? D/FCMPlugin: ==> FCMPlugin execute: registerNotification
2020-04-10 20:43:11.618 23010-23303/? D/FCMPlugin: ==> FCMPlugin execute: getToken
2020-04-10 20:43:11.655 23010-23010/? I/FCMPlugin: 	Token: ddjIwAeG7Ng:APA91bHnpinB_4R79tQM3QutNnT1VorjzbZz_mKnsVQakUzbzMdxPG1126EIBznTpl8dvl7w4VF6NZN23m3kzUl7IXwXOuoTtT1qzYh6sqG8U1npaW1wj9RVK9uV8Lw6trhRX0V26c2q
2020-04-10 20:43:11.818 23010-23303/? D/FCMPlugin: ==> FCMPlugin execute: registerNotification
2020-04-10 20:43:11.985 23010-23303/? D/FCMPlugin: ==> FCMPlugin execute: registerNotification
2020-04-11 17:12:06.649 27596-27596/com.schoolspider.schoolspider D/FCMPlugin: ==> FCMPlugin initialize
2020-04-11 17:12:18.828 27596-27794/com.schoolspider.schoolspider D/FCMPlugin: ==> FCMPlugin execute: ready
2020-04-11 17:12:18.835 27596-27596/com.schoolspider.schoolspider D/SystemWebChromeClient: webpack-internal:///./node_modules/@sentry/utils/dist/instrument.js: Line 112 : FCMPlugin.js: is created
2020-04-11 17:12:18.836 27596-27596/com.schoolspider.schoolspider I/chromium: [INFO:CONSOLE(112)] "FCMPlugin.js: is created", source: webpack-internal:///./node_modules/@sentry/utils/dist/instrument.js (112)
2020-04-11 17:12:18.871 27596-27596/com.schoolspider.schoolspider D/SystemWebChromeClient: webpack-internal:///./node_modules/@sentry/utils/dist/instrument.js: Line 112 : FCMPlugin Ready OK
2020-04-11 17:12:18.871 27596-27596/com.schoolspider.schoolspider I/chromium: [INFO:CONSOLE(112)] "FCMPlugin Ready OK", source: webpack-internal:///./node_modules/@sentry/utils/dist/instrument.js (112)
2020-04-11 17:12:19.132 27596-27794/com.schoolspider.schoolspider D/FCMPlugin: ==> FCMPlugin execute: registerNotification
2020-04-11 17:12:53.305 27596-27794/com.schoolspider.schoolspider D/FCMPlugin: ==> FCMPlugin execute: registerNotification
2020-04-11 17:12:53.390 27596-27794/com.schoolspider.schoolspider D/FCMPlugin: ==> FCMPlugin execute: registerNotification
2020-04-11 17:13:51.597 27596-27794/com.schoolspider.schoolspider D/FCMPlugin: ==> FCMPlugin execute: ready
2020-04-11 17:13:51.619 27596-27794/com.schoolspider.schoolspider W/PluginManager: THREAD WARNING: exec() call to FCMPlugin.ready blocked the main thread for 23ms. Plugin should use CordovaInterface.getThreadPool().
2020-04-11 17:13:51.623 27596-27596/com.schoolspider.schoolspider D/SystemWebChromeClient: webpack-internal:///./node_modules/@sentry/utils/dist/instrument.js: Line 112 : FCMPlugin.js: is created
2020-04-11 17:13:51.623 27596-27596/com.schoolspider.schoolspider I/chromium: [INFO:CONSOLE(112)] "FCMPlugin.js: is created", source: webpack-internal:///./node_modules/@sentry/utils/dist/instrument.js (112)
2020-04-11 17:13:51.643 27596-27596/com.schoolspider.schoolspider D/SystemWebChromeClient: webpack-internal:///./node_modules/@sentry/utils/dist/instrument.js: Line 112 : FCMPlugin Ready OK
2020-04-11 17:13:51.643 27596-27596/com.schoolspider.schoolspider I/chromium: [INFO:CONSOLE(112)] "FCMPlugin Ready OK", source: webpack-internal:///./node_modules/@sentry/utils/dist/instrument.js (112)
2020-04-11 17:13:52.374 27596-27794/com.schoolspider.schoolspider D/FCMPlugin: ==> FCMPlugin execute: registerNotification
2020-04-11 17:16:45.875 27596-27794/com.schoolspider.schoolspider D/FCMPlugin: ==> FCMPlugin execute: registerNotification
2020-04-11 17:16:46.037 27596-27794/com.schoolspider.schoolspider D/FCMPlugin: ==> FCMPlugin execute: registerNotification
2020-04-11 17:16:59.920 27596-31764/com.schoolspider.schoolspider W/FirebaseMessaging: Icon resource fcm_push_icon not found. Notification will use default icon.
2020-04-11 17:17:05.239 27596-31848/com.schoolspider.schoolspider W/FirebaseMessaging: Icon resource fcm_push_icon not found. Notification will use default icon.
2020-04-11 17:17:14.119 2079-2079/? W/NotificationEntryMgr: removeNotification for unknown key: 0|com.schoolspider.schoolspider|0|FCM-Notification:75646291|10088`


my notification payload is as follows 

```
{
"to":"'TOKEN_GOES_HERE", 
"notification": {
                "title":"This a test notification title",
                "body":"This is the content of the notification",
                "badge": 1,
                "sound": "default"
            },
            "data": {
                "type" : "survey",
                "id" : "",
                "title":"This a test notification title",
                "body":"This is the content of the notification",
            }
            }
```

**Comment by smorris1709** [comment]
I did a filter on the logcat of fcm just so there wasnt too much noise

**Comment by smorris1709** [comment]
I just installed [#35 ](https://github.com/andrehtissot/cordova-plugin-fcm-with-dependecy-updated/issues/35) as you suggested its working a lot better however still when the app is closed and then you tap a notification it still does nothing.

When the app is in the foreground and you pull down the notification tray and tap the notification then it does the desired action so it works as expected so its just when the app is closed it seems like its not sending the payload to the app.

**Comment by smorris1709** [comment]
@andrehtissot sorry for pestering just realised I wasn't passing the "click_action":"FCM_PLUGIN_ACTIVITY" with my notification payload. when I do that it all works I think as expected.

**Comment by andrehtissot** [comment]
That's funny. You shouldn't be required to give "click_action", as the app, in the branch I suggested, should already be handling any push message in a background service alone.

**Comment by smorris1709** [comment]
Oh how interesting,

Yeah our old app uses the old phonegap push plugin and we dont have that click action specified in our old payload but that used gcm and apns directly. 

Do you think it will be an easy fix? Let me know if I can help you in anyway, I dont know much about android/java but can help in other ways if you need even if its another pair of eyes. 

Thanks again for making the plugin or at least maintaining the updated version of it

**Comment by andrehtissot** [comment]
Of course. I really don't know why the "click_action" approach didn't work for you. As it does allow users to have other plugins or custom notification handling work more easily.
But having the background service approach improved and working as a fallback in case of "click_action" not being given, should easy enough.

**Comment by andrehtissot** [comment]
I was investigating the issue reported until I found this thread https://stackoverflow.com/questions/37711082/how-to-handle-notification-when-app-in-background-in-firebase

Which reminded me of Android push behavior:
- For "notification" payload:
  - When app is on background: The OS receives the payload, presents it, and on tapping, open the "click_action", or in lack of it, the main action;
  - When app is on foreground: the app background service receives the payload and decides what to do with it;
- For "data" payload: The app's background service receives the payload and decides what to do with it;
- For mixed ("notification" and "data") payload:
  - When app is on background: The OS receives the payload, presents it, and on tapping, open the "click_action", or in lack of it, the main action;
  - When app is on foreground: the app background service receives the payload and decides what to do with it;

Hence, as I have explained long time ago in https://github.com/andrehtissot/cordova-plugin-firebase-extended-notification/wiki/The-Three-Types-of-Notification-Playload, the only way to control the notification tapping action, as well to use more advanced notification options, is to only send "data" payloads.

Would that be possible in your case?

**Comment by smorris1709** [comment]
Ah okay,

So by my understanding keep the payload the same for sending to iOS as thats working but basically for android just use data only? 

I will give this ago today and see where I get should I try this with a tagged version of your notification packages rather than the checked out branch one?


Another issue is that when I built this and tried to push to play store for beta testing I had it working on the emulator but then when I pushed  it didnt seem to work im not sure whether its something im doing in the build process or something else. 

Thanks for investigating this.

**Comment by andrehtissot** [comment]
> So by my understanding keep the payload the same for sending to iOS as thats working but basically for android just use data only?

If you want to have the manual control of how notifications are displayed, `data` messages are the only real way.
If you want to keep the payload the same, you can have the "click_action" there to act when the app is not in the foreground.

> I will give this ago today and see where I get should I try this with a tagged version of your notification packages rather than the checked out branch one?

I'll see how I'll integrate the changes from the experimental branch to a release.

> Another issue is that when I built this and tried to push to play store for beta testing I had it working on the emulator but then when I pushed it didnt seem to work im not sure whether its something im doing in the build process or something else.

As long as the same google services configuration file is in the right paths, the signed release build should just work.
If you like, I can take a look in the published app's initialisation adb logs.

**Comment by smorris1709** [comment]
@andrehtissot I don't really need custom display info. I just need the basic notification display and it to be tappable and when its tapped certain data params are passed so I can navigate to the specific resource in my app. 

Then in the foreground I display a toast like notification with a view button so they can choose to view it or not within the app.

I will try again later or tomorrow and see if I can get the thing working as expected. I have your extended notification plugin and will see what that entails for android, as for iOS my functionality is working perfectly so don't wanna change it if I can help it.

> If you like, I can take a look in the published app's initialisation adb logs.

that might actually be helpful if I get any more issues with a deployment.

**Comment by andrehtissot** [comment]
> @andrehtissot I don't really need custom display info. I just need the basic notification display and it to be tappable and when its tapped certain data params are passed so I can navigate to the specific resource in my app.

Then, recommend you get back to the latest release, continue to send the payload with `"click_action":"FCM_PLUGIN_ACTIVITY"`.

> Then in the foreground I display a toast like notification with a view button so they can choose to view it or not within the app.

When the app is on the foreground, as the push payload is mixed, you'll get as part of the data, the notification title and body.*
With the data that you should receive just as the payload reaches the app, you can show the toast notification as you prefer.

> I will try again later or tomorrow and see if I can get the thing working as expected. I have your extended notification plugin and will see what that entails for android, as for iOS my functionality is working perfectly so don't wanna change it if I can help it.

The extended notification plugin goes to the other way, as it requires the payloads to be data-only and draws the notifications itself, as a background service.

> > If you like, I can take a look in the published app's initialisation adb logs.
> 
> that might actually be helpful if I get any more issues with a deployment.

On Android, there should be no reason to act differently in a local build or a signed one.

Please re-open this issue or create more specific ones if you get into problems, I'll be happy to help.

**Comment by smorris1709** [comment]
@andrehtissot i'm not sure if background notification is working correctly as its not giving me an alert when I tap the notification even with it the click action defined.

**Comment by andrehtissot** [comment]
It shouldn't give you an alert on tapping, but just return to `FCMPlugin.onNotification`.

I'd only alert, if you have wrote something like this in your app:
```javascript
FCMPlugin.onNotification(function(data){
    alert(JSON.stringify(data))
});
```

If this doesn't work, please reopen the issue. If not I might not see your comment.

**Comment by smorris1709** [comment]
Thats exactly whats not working

**Comment by andrehtissot** [comment]
Ok, I'll check

**Comment by smorris1709** [comment]
@andrehtissot im installing this on a fresh cordova app to see if its anything to do with my setup or other plugins. will let you know how it goes

**Comment by smorris1709** [comment]
@andrehtissot I just installed v4.6.4 and background tapping works with that but with click_action present in the payload.

**Comment by andrehtissot** [comment]
Yes, the `click_action` is required in the payload.

I'll check why it stopped working since v4.6.4.

**Comment by smorris1709** [comment]
yeah I did it didn't work

**Comment by andrehtissot** [comment]
Do you require iOS 9 support?

**Comment by andrehtissot** [comment]
Could @smorris1709 create a hello world app, of which can be shared here on github? Of which you experience the same issue?

**Comment by smorris1709** [comment]
yeah ill see if it that works, I currently have a working version though now on v4.6.4. I am using the webpack plugin aswell and it didn't seem to be building properly.

so I removed the plugin readded it and replatformed then getting things as expected which enabled me to implement my functionality.

I will create it and get back to you on the latest version. and yeah I think I do require ios9 support

**Comment by andrehtissot** [comment]
Well, for now v4.6.4 is the latest iOS 9 compatible.
But it's interesting to know that developers still to work with this constraint, given how old this version of iOS is.

**Comment by smorris1709** [comment]
Yeah okay thanks,

If it was up to me I would be on the latest and gratest but we have to support a lot of users that don't know what they are doing.

Our app was written in cordova a while ago before I started so have rewritten everything so im not even sure if I need to support it anymore but im gunna go out on a limb and say I have to for the time being anyway untill I can gather tthe data on the people using it and what os is being used.

**Comment by smorris1709** [comment]
@andrehtissot I think I may have figured out the source of the issue i'm having it might not be to do with the plugin at all.

I am using the cordova webpack plugin https://github.com/kotarella1110/cordova-plugin-webpack

when I do a cordova platform add my manifest file is like so

`
<?xml version="1.0" encoding="utf-8" ?>
<manifest android:hardwareAccelerated="true" android:versionCode="10000" android:versionName="1.0.0" package="com.app.app" xmlns:android="http://schemas.android.com/apk/res/android">
    <supports-screens android:anyDensity="true" android:largeScreens="true" android:normalScreens="true" android:resizeable="true" android:smallScreens="true" android:xlargeScreens="true" />
    <uses-permission android:name="android.permission.INTERNET" />
    <application android:hardwareAccelerated="true" android:icon="@mipmap/ic_launcher" android:label="@string/app_name" android:supportsRtl="true" android:usesCleartextTraffic="true">
        <activity android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|smallestScreenSize|screenLayout|uiMode" android:label="@string/activity_name" android:launchMode="singleTop" android:name="MainActivity" android:theme="@android:style/Theme.DeviceDefault.NoActionBar" android:windowSoftInputMode="adjustResize">
            <intent-filter android:label="@string/launcher_name">
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
        <activity android:exported="true" android:launchMode="singleTop" android:name="com.gae.scaffolder.plugin.FCMPluginActivity">
            <intent-filter>
                <action android:name="FCM_PLUGIN_ACTIVITY" />
                <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>
        </activity>
        <service android:name="com.gae.scaffolder.plugin.MyFirebaseMessagingService" android:stopWithTask="false">
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT" />
            </intent-filter>
        </service>
        <meta-data android:name="com.google.firebase.messaging.default_notification_icon" android:resource="@mipmap/ic_launcher" />
    </application>
</manifest>
`

but then when I do a cordova run android -- --livereload 

its changing the manifest file to this.

`<?xml version='1.0' encoding='utf-8'?>
<manifest android:hardwareAccelerated="true" android:versionCode="10000" android:versionName="1.0.0" package="com.app.app" xmlns:android="http://schemas.android.com/apk/res/android">
    <supports-screens android:anyDensity="true" android:largeScreens="true" android:normalScreens="true" android:resizeable="true" android:smallScreens="true" android:xlargeScreens="true" />
    <uses-permission android:name="android.permission.INTERNET" />
    <application android:hardwareAccelerated="true" android:icon="@mipmap/ic_launcher" android:label="@string/app_name" android:supportsRtl="true" android:usesCleartextTraffic="true">
        <activity android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|smallestScreenSize|screenLayout|uiMode" android:label="@string/activity_name" android:launchMode="singleTop" android:name="MainActivity" android:theme="@android:style/Theme.DeviceDefault.NoActionBar" android:windowSoftInputMode="adjustResize">
            <intent-filter android:label="@string/launcher_name">
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
        <service android:name="com.gae.scaffolder.plugin.MyFirebaseMessagingService" android:stopWithTask="false">
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT" />
            </intent-filter>
        </service>
        <meta-data android:name="com.google.firebase.messaging.default_notification_icon" android:resource="@mipmap/ic_launcher" />
    </application>
</manifest>
`

**Comment by smorris1709** [comment]
So when I have the below in my config.xml it seems to be overwriting the plugin xml code.

`<edit-config file="AndroidManifest.xml" mode="merge" target="/manifest/application">
            <application android:usesCleartextTraffic="true" />
        </edit-config>`

there is even an error 
` Conflict found, edit-config changes from config.xml will overwrite plugin.xml changes`

**Comment by andrehtissot** [comment]
I understand the issue, but are you sure you want your traffic to not be encrypted?

**Comment by smorris1709** [comment]
I'm not familiar with this android stuff now its a bit out of my league don't really know what do, I need that setting in order to have live reload when I'm working on the app. but are you saying I shouldn't have this in production?

How come its having conflicts though is this some settings in your plugin?

**Comment by andrehtissot** [comment]
iOS 9 now supported in version 6.2.0.

**Comment by smorris1709** [comment]
@andrehtissot Thanks 👍

**Comment by andrehtissot** [comment]
Closed issue due to inactivity.
