### ISSUE TITLE
onFirebaseDataNotificationIOS is missing from @ionic-native/fcm

### ISSUE THREAD

**Issue by viksat7** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated#39]
Hi All,
I was struggling with an issue of IOS notification not receiving when app is open (works fine when app is closed)

Thanks for the 4.6.0 update which has new method FCMPlugin.onFirebaseDataNotificationIOS to fix my above issue

I tried implementing the new method by installing your latest version of plugin v4.6.0 
and also @ionic-native/fcm version 5.23.0

But i got error of "Property 'onFirebaseDataNotificationIOS' does not exist on type 'FCM'.ts(2339)"
when implementing the method in my app.component.ts

Below is my code snippet from app.component.ts

`import { FCM } from '@ionic-native/fcm';

constructor(
private fcm: FCM,
)

initializeApp() {
this.fcm.onFirebaseDataNotificationIOS(
      function (payload) {
        console.info("Message id: " + payload.messageID)
        console.info("Data parameters: " + payload.appData)
      }
    );
}`

Kindly help me out if i am doing any mistake

**Comment by jackie-d** [comment]
Could you please report the issue at the appropriate support here: [https://github.com/ionic-team/ionic-native/issue](https://github.com/ionic-team/ionic-native/issue) for keeping this place up to tidyness?

By the way, you could try to write the following code at the end of your file to access the feature:

```
    (window as any).FCMPlugin.onFirebaseDataNotificationIOS(
      payload => {
        console.log('Payload: ', payload);
      }
```

**Comment by andrehtissot** [comment]
For the iOS issue: A similar bug was reported in the issue https://github.com/andrehtissot/cordova-plugin-fcm-with-dependecy-updated/issues/38. So please, follow the development there.

For the @ionic-native/fcm issue: It is an official ionic repository which interfaces with this one for specific ionic integration. As it is not always in sync with this one. I created a issue https://github.com/andrehtissot/cordova-plugin-fcm-with-dependecy-updated/issues/41 to handle this.
