### ISSUE TITLE
getting weird format of fcm token for ios 13

### ISSUE THREAD

**Issue by nurnabicse** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated#40]
hello,

i was using the library for fcm notification. i was using 

       FcmPlugin.getToken().then((token)=>{
                            console.log("***************token***********");
                            console.log(token);
          });

above function to retrieve the fcm token but it is returning a weird format token. i am using cordova-plugin-fcm-with-dependency-updated version 4.6.0. 

{length=32,bytes=0x70da2d4619ff25b1795971057859f90d...7b9e555ebfe8df37}'

can you please help?

**Comment by andrehtissot** [comment]
Which version of iOS you are running, and which version of iOS are targetting in your build?

I've worked in a similar issue before, which was highly dependent on the iOS version.

**Comment by nurnabicse** [comment]
yes it is iOS , OS version 13

**Comment by andrehtissot** [comment]
Hi @nurnabicse 

Please install the beta version "beta", which should have the bug you mentioned fixed.

Please, as it is a big package of changes, you might find other bugs.

**Comment by andrehtissot** [comment]
The new release v5.0.0 has the changes I mentioned.

**Comment by andrehtissot** [comment]
Issue closed due to inactivity.

Although there was no response, fix for mentioned problem was published in version 5.0.0.
