### ISSUE TITLE
Duplicate Notification When app in background or closed

### ISSUE THREAD

**Issue by Suryalg** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated#42]
When App is foreground I am receiving notification on js callback but not in notification tray which is fine.

But in the background or closed state the same notification is coming twice in Notification tray.
What shall be the reason?

**Comment by andrehtissot** [comment]
I'm assuming you are referring to Android.

Do you also get twice the payload when app is on the foreground when the device receive the push?

**Comment by Suryalg** [comment]
> I'm assuming you are referring to Android.
> 
> Do you also get twice the payload when app is on the foreground when the device receive the push?

Yes for android only. 
When in foreground it receives notification on JS callback only. Not in tray which is fine.
Only issue is in Background or in closed state.
P.S how will I know if I am getting twice the payload.

This is the code I am using to send
$token='*****';
		$title='xc Welcome to My Masjid';
		$body = "This is a test notification";
		$serverkeyValue = "****";

		$ch           = curl_init("https://fcm.googleapis.com/fcm/send"); 
		
		$notification = array(
			'title' => $title,
			'body' => $body,
			'priority' => 'high',
			'sound' => 'sound',
			'vibration' => 'yes'
		);
		
		$data = array(
	    'title' => $title,
	    'body' => $body,
	    'sound' => 'sound',
	    "param1"=>"value1" ,
	    "param2"=>"value2"  
	  ); 
		
		
		$arrayToSend  = array(
			'to' => $token,
			'priority'=>"high",
			'notification' => $notification,
			'data' => $data
		);
		$json         = json_encode($arrayToSend);
		$headers      = array();
		$headers[]    = 'Content-Type: application/json';
		$headers[]    = 'Authorization: key= ' . $serverkeyValue;
		curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "POST");
		curl_setopt($ch, CURLOPT_POSTFIELDS, $json);
		curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
		curl_exec($ch);
		
		$response = curl_getinfo($ch, CURLINFO_HTTP_CODE);
		curl_close($ch);
		
		//echopredie($response); 
		if($response==200 || $response=='200')
		{
			dd('succ');
		}
		return $response;

**Comment by andrehtissot** [comment]
Let's say you have in your app runs something like this:
```javascript
FCMPlugin.onNotification(function(data){
  console.log(Date.now()+": "+JSON.stringify(data));
});
```

When the app is on the foreground and the device receives the push, do you receive the console message twice?

**Comment by Suryalg** [comment]
> Let's say you have in your app runs something like this:
> 
> ```js
> FCMPlugin.onNotification(function(data){
>   console.log(Date.now()+": "+JSON.stringify(data));
> });
> ```
> 
> When the app is on the foreground and the device receives the push, do you receive the console message twice?

Yes absolutely I am getting console.log twice on js callback of onNotification

**Comment by andrehtissot** [comment]
So, it's clear that the issue is on the sender side.
Could you check if the php code you presented above is not being executed twice for each device's firebase token?

**Comment by Suryalg** [comment]
> So, it's clear that the issue is on the sender side.
> Could you check if the php code you presented above is not being executed twice for each device's firebase token?

I have attached the PHP code to send notification on above. can you help me on that?

**Comment by andrehtissot** [comment]
The code seems fine at a glance.
My question is more about how you execute it.
Do you manually run this php file or is it triggered by another application?

**Comment by andrehtissot** [comment]
Issue closed due to inactivity.
