### ISSUE TITLE
Android notification channels support

### ISSUE THREAD

**Issue by sajhu** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated#46]
By default, users on Android end with a Miscellanious channel. Could we have support for creating and routing notifications to other channels?

**Comment by andrehtissot** [comment]
By "channel", do you mean the Android Notification Channel (https://developer.android.com/training/notify-user/channels#CreateChannelGroup)?

If that's the case, now we'd have have of the future.
As https://firebase.google.com/docs/cloud-messaging/http-server-ref#notification-payload-support allow the server to send to the right channel, the is still required to be created from the app side.
So of course, the app side could be implemented.

**Comment by andrehtissot** [comment]
Version 6.1.0 released with channel creation support. Let me know if you run into any issues.
