### ISSUE TITLE
Remove UIWebView dependecy

### ISSUE THREAD

**Issue by andremarchezini** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated#48]
Apple will block any new realease with UIWebView dependency

ITMS-90809: Deprecated API Usage - Apple will no longer accept submissions of new apps that use UIWebView as of April 30, 2020 and app updates that use UIWebView as of December 2020. Instead, use WKWebView for improved security and reliability. Learn more (https://developer.apple.com/documentation/uikit/uiwebview).

**Comment by andrehtissot** [comment]
Of course, it will come soon enough.

I was focusing on cleaning up and taking care of more critical bugs.

Now that v5.0.0 proves itself much more stable and iOS 13 compatible, I can work on this and new features.

**Comment by andrehtissot** [comment]
Release change as v5.1.0. Let me know if you have any issues.

**Comment by rendau** [comment]
hello, I've installed v5.1.0, Cordova 5.1.1, Xcode New Build System (development), with cordova-plugin-wkwebview-engine. And I can not receive any push notification. There is no error

**Comment by andrehtissot** [comment]
Would you provide the log from the time that the app opens, to the time that it should have received the push message (a couple minutes after sending it).

Maybe we can spot a warning or something.

**Comment by andrehtissot** [comment]
Please @rendau, continue the discussion in the issue #49, so it doesn't mix with this unrelated issue.

**Comment by andremarchezini** [comment]
> Released as v5.1.0. Let me know if you have any issues.

Thanks mate. I will test it and let you know

**Comment by andremarchezini** [comment]
@andrehtissot hey bro It worked fine on iOS. The only issue I had was with the dependency of cordova-plugin-wkwebview-engine as we use cordova-plugin-ionic-webview. I created a fork and removed the dependency and it seems to work fine with cordova-plugin-ionic-webview. Not sure how the other plugins do but they don't have the dependency as there are different plugins for webview. Thanks for the fix!

**Comment by andrehtissot** [comment]
Yes, thank you.

The new version 6.0.1 has the `cordova-plugin-wkwebview-engine` dependency removed. 👍
