### ISSUE TITLE
Version >=5.1.0 not compatible with latest cordova-plugin-ionic-webview

### ISSUE THREAD

**Issue by melanom** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated#50]
### Problem
- cordova-plugin-fcm-with-dependecy-updated 6.0.0 depend on / installs cordova-plugin-wkwebview-engine 1.2.1
- cordova-plugin-ionic 5.4.7 depend on /installs cordova-plugin-ionic-webview 4.2.0
- cordova-plugin-ionic-webview 4.2.0 and cordova-plugin-wkwebview-engine 1.2.1 are not compatible for iOS

### Pointers

- This gives a linking error when building app in xcode related to duplicate symbols. 
- Confirmed that app builds if  cordova-plugin-fcm-with-dependecy-updated 6.0.0 and cordova-plugin-wkwebview-engine are removed
- Configuration works if cordova-plugin-fcm-with-dependecy-updated < 5.0.0 is installed. Hence the problem is related to installation of cordova-plugin-wkwebview-engine.

### Debug info
`cordova plugin ls

cordova-clipboard 1.3.0 "Clipboard"
cordova-plugin-androidx 1.0.2 "cordova-plugin-androidx"
cordova-plugin-androidx-adapter 1.1.0 "cordova-plugin-androidx-adapter"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-appavailability 0.4.2 "AppAvailability"
cordova-plugin-badge 0.8.8 "Badge"
cordova-plugin-calendar 5.1.5 "Calendar"
cordova-plugin-camera 4.1.0 "Camera"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-contacts 3.0.1 "Contacts"
cordova-plugin-datepicker 0.9.3 "DatePicker"
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-facebook4 6.4.0 "Facebook Connect"
cordova-plugin-fcm-with-dependecy-updated 6.0.0 "Cordova FCM Push Plugin"
cordova-plugin-file 6.0.2 "File"
cordova-plugin-geolocation 4.0.2 "Geolocation"
cordova-plugin-globalization 1.11.0 "Globalization"
cordova-plugin-inappbrowser 3.2.0 "InAppBrowser"
cordova-plugin-ionic 5.4.7 "cordova-plugin-ionic"
cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.2.0 "cordova-plugin-ionic-webview"
cordova-plugin-localization-strings 3.2.1 "Localization"
cordova-plugin-mixpanel 4.7.0 "Mixpanel"
cordova-plugin-network-information 2.0.2 "Network Information"
cordova-plugin-splashscreen 5.0.3 "Splashscreen"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-vibration 3.1.1 "Vibration"
cordova-plugin-whitelist 1.3.4 "Whitelist"
cordova-plugin-wkwebview-engine 1.2.1 "Cordova WKWebView Engine"
cordova-support-google-services 1.4.0 "cordova-support-google-services"`

### Xcode build error
`
duplicate symbol '_OBJC_IVAR_$_CDVWKWebViewEngine._engineWebView' in:
    /Users/quinn/Library/Developer/Xcode/DerivedData/ViVil-atsknnogohyfhresoxzxhsvqezgf/Build/Intermediates.noindex/ViVil.build/Debug-iphoneos/ViVil.build/Objects-normal/arm64/CDVWKWebViewEngine-FEF233EC3699DE82.o
    /Users/quinn/Library/Developer/Xcode/DerivedData/ViVil-atsknnogohyfhresoxzxhsvqezgf/Build/Intermediates.noindex/ViVil.build/Debug-iphoneos/ViVil.build/Objects-normal/arm64/CDVWKWebViewEngine-1200E40279F635B2.o
duplicate symbol '_OBJC_IVAR_$_CDVWKWeakScriptMessageHandler._scriptMessageHandler' in:
    /Users/quinn/Library/Developer/Xcode/DerivedData/ViVil-atsknnogohyfhresoxzxhsvqezgf/Build/Intermediates.noindex/ViVil.build/Debug-iphoneos/ViVil.build/Objects-normal/arm64/CDVWKWebViewEngine-FEF233EC3699DE82.o
    /Users/quinn/Library/Developer/Xcode/DerivedData/ViVil-atsknnogohyfhresoxzxhsvqezgf/Build/Intermediates.noindex/ViVil.build/Debug-iphoneos/ViVil.build/Objects-normal/arm64/CDVWKWebViewEngine-1200E40279F635B2.o
duplicate symbol '_OBJC_IVAR_$_CDVWKWebViewEngine._weakScriptMessageHandler' in:
    /Users/quinn/Library/Developer/Xcode/DerivedData/ViVil-atsknnogohyfhresoxzxhsvqezgf/Build/Intermediates.noindex/ViVil.build/Debug-iphoneos/ViVil.build/Objects-normal/arm64/CDVWKWebViewEngine-FEF233EC3699DE82.o
    /Users/quinn/Library/Developer/Xcode/DerivedData/ViVil-atsknnogohyfhresoxzxhsvqezgf/Build/Intermediates.noindex/ViVil.build/Debug-iphoneos/ViVil.build/Objects-normal/arm64/CDVWKWebViewEngine-1200E40279F635B2.o
duplicate symbol '_OBJC_CLASS_$_CDVWKWeakScriptMessageHandler' in:
    /Users/quinn/Library/Developer/Xcode/DerivedData/ViVil-atsknnogohyfhresoxzxhsvqezgf/Build/Intermediates.noindex/ViVil.build/Debug-iphoneos/ViVil.build/Objects-normal/arm64/CDVWKWebViewEngine-FEF233EC3699DE82.o
    /Users/quinn/Library/Developer/Xcode/DerivedData/ViVil-atsknnogohyfhresoxzxhsvqezgf/Build/Intermediates.noindex/ViVil.build/Debug-iphoneos/ViVil.build/Objects-normal/arm64/CDVWKWebViewEngine-1200E40279F635B2.o
duplicate symbol '_OBJC_METACLASS_$_CDVWKWeakScriptMessageHandler' in:
    /Users/quinn/Library/Developer/Xcode/DerivedData/ViVil-atsknnogohyfhresoxzxhsvqezgf/Build/Intermediates.noindex/ViVil.build/Debug-iphoneos/ViVil.build/Objects-normal/arm64/CDVWKWebViewEngine-FEF233EC3699DE82.o
    /Users/quinn/Library/Developer/Xcode/DerivedData/ViVil-atsknnogohyfhresoxzxhsvqezgf/Build/Intermediates.noindex/ViVil.build/Debug-iphoneos/ViVil.build/Objects-normal/arm64/CDVWKWebViewEngine-1200E40279F635B2.o
duplicate symbol '_OBJC_IVAR_$_CDVWKWebViewEngine._uiDelegate' in:
    /Users/quinn/Library/Developer/Xcode/DerivedData/ViVil-atsknnogohyfhresoxzxhsvqezgf/Build/Intermediates.noindex/ViVil.build/Debug-iphoneos/ViVil.build/Objects-normal/arm64/CDVWKWebViewEngine-FEF233EC3699DE82.o
    /Users/quinn/Library/Developer/Xcode/DerivedData/ViVil-atsknnogohyfhresoxzxhsvqezgf/Build/Intermediates.noindex/ViVil.build/Debug-iphoneos/ViVil.build/Objects-normal/arm64/CDVWKWebViewEngine-1200E40279F635B2.o
duplicate symbol '_OBJC_CLASS_$_CDVWKWebViewEngine' in:
    /Users/quinn/Library/Developer/Xcode/DerivedData/ViVil-atsknnogohyfhresoxzxhsvqezgf/Build/Intermediates.noindex/ViVil.build/Debug-iphoneos/ViVil.build/Objects-normal/arm64/CDVWKWebViewEngine-FEF233EC3699DE82.o
    /Users/quinn/Library/Developer/Xcode/DerivedData/ViVil-atsknnogohyfhresoxzxhsvqezgf/Build/Intermediates.noindex/ViVil.build/Debug-iphoneos/ViVil.build/Objects-normal/arm64/CDVWKWebViewEngine-1200E40279F635B2.o
duplicate symbol '_OBJC_METACLASS_$_CDVWKWebViewEngine' in:
    /Users/quinn/Library/Developer/Xcode/DerivedData/ViVil-atsknnogohyfhresoxzxhsvqezgf/Build/Intermediates.noindex/ViVil.build/Debug-iphoneos/ViVil.build/Objects-normal/arm64/CDVWKWebViewEngine-FEF233EC3699DE82.o
    /Users/quinn/Library/Developer/Xcode/DerivedData/ViVil-atsknnogohyfhresoxzxhsvqezgf/Build/Intermediates.noindex/ViVil.build/Debug-iphoneos/ViVil.build/Objects-normal/arm64/CDVWKWebViewEngine-1200E40279F635B2.o
duplicate symbol '_OBJC_CLASS_$_CDVWKWebViewUIDelegate' in:
    /Users/quinn/Library/Developer/Xcode/DerivedData/ViVil-atsknnogohyfhresoxzxhsvqezgf/Build/Intermediates.noindex/ViVil.build/Debug-iphoneos/ViVil.build/Objects-normal/arm64/CDVWKWebViewUIDelegate-AB7D11158DD85945.o
    /Users/quinn/Library/Developer/Xcode/DerivedData/ViVil-atsknnogohyfhresoxzxhsvqezgf/Build/Intermediates.noindex/ViVil.build/Debug-iphoneos/ViVil.build/Objects-normal/arm64/CDVWKWebViewUIDelegate-3DF37D8EAA5EC842.o
duplicate symbol '_OBJC_METACLASS_$_CDVWKWebViewUIDelegate' in:
    /Users/quinn/Library/Developer/Xcode/DerivedData/ViVil-atsknnogohyfhresoxzxhsvqezgf/Build/Intermediates.noindex/ViVil.build/Debug-iphoneos/ViVil.build/Objects-normal/arm64/CDVWKWebViewUIDelegate-AB7D11158DD85945.o
    /Users/quinn/Library/Developer/Xcode/DerivedData/ViVil-atsknnogohyfhresoxzxhsvqezgf/Build/Intermediates.noindex/ViVil.build/Debug-iphoneos/ViVil.build/Objects-normal/arm64/CDVWKWebViewUIDelegate-3DF37D8EAA5EC842.o
duplicate symbol '_OBJC_IVAR_$_CDVWKWebViewUIDelegate._title' in:
    /Users/quinn/Library/Developer/Xcode/DerivedData/ViVil-atsknnogohyfhresoxzxhsvqezgf/Build/Intermediates.noindex/ViVil.build/Debug-iphoneos/ViVil.build/Objects-normal/arm64/CDVWKWebViewUIDelegate-AB7D11158DD85945.o
    /Users/quinn/Library/Developer/Xcode/DerivedData/ViVil-atsknnogohyfhresoxzxhsvqezgf/Build/Intermediates.noindex/ViVil.build/Debug-iphoneos/ViVil.build/Objects-normal/arm64/CDVWKWebViewUIDelegate-3DF37D8EAA5EC842.o
duplicate symbol '_OBJC_CLASS_$_CDVWKProcessPoolFactory' in:
    /Users/quinn/Library/Developer/Xcode/DerivedData/ViVil-atsknnogohyfhresoxzxhsvqezgf/Build/Intermediates.noindex/ViVil.build/Debug-iphoneos/ViVil.build/Objects-normal/arm64/CDVWKProcessPoolFactory-5C842A30507E167B.o
    /Users/quinn/Library/Developer/Xcode/DerivedData/ViVil-atsknnogohyfhresoxzxhsvqezgf/Build/Intermediates.noindex/ViVil.build/Debug-iphoneos/ViVil.build/Objects-normal/arm64/CDVWKProcessPoolFactory-9DAB6944C7B8F8B5.o
duplicate symbol '_OBJC_METACLASS_$_CDVWKProcessPoolFactory' in:
    /Users/quinn/Library/Developer/Xcode/DerivedData/ViVil-atsknnogohyfhresoxzxhsvqezgf/Build/Intermediates.noindex/ViVil.build/Debug-iphoneos/ViVil.build/Objects-normal/arm64/CDVWKProcessPoolFactory-5C842A30507E167B.o
    /Users/quinn/Library/Developer/Xcode/DerivedData/ViVil-atsknnogohyfhresoxzxhsvqezgf/Build/Intermediates.noindex/ViVil.build/Debug-iphoneos/ViVil.build/Objects-normal/arm64/CDVWKProcessPoolFactory-9DAB6944C7B8F8B5.o
duplicate symbol '_OBJC_IVAR_$_CDVWKProcessPoolFactory._sharedPool' in:
    /Users/quinn/Library/Developer/Xcode/DerivedData/ViVil-atsknnogohyfhresoxzxhsvqezgf/Build/Intermediates.noindex/ViVil.build/Debug-iphoneos/ViVil.build/Objects-normal/arm64/CDVWKProcessPoolFactory-5C842A30507E167B.o
    /Users/quinn/Library/Developer/Xcode/DerivedData/ViVil-atsknnogohyfhresoxzxhsvqezgf/Build/Intermediates.noindex/ViVil.build/Debug-iphoneos/ViVil.build/Objects-normal/arm64/CDVWKProcessPoolFactory-9DAB6944C7B8F8B5.o
ld: 14 duplicate symbols for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation
`
Tried to clean build, deleting DerivedData among other things.

**Comment by andrehtissot** [comment]
Thanks for letting me know with a very useful description.

**Comment by andrehtissot** [comment]
The hotfix was released as 6.0.1. Let me know if you have any issues.

**Comment by melanom** [comment]
It works. Thanks a lot for a quick response!
