### ISSUE TITLE
iOS image support. Notification Service Extension

### ISSUE THREAD

**Issue by avoskresenskiy-alytics** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated#51]
Hello, thank you for plugin! I works in Android and iOS.
The only problem is that it does not show "image" in iOS push message. On Android it works great.
I added "Notification Service Extension" in XCode as described here https://firebase.google.com/docs/cloud-messaging/ios/send-image
but it seems that your plugin does not support "Notification Service Extension" for sending images in iOS notifications.
Are you planning to add this feature?

**Comment by andrehtissot** [comment]
Of course.
As soon as reported bugs are dealt with, this will be implemented.

**Comment by andrehtissot** [comment]
Hi @avoskresenskiy-alytics,

After a lot of work, the first release of a sister-plugin https://github.com/andrehtissot/cordova-plugin-fcm-image-support is out. Which should enable the support, just by installing.

Ping me there, if you find any issues.

**Comment by avoskresenskiy-alytics** [comment]
Thanks a lot!
