### ISSUE TITLE
Support for iOS 9 and WKWebView update

### ISSUE THREAD

**Issue by ulver2812** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated#53]
Hi, I need to use this plugin with iOS 9 and WKWebView in order to avoid Apple rejections. I see that the version 5.1.0 solve the WKWebView issue but the iOS 9 support is removed, it doesn't work on ios 9 or there are issues ?

**Comment by andrehtissot** [comment]
The main issue is the maintenance effort due to having a different handling of Push than iOS 10 up.

And to be honest, it's been outdated for a long time and unsupported by apple by now (https://support.apple.com/guide/iphone/supported-iphone-models-iphe3fa5df43/ios https://www.statista.com/chart/5824/ios-iphone-compatibility/).

If it is still required, I'll see how I can bring that back.

**Comment by ulver2812** [comment]
The problem is related to the recent needs of use the WKWebView instead of UiWebView. If we still use the 4.6.0 version in order to work with ios 9 we can't publish the app on the app store because this version refers to UiWebView.

**Comment by andrehtissot** [comment]
Yes, I understand. I'll try to come up with something fast to allow you to publish, and later bring the support back so you can enjoy the newer features.

**Comment by ulver2812** [comment]
@andrehtissot thanks a lot! :-)

**Comment by andrehtissot** [comment]
The fast fix was implemented as v4.6.4. Let me know if you face any issues.

**Comment by ulver2812** [comment]
@andrehtissot thanks a lot, I'll try it and I'll give you a feedback.

**Comment by ulver2812** [comment]
Hi @andrehtissot , I'm trying to use the version 4.6.4 on ios 9, in the console I get this log message:

`You've implemented -[<UIApplicationDelegate> application:didReceiveRemoteNotification:fetchCompletionHandler:], but you still need to add "remote-notification" to the list of your supported UIBackgroundModes in your Info.plist.`

There's something that I need to do or just ignore it ?

**Comment by andrehtissot** [comment]
Yes, it is. You need to add the capability to the app. Apple's reasoning. https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/pushing_background_updates_to_your_app

**Comment by andrehtissot** [comment]
Please reopen the issue, or create a new more specific one. As I might not see your comment on closed ones.

**Comment by andrehtissot** [comment]
> Yes, it is. You need to add the capability to the app. Apple's reasoning. https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/pushing_background_updates_to_your_app

Although, this change in configuration is automatically applied in newer version of the plugin.
