### ISSUE TITLE
No notification sound

### ISSUE THREAD

**Issue by tyl3r** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated#57]
I receive the notifications perfectly but without sound, here is my PHP code:

```
$data = array(	
	"notification" => array( 
		"title" => "$title", 
		"body" => "$message", 				
		"sound" => "default",
		"click_action" => "FCM_PLUGIN_ACTIVITY"
	),
	"data" => array(		
		"test" => "$test",
	),
	"to" => "/topics/testing",
	"priority" => "high"
);

$data_string = json_encode($data); 
    
// FCM API Token URL
$url = "https://fcm.googleapis.com/fcm/send";

// Curl Headers
$headers = array
(
'Authorization: key=' . API_ACCESS_KEY, 
'Content-Type: application/json'
);  

$ch = curl_init();  
curl_setopt($ch, CURLOPT_URL, $url);                                                                 
curl_setopt($ch, CURLOPT_POST, 1);  
curl_setopt( $ch,CURLOPT_HTTPHEADER, $headers );
curl_setopt( $ch,CURLOPT_RETURNTRANSFER, true );
curl_setopt( $ch,CURLOPT_POSTFIELDS, $data_string);                                                                   
$result = curl_exec($ch);
curl_close ($ch);
```
The notification appears into the Android tray bar but my phone does not make any notification sound, the strange thing is when i put my phone in only vibration mode it works and the phone vibrates when the notification arrives :/. I also tested via official firebase website (https://console.firebase.google.com/) without any luck.

I have no idea about what is wrong in my App, here is my list of plugins:
```
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-fcm-with-dependecy-updated 6.0.1 "Cordova FCM Push Plugin"
cordova-plugin-inappbrowser 2.0.2 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 1.1.16 "cordova-plugin-ionic-webview"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.1 "Whitelist"
cordova-plugin-youtube-video-player 1.0.6 "CordovaYoutubeVideoPlayer"
cordova-sqlite-storage 3.2.0 "Cordova sqlite storage plugin - cordova-sqlite-storage plugin version"
```

and ionic/android/cordoba versions:

```
Ionic:

   ionic (Ionic CLI)  : 4.12.0 (C:\Users\admin\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.1

Cordova:

   cordova (Cordova CLI) : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms     : android 8.0.0
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 1.1.1, (and 9 other plugins)

System:

   Android SDK Tools : 26.1.1 (C:\Users\admin\AppData\Local\Android\Sdk)
   NodeJS            : v8.9.4 (C:\Program Files\nodejs\node.exe)
   npm               : 5.6.0
   OS                : Windows 10

```

I also tried with custom_sound.mp3 in `res/raw` directory using `"sound" => "custom_sound"` but also does not work.

**Comment by andrehtissot** [comment]
The notification sound, if it is respecting the https://firebase.google.com/docs/cloud-messaging/http-server-ref#notification-payload-support might still be blocked in the case of:
- the user setting the device as in "silent mode";
- having the volume of notifications to zero;
- or have the priority set in the push payload as lower than required to play the sound; or
- for Android 8+, having the default channel with the priority lower than required to play the sound.

For all those above, you can verify as a device user.

The new channel feature (#46) is going to be implemented as soon as some critical bugs are addressed. Although, PRs are welcomed.

**Comment by tyl3r** [comment]
Hi @andrehtissot, thanks for the answer, i located the problem in android aplication options:

![how-enable-this-automatically](https://user-images.githubusercontent.com/1686118/80024471-70026500-84df-11ea-9cbb-1e6a65ba7751.jpg)

I don't know why sound is disabled by default in my app, any clue on how do I enable this automatically when the app is installed?, i don't see any specific permission for that in https://developer.android.com/reference/android/Manifest.permission?hl=es-419, my current permissions are:

```
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
    <uses-permission android:name="android.permission.INTERNET" />
```

Now with this enabled it works with the default sound but not with the custom one in `res/raw`, my phone has Android 9 so maybe custom sounds works only with the new channel feature?

**Comment by andrehtissot** [comment]
Not sure. As the options I mentioned should always prioritize user's definition, what it might help is, at least for Android 8.0+, to consider creating the channel (feature pending), with a high importance https://developer.android.com/guide/topics/ui/notifiers/notifications#importance

**Comment by andrehtissot** [comment]
Version 6.1.0 released with channel creation support. Let me know if you run into any issues.

**Comment by tyl3r** [comment]
Thx @andrehtissot, sorry for the late, im trying to update the app to last Ionic/Angular before implement the new channel feature, still so much work to do,  now it's a mess ^^U.

P.D: I tested the app (Ionic 3.9.2) with custom sound on my old Samsung tablet and is totally working (Android 6.0.1), Google shame...

**Comment by andrehtissot** [comment]
Google reinvents permissions and notifications every few versions 😅.
