### ISSUE TITLE
Can't get the FCM tokens on iOS

### ISSUE THREAD

**Issue by ulver2812** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated#59]
Hi I'm trying to get the FCM tokens on iOS 9 but I get `null` as FCM token value.

I'm using the 4.6.4 version of this plugin, I'm able to receive the APNS token with this:

```
FCMPlugin.getAPNSToken(
          function(token) {
            console.log(token);
          },
          function(error) {
            console.error(error);
          }
);
```

but this return `null` as token value
```
FCMPlugin.getToken(function(token){
     console.log(token);
});
```

and this doesn't get triggered so I can't see the token value 'onTokenRefresh':
```
FCMPlugin.onTokenRefresh((token) => {
          console.log(token);
});
```

I'm able to receive push notification if I use the Firebase Cloud Messaging tool to send notification campaign (the tool in the screen below).

![Cattura](https://user-images.githubusercontent.com/25301598/80093505-ea28fd00-8564-11ea-85ff-97853ee7983d.PNG)

I need the FCM token for each iOS device because I need to send notifications to specific users.

In Xcode I enabled these capabilities:

- Background modes => remote notifications
- Push notifications

In Firebase Cloud Messaging settings I uploaded the Apple APNs Auth Key correctly.

**Comment by andrehtissot** [comment]
For the devices you are running for, which iOS versions are running in them?

**Comment by ulver2812** [comment]
@andrehtissot I'm using an iPad with iOS 9.3.5

**Comment by ulver2812** [comment]
@andrehtissot I see this message in the console during app execution, it can be related with this issue ?

```
<Notice>: 6.14.0 - [Firebase/Messaging][I-FCM001000] FIRMessaging Remote Notifications proxy enabled, will swizzle remote notification receiver handlers. If you'd prefer to manually integrate Firebase Messaging, add "FirebaseAppDelegateProxyEnabled" to your Info.plist, and set it to NO. Follow the instructions at:
	https://firebase.google.com/docs/cloud-messaging/ios/client#method_swizzling_in_firebase_messaging
	to ensure proper integration.
```

**Comment by andrehtissot** [comment]
Before the v5.0.0, which droped iOS 9 support, the Firebase token management was given by the Firebase iOS dependency itself. Newer versions of `cordova-plugin-fcm-with-dependecy-updated` have a manual management of firebase token, which disabled this Proxy by swizzling.

Near future plans is to reintroduce the iOS 9 support (#55).

**Comment by ulver2812** [comment]
So you are saying that in the v4.6.4 I can't get the FCM tokens on iOS 9 devices ?

**Comment by andrehtissot** [comment]
I'm saying that should. But, instead of relying in the inner works of Firebase, it changed to manual token management. Not saying this change would fix for your case, as it should never be an issue in the first place, but it might.

I'll prioritize the reintroduction of iOS 9 support to the current version of the plugin, as there is no reason for the token to not be given.

**Comment by andrehtissot** [comment]
iOS 9 now supported in version 6.2.0.

**Comment by andrehtissot** [comment]
If upgrading doesn't work, please let me know.
