### ISSUE TITLE
Callbacks on requestPushPermissionIOS not working

### ISSUE THREAD

**Issue by maximo72** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated#61]
Calling
FCMPlugin.requestPushPermissionIOS( successCallback(), errorCallback(err) );
callbacks are never executed.
Seems that method requestPushPermission in FCMPlugin.m is not handling callbacks, am I missing something?
Thanks in advance!

**Comment by andrehtissot** [comment]
Having the callback working is the step 2 of this feature.
For now, it's not as practical, but you can use, from time to time, `hasPermission` to check.

**Comment by maximo72** [comment]
Ok, thanks!

**Comment by andrehtissot** [comment]
I know it's been a month, but now the `FCMPlugin.requestPushPermissionIOS` responds as you at first expected.

**Comment by maximo72** [comment]
Great! Thanks
