### ISSUE TITLE
notification not working ios 13

### ISSUE THREAD

**Issue by bido20** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated#62]
hello, 
i use fcm it work on android but not working on my ios app 
i received notification data on xcode console output but no notification display on  my phone 

![ab9c49d5-7a1c-4de7-b653-a1bf1ee6bbc5](https://user-images.githubusercontent.com/64337965/80294292-79eac900-8768-11ea-975c-fb17db03bb30.jpeg)

**Comment by andrehtissot** [comment]
Yes, I believe I've found the issue, but I'm unable meet the unknown criteria to trigger this error.

Could you create a hello world app, of which can be shared here on github? With which you experience the same issue.

**Comment by bido20** [comment]
@andrehtissot https://github.com/bido20/firebaseTest

**Comment by roman-rr** [comment]
@bido20 

1. Check if Android notifications works
2. Check .p8 key uploaded in firebase console
3. Check that Notification enabled herehttps://console.developers.google.com/apis/api/firebaseinappmessaging.googleapis.com/overview?project=PROJECT_NAME
4. Rebuilt few times with clear envieronment

**Comment by bido20** [comment]
thank you @roman-rr 
on Android it works without problem
in firebase console i uploaded .p12 and it still doesn't work
![Screen Shot 2020-04-27 at 1 10 35 AM](https://user-images.githubusercontent.com/64337965/80322328-9e0be000-8824-11ea-8350-71e4aaaa3765.png)

**Comment by plailopo** [comment]
hi guy, also for me not works on ios.
Server is ok, on Android it works.
APNS Key si configured, but nothing to do on iOS.

**Comment by cesarak** [comment]
I'm facing problems with iOS too. In my case I'm passing 3 different situations:
1) app running in foreground: message received and presented
2) app running in background: message received, when notification is clicked message is presented and the app goes to foreground
3) app not running: message received but when notification is clicked, the app goes to foreground but no message is showed.

Working with Cordova-9 and iOS-5.1.1
Android works in all cases. (Android-8.1.0)

Any ideas?

**Comment by cesarak** [comment]
> thank you @roman-rr
> on Android it works without problem
> in firebase console i uploaded .p12 and it still doesn't work
> ![Screen Shot 2020-04-27 at 1 10 35 AM](https://user-images.githubusercontent.com/64337965/80322328-9e0be000-8824-11ea-8350-71e4aaaa3765.png)

Is better to work with APN's key, they never expire.

**Comment by cesarak** [comment]
> I'm facing problems with iOS too. In my case I'm passing 3 different situations:
> 
> 1. app running in foreground: message received and presented
> 2. app running in background: message received, when notification is clicked message is presented and the app goes to foreground
> 3. app not running: message received but when notification is clicked, the app goes to foreground but no message is showed.
> 
> Working with Cordova-9 and iOS-5.1.1
> Android works in all cases. (Android-8.1.0)
> 
> Any ideas?

@andrehtissot I found the solution, created a branch and sent to you

**Comment by andrehtissot** [comment]
@cesarak @plailopo @roman-rr @bido20 

The PR was merged and the new v6.3.1 release is available with it.
