### ISSUE TITLE
Notification not appear in the top on phone on Android platform when app is background

### ISSUE THREAD

**Issue by sirineKr** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated#64]
Hello, 
I use FCM to send notification on Android devices. Il work correctly when app is foreground but not when app is background  (notification not appear in the top on phone).

In my message payload, I use only data object.
{
  "to": "XXXXXXXXXX",
  "data": {
    "title": "notification_title",
    "body": "notification_body"
    }
}

I'm using ionic 4 and cordova-android v8.1.0

**Comment by andrehtissot** [comment]
Yes, that's the expected behavior.

As there is no `notification` key, the OS understands that is nothing to show as a notification.

In your case, I'd change the payload to:
```json
{
  "notification": {
    "title": "notification_title",
    "body": "notification_body"
    "click_action":"FCM_PLUGIN_ACTIVITY",
  },
  "data": {
    "title": "notification_title",
    "body": "notification_body"
  },
  "to":"XXXXXXXXXX",
}
```
