### ISSUE TITLE
On Android 6 (Marshmallow), notification crashes app : unable to load icon resource

### ISSUE THREAD

**Issue by MRossignol** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated#67]
I've installed the plugin using the option ` --variable ANDROID_DEFAULT_NOTIFICATION_ICON = "@drawable/fcm_push_icon"` to specify the notification icon. That icon is black and white, alpha channel only, created with Android Studio.

On Android 7+, everything works fine, but on Android 6 (Marshmallow) notifications are never displayed, and if the app is in background it crashes upon reception of a notification. Apparently this is due to the system being unable to load the icon resource:

`Unable to load resource 0x7f070087 from pkg=com.lonofi.app`
`android.content.res.Resources$NotFoundException: Resource ID #0x7f070087`
...
`StatusBarIconView: No icon for slot com.lonofi.app/0x0`
`NotificationService: onNotification error pkg=com.lonofi.app tag=FCM-Notification:593614 id=0; will crashApplication(uid=10061, pid=6592)`
`StatusBar: removeNotification for unknown key: 0|com.lonofi.app|0|FCM-Notification:593614|10061`
`AndroidRuntime: android.app.RemoteServiceException: Bad notification posted from package com.lonofi.app: Couldn't create icon: StatusBarIcon(icon=Icon(typ=RESOURCE pkg=com.lonofi.app id=0x7f070087) visible user=0 )`

Any idea how to solve this?

**Comment by andrehtissot** [comment]
In which directories you added the icon.
A user here https://stackoverflow.com/questions/21269502/android-resourcesnotfoundexception-resource-id-0x7f030027 got the same issue.

**Comment by andrehtissot** [comment]
Closed issue due to inactivity.
