### ISSUE TITLE
Notification tappes.

### ISSUE THREAD

**Issue by tarun57** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated#68]
I'm using ionic 4, and using fcm plugin in which i got notifications but when click on the notification ii can't handle this click on notification.

**Comment by andrehtissot** [comment]
Which version of `
cordova-plugin-fcm-with-dependecy-updated ` you have installed, which platform is not working Android or iOS?

**Comment by andrehtissot** [comment]
Closed issue due to inactivity.
