### ISSUE TITLE
"hasPermission" is not firing

### ISSUE THREAD

**Issue by kartiksolanki** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated#71]
I get the token as desired, but FCMPlugin.hasPermission() is not firing. I am not getting any popup asking for "Allow Push Notification" in my ionic ios project. Any idea what is going wrong?

**Comment by andrehtissot** [comment]
**Which version of iOS are you running on?**

**`hasPermission` only returns the current state, it shouldn't ask the user**
So calling something like bellow doesn't show anything?
```javascript
FCMPlugin.hasPermission(function(doesIt){
    alert("Has permission: "+JSON.stringify(doesIt));
});
```

**If you want to ask the user, you can call:**
```
FCMPlugin.requestPushPermissionIOS();
```

**Comment by andrehtissot** [comment]
Closed issue due to inactivity.
