### ISSUE TITLE
How to localize (translate) text on incoming notifications?

### ISSUE THREAD

**Issue by dimitriscsd** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated#73]
Hello.

I was just wondering if there is a clever way to handle multiple languages in our app.

We usually have placeholders for text which then get looked up in a json file related to the current language. Having no control over the native side of the app though, I am not sure how to make this work for the notifications.

Any ideas?

**Comment by andrehtissot** [comment]
As far as I know, there is no open-source plugin for this. 

### Solution 1, Target push by user preference:

When the user logs in or changes language, send to your server the relationship between the token and the language selected.
Before you trigger notifications to that user, manipulate the message for the language chosen and send the Push with the translated message.

### Solution 2, Target push by language topics:

This solution, different from 1 and 3, wouldn't work for specific users.
When the user logs in or changes language, unsubscribe to the last language-specific topic and subscribe to the new language-specific topic.
Before you trigger notifications to that group, manipulate the message for the language chosen and send the Push with the translated message.
Example: subscribing to "en-us", allows you to send to all English speaking from US by sending the push with `to` target attribute as "/topic/en-us"

### Solution 3, Push message with language tags:

#### For iOS:

You can implement natively a Notification Content Extension (https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/ModifyingNotifications.html) which manipulates the notification text to select the correct message for current language.

#### For Android:

The push would have to always be as a data, the background "Message" service would, also by a native implementation, manipulate the message and create the notification with it.

### Solution 4, Localytics:

I have some experience with Localytics, which despite being payed, not well documented and very limited. Should provide this feature.

**Comment by dimitriscsd** [comment]
Hello Andreh,

I would like to thank you for taking the time to put thought into this and provide such a great array of options.

I will investigate each one of your solutions and will get back to you if I have any further questions.

Regarding solution 3, I suppose it would have to work through a custom cordova plugin, considering there is no access to the platform files of android and ios on a proper cordova project. Is that correct?

**Comment by andrehtissot** [comment]
> Regarding solution 3, I suppose it would have to work through a custom cordova plugin, considering there is no access to the platform files of android and ios on a proper cordova project. Is that correct?
Ideally yes. But you can always implement in an app level.

**Comment by andrehtissot** [comment]
Let me know if you have any other questions. :)
