### ISSUE TITLE
Android - Can't show notification when lock screen

### ISSUE THREAD

**Issue by xuanphu123** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated#74]
As the title. i can't show notification when lock screen on android
- cordova-plugin-fcm-with-dependecy-updated: 6.3.1
- cordova-android: 8.1.0

Thanks.

**Comment by andrehtissot** [comment]
There is a huge chance it might be related to the notification importance.

To test if this is the issue. I recommend that you create a high importance public channel, like bellow:
```javascript
FCMPlugin.createNotificationChannelAndroid({
  id: "urgent_alert", // required
  name: "Urgent Alert", // required
  description: "Very urgent message alert",
  importance: "high", // https://developer.android.com/guide/topics/ui/notifiers/notifications#importance
  visibility: "public", // https://developer.android.com/training/notify-user/build-notification#lockscreenNotification
});
```

And when send to FCM through the API, add the `android_channel_id` attribute, like bellow:
```json
{
  "notification":{
    "title":"Notification title",
    "body":"Notification body",
    "click_action":"FCM_PLUGIN_ACTIVITY",
  },
  "data":{
    "param1":"value1",
    "param2":"value2"
  },
  "to":"TOPIC OR DEVICE TOKEN",
  "priority":"high",
  "android_channel_id":"urgent_alert"
}
```

**Comment by xuanphu123** [comment]
i tried above code.. but still can't show notification when locked screen. My device using is xiaomi, android 7.1.2.
![image](https://user-images.githubusercontent.com/43433616/82278501-90292500-99b4-11ea-816f-ab552782d057.png)

**Comment by andrehtissot** [comment]
You set `visibility` as "private". Would try to create a new channel setting as "public"?
Just as a test?
As channels created are immutable, you would have to uninstall and install again, or change here the id and name for something else and, in the push payload add the "android_channel_id" to the new one.

**Comment by xuanphu123** [comment]
Yes.. just set "private" for test. I tried change the channel id.. my phone can recieve notification with sound.. but still can't show the message on lock screen .
I tried samsung phone can working... so I think this issue is private config of xiaomi phone.

**Comment by andrehtissot** [comment]
A model-specific android version might take this importance as a suggestion and act differently.
As far as I know, there is official no way to force it.
