### ISSUE TITLE
android notification not receive when app closed

### ISSUE THREAD

**Issue by tangtermsak** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated#76]
Is there any way to make it happen ?

**Comment by andrehtissot** [comment]
It should be already working. Would you share a push payload example?

**Comment by tangtermsak** [comment]
I just found out that if running on android 8 (asus zen4) and Mi Pad 4 it not working but if I run it on emulator android 10 it’s working. 
 
So, it might be os or phone model problem

**Comment by andrehtissot** [comment]
Check if the OSs are set in a battery saving mode. This should not block, but lower push communication.

**Comment by tangtermsak** [comment]
Thank you so much I will try it 😄
