### ISSUE TITLE
Ionic 4 official FCM wrapper not updating with requestPermissionOnIOS

### ISSUE THREAD

**Issue by casper5822** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated#79]
Hello,

the official native ionic 4 wrapper for your plugin is not updated.
There is no the requestPermissiononIOS method.

Best regards.

**Comment by andrehtissot** [comment]
Yes, the PR has been created https://github.com/ionic-team/ionic-native/pull/3430 but still no comments from the maintainers. Please leave a like there, just so may take this as a priority.
