### ISSUE TITLE
bug(android): onTokenRefresh, feature(ios): onAPNSTokenRefresh

### ISSUE THREAD

**Issue by expcapitaldev** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated#81]
Hello!
Thank you for good plugin!
I found mistake with onTokenRefresh method (android) and I want to ask you to add onAPNSTokenRefresh method.
You can see next: 
https://firebase.google.com/docs/cloud-messaging/android/client#monitor-token-generation
https://github.com/expcapitaldev/cordova-plugin-fcm-with-dependecy-updated/tree/6.4.0-dev
https://github.com/expcapitaldev/cordova-plugin-fcm-with-dependecy-updated/commit/99bc4dda0c1e15fab23915b0b8b8df052c490354

**Comment by andrehtissot** [comment]
The `onTokenRefresh` method works for both Android and iOS. And informs the app when a new Firebase token is generated. This token should be used for both Android and iOS.

For iOS, there is also the APNS token, which is sent to Firebase and connected to the Firebase token.

As the APNS token shouldn't ever change, having a method for its update seems unnecessary.
https://stackoverflow.com/questions/6652242/does-the-apns-device-token-ever-change-once-created
https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/HandlingRemoteNotifications.html#//apple_ref/doc/uid/TP40008194-CH6-SW1

So having a `onAPNSTokenRefresh` seems counter-intuitive as, after you got the push permision, you should be able to fetch it, by calling `getAPNSToken`.

@expcapitaldev, what do you think?

**Comment by expcapitaldev** [comment]
@andrehtissot can you check ?
About onTokenRefresh. I can not find for Android about onTokenRefresh implementation, 
https://github.com/andrehtissot/cordova-plugin-fcm-with-dependecy-updated/blob/master/src/android/com/gae/scaffolder/plugin/MyFirebaseMessagingService.java#L23, 
unused method https://github.com/andrehtissot/cordova-plugin-fcm-with-dependecy-updated/blob/master/src/android/com/gae/scaffolder/plugin/FCMPlugin.java#L273 ?, 
see
https://firebase.google.com/docs/cloud-messaging/android/client#monitor-token-generation
So, with APNS token I agree with you, it is unnecessary issue.

**Comment by andrehtissot** [comment]
You are correct.

The method bellow is just logging, but not sending the token to the `onTokenRefresh`.
```java
    @Override
    public void onNewToken(String token) {
        super.onNewToken(token);
        Log.d(TAG, "New token: " + token);
    }
```


The bug will be fixed and a patch will be released. Thank you very much!

**Comment by andrehtissot** [comment]
Bug fix released as v6.4.1. Thank you again.

**Comment by expcapitaldev** [comment]
@andretissot  thank you for your plugin !

**Comment by expcapitaldev** [comment]
onTokenRefresh (android) will not be called the first time because the token can be changed before the javascript callback is created. We can save the token and send it to javascript when the callback appears.
@andrehtissot, what do you think?

**Comment by andrehtissot** [comment]
You can always retrieve the current on by calling `FCMPlugin.getToken(function(token){ /*...*/ });`.

The `onTokenRefresh` is more for when you don't know that your token has expired, so to have updated right away.
