### ISSUE TITLE
Error in IOS build.

### ISSUE THREAD

**Issue by kishsak** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated#82]
kishoresakthi@kishores-MacBook-Air src-cordova % cordova platform add ios
Using cordova-fetch for cordova-ios@^5.0.0
Adding ios project...
Creating Cordova project for the iOS platform:
	Path: platforms/ios
	Package: com.maskmeet.app
	Name: Maskmeet
iOS project created with cordova-ios@5.1.1
Installing "cordova-plugin-androidx" for ios
Installing "cordova-plugin-androidx-adapter" for ios
Installing "cordova-plugin-appversion" for ios
Installing "cordova-plugin-badge" for ios
Installing "cordova-plugin-camera" for ios
Installing "cordova-plugin-device" for ios
Installing "cordova-plugin-fcm-with-dependecy-updated" for ios
Running command: pod install --verbose
Failed to install 'cordova-plugin-fcm-with-dependecy-updated': Error: pod: Command failed with exit code 1
    at ChildProcess.whenDone (/Volumes/HP_RECOVERY/www/maskmeet-mobile/src-cordova/node_modules/cordova-common/src/superspawn.js:135:23)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Socket.emit (events.js:198:13)
    at Pipe._handle.close (net.js:606:12)
pod: Command failed with exit code 1

1. I tried to reinstall the plugin --> din't work
2. i uninstalled the plugin, added platform ios and then installed the plugin --> din't work 
3. i tried installing cocopods, then ran "pod init nad pod install" it showed some error as "tag not found"

so please provide a solution.

**Comment by andrehtissot** [comment]
It is a local issue with cocoapods dependency manager. Please, run `pod repo update` to refresh your cocoapod's cache.

**Comment by andrehtissot** [comment]
Let me know if this does not fix the issue.

**Comment by kishsak** [comment]
yes, you are right i found the error was with the cocoapods new released version 1.9.1

i downgraded to cocoapods  version 1.9.0 and cleared repo cache and then ran the commands "pod init and pod install" it worked. 

sorry to disturb and thanks for your response.

**Comment by andrehtissot** [comment]
Don't need to be sorry about.

Now I know to be cautious about cocoapods v1.9.1.

**Comment by BRadHoc** [comment]
I'm experiencing the same issue after accidentally updating cocapods.

I've tried to downgrade using:
> sudo gem uninstall cocoapods
> sudo gem install cocoapods -v 1.9.0

as suggested:

```
sudo gem list cocoapods

*** LOCAL GEMS ***

cocoapods (1.9.0)
cocoapods-clean (0.0.1)
cocoapods-core (1.9.3, 1.9.0)
cocoapods-deintegrate (1.0.4)
cocoapods-downloader (1.3.0)
cocoapods-plugins (1.0.0)
cocoapods-search (1.0.0)
cocoapods-stats (1.1.0)
cocoapods-trunk (1.5.0)
cocoapods-try (1.2.0)
```

However when adding the platform via:

> cordova platform ios

I get:

```
Running command: pod install --verbose
Failed to install 'cordova-plugin-fcm-with-dependecy-updated': Error: pod: Command failed with exit code 1
    at ChildProcess.whenDone (/Users/user/Documents/Projects/Project/node_modules/cordova-common/src/superspawn.js:135:23)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1051:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)

```
