### ISSUE TITLE
This plugin breaks adding short app name

### ISSUE THREAD

**Issue by QuentinFarizon** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated#86]
Cordova added an attribute called "short" on the name in the config.xml. The after prepare script will fail to get the project name because of the added attribute.

https://cordova.apache.org/docs/en/latest/config_ref/#short-name

This is fixed in https://github.com/arnesson/cordova-plugin-firebase/pull/724, could you cherry-pick the fix ?

**Comment by andrehtissot** [comment]
I believe I know what might be going on. Thank you for letting me know of this issue. I'll make some tests and report here any advances.

**Comment by andrehtissot** [comment]
Fixed on v6.4.3 (and v7.0.0-beta.2)

Thank you for pointing it out.
