### ISSUE TITLE
Can not intercept background notification in the app in Android only

### ISSUE THREAD

**Issue by EmreAkkoc** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated#89]
Hey Andre Love the hard work you do here for this plugin. You even created a TS wrapper yourself. Really appreciate it.However, My problem is when received a notification in the **background** in **Android** I cant intercept it with a tap. In fact when I looked at the Logs in android studio it doesnt even receive the message so that I can direct my users to certain pages. I have tested it on device with android version 7. note that, I did not use Ts wrapper and it works normal for foreground notifications. On ios works perfectly normal for both Foreground an Background and when I tap the notification received in background it works as it supposed to unlike on android.
can you give a quick check ?

**Comment by andrehtissot** [comment]
Hi, this is very common issue, due to the way the OS communicates with the app on push.
1. Would you share the format of the push payload you send?
2. Would you share your `AndroidManifest.xml`?

**Comment by EmreAkkoc** [comment]
sure this is the format
`if (fcmTokens) {
    fcmTokens.forEach(async (token, index) => {

      message = {
        token: token,
        notification: {
          title: uid_username.split('_')[1],
          body: content,

        },
        "data":{
          "uid" : uid_username.split('_')[0],
          "username" : uid_username.split('_')[1],
          "type"   : 'privateMessage',
          "receiverRole":senderRole      //by receiverRole we also mean sender here
        },
        "android": {
          "notification": {
            "sound": "default"
          }
        },
        "apns": {
          "payload": {
            "aps": {
              "sound": "default",
              "badge": 1,
              "content-available": 1
            }
          }
        }

      }
      let response = await admin.messaging().send(message).catch(error => {
        console.log(error.errorInfo.code)
        console.log('Failure sending notification to', fcmTokens[index], error);
        // Cleanup the tokens who are not registered anymore.
        if (error.errorInfo.code === 'messaging/invalid-registration-token' ||
          error.errorInfo.code === 'messaging/registration-token-not-registered' ||
          error.errorInfo.code === 'messaging/invalid-argument') {
          userTokensRef.update({
            'tokens': admin.firestore.FieldValue.arrayRemove(token)
          });
        }
      })





    });
  }` 
and AndroidManifest.xml
`<?xml version='1.0' encoding='utf-8'?>
<manifest android:hardwareAccelerated="true" android:versionCode="1" android:versionName="0.0.1" package="com.emreakkoc.fitnessrec" xmlns:android="http://schemas.android.com/apk/res/android">
    <supports-screens android:anyDensity="true" android:largeScreens="true" android:normalScreens="true" android:resizeable="true" android:smallScreens="true" android:xlargeScreens="true" />
    <uses-permission android:name="android.permission.INTERNET" />
    <application android:hardwareAccelerated="true" android:icon="@mipmap/ic_launcher" android:label="@string/app_name" android:networkSecurityConfig="@xml/network_security_config" android:supportsRtl="true">
        <activity android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|smallestScreenSize|screenLayout|uiMode" android:label="@string/activity_name" android:launchMode="singleTop" android:name="MainActivity" android:theme="@android:style/Theme.DeviceDefault.NoActionBar" android:windowSoftInputMode="adjustResize">
            <intent-filter android:label="@string/launcher_name">
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
        <activity android:exported="true" android:launchMode="singleTop" android:name="com.gae.scaffolder.plugin.FCMPluginActivity">
            <intent-filter>
                <action android:name="FCM_PLUGIN_ACTIVITY" />
                <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>
        </activity>
        <service android:name="com.gae.scaffolder.plugin.MyFirebaseMessagingService" android:stopWithTask="false">
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT" />
            </intent-filter>
        </service>
        <meta-data android:name="com.google.firebase.messaging.default_notification_icon" android:resource="@mipmap/ic_launcher" />
        <provider android:authorities="${applicationId}.provider" android:exported="false" android:grantUriPermissions="true" android:name="org.apache.cordova.camera.FileProvider">
            <meta-data android:name="android.support.FILE_PROVIDER_PATHS" android:resource="@xml/camera_provider_paths" />
        </provider>
        <receiver android:enabled="true" android:name="nl.xservices.plugins.ShareChooserPendingIntent">
            <intent-filter>
                <action android:name="android.intent.action.SEND" />
            </intent-filter>
        </receiver>
        <provider android:authorities="${applicationId}.sharing.provider" android:exported="false" android:grantUriPermissions="true" android:name="nl.xservices.plugins.FileProvider">
            <meta-data android:name="android.support.FILE_PROVIDER_PATHS" android:resource="@xml/sharing_paths" />
        </provider>
    </application>
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.BODY_SENSORS" />
</manifest>
`

**Comment by andrehtissot** [comment]
I've added a line which should solve your issues:
```javascript
if (fcmTokens) {
    fcmTokens.forEach(async (token, index) => {

      message = {
        token: token,
        notification: {
          title: uid_username.split('_')[1],
          body: content,
          "click_action":"FCM_PLUGIN_ACTIVITY", // <=== THIS ONE HERE
        },
        "data":{
          "uid" : uid_username.split('_')[0],
          "username" : uid_username.split('_')[1],
          "type"   : 'privateMessage',
          "receiverRole":senderRole      //by receiverRole we also mean sender here
        },
        "android": {
          "notification": {
            "sound": "default"
          }
        },
        "apns": {
          "payload": {
            "aps": {
              "sound": "default",
              "badge": 1,
              "content-available": 1
            }
          }
        }

      }
      let response = await admin.messaging().send(message).catch(error => {
        console.log(error.errorInfo.code)
        console.log('Failure sending notification to', fcmTokens[index], error);
        // Cleanup the tokens who are not registered anymore.
        if (error.errorInfo.code === 'messaging/invalid-registration-token' ||
          error.errorInfo.code === 'messaging/registration-token-not-registered' ||
          error.errorInfo.code === 'messaging/invalid-argument') {
          userTokensRef.update({
            'tokens': admin.firestore.FieldValue.arrayRemove(token)
          });
        }
      })
    });
  }
```

This line says to the OS to trigger the `FCM_PLUGIN_ACTIVITY` action intention you have defined in your AndroidManifest.xml.

**Comment by andrehtissot** [comment]
Let me know if the issue persists or if you get any other.

**Comment by EmreAkkoc** [comment]
I made the change you wrote and also changed the line for _Firebase Cloud Functions_
`let response = await admin.messaging().send(message)`
to:
`let response = await admin.messaging().sendToDevice(token, message)`

works well, thank you
