### ISSUE TITLE
ios don't receive notifications

### ISSUE THREAD

**Issue by zinebAme** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated#92]
Hy,
I am working with the version 6.4.1  of this plugin. In ios, I get the fcm token but not the notification.
I use the "cordova-ios": "5.1.1", and  "cordova": "^8.1.2". Please give me advice

**Comment by andrehtissot** [comment]
Besides FCM token, do you also have access to the [APNS token](https://github.com/andrehtissot/cordova-plugin-fcm-with-dependecy-updated#version-400-12102019)?
Would you mind sharing your package.json?

**Comment by Nogatz** [comment]
I tryed to install 

WARN: Install the FCM plugin: 'ionic cordova plugin add cordova-plugin-fcm-with-dependecy-updated'

But on ionic cordova plugin list 

cordova-plugin-android-permissions 1.0.2 "Permissions"
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-document-viewer 0.9.13 "SitewaertsDocumentViewer"
cordova-plugin-fcm-with-dependecy-updated 6.4.2 "Cordova FCM Push Plugin"
cordova-plugin-file 6.0.2 "File"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 5.0.0 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.3 "Splashscreen"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-whitelist 1.3.4 "Whitelist"
cordova-plugin-x-socialsharing 5.6.4 "SocialSharing"
cordova-sqlite-storage 5.0.0 "Cordova sqlite storage plugin - cordova-sqlite-storage plugin version"
es6-promise-plugin 4.2.2 "Promise"

Is in there. 

cordova-ios 5.1.0

**Comment by andrehtissot** [comment]
Fixed on v6.4.3 (and v7.0.0-beta.2)

Thank you for pointing it out.
