### ISSUE TITLE
IOS push notification n't receiving in latest version plugin

### ISSUE THREAD

**Issue by sivakumar55** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated#94]
Hi
I am working with version 6.4.2 of this plugin.
I use the "cordova-ios": "5.1.1", and "cordova": "9". When I used older version notification worked and I update the latest version of plugin can't receive notification for ios device.

**Comment by andrehtissot** [comment]
Did you call [FCMPlugin.requestPushPermissionIOS()](https://github.com/andrehtissot/cordova-plugin-fcm-with-dependecy-updated#version-640-21052020)? Before, the push permission was requested at app start, now you can delay and request later. But without the user's permission, there is no Push on iOS.

**Comment by sivakumar55** [comment]
Push permission not to ask for the app to start in ios device. I'm using ionic framework

**Comment by andrehtissot** [comment]
I'm sorry, I'm not sure I understood what you meant. Did you call FCMPlugin.requestPushPermissionIOS()?

To have access to this and newer features and fixes, I suggest you to use the new beta version [7.0.0-beta.2](https://github.com/andrehtissot/cordova-plugin-fcm-with-dependecy-updated/blob/v7.0.0-beta/README.md) as it comes with ionic v4 support as part of the main plugin package.

**Comment by sivakumar55** [comment]
I called "FCMPlugin.requestPushPermissionIOS()" method. blank white screen appear in my app

**Comment by andrehtissot** [comment]
For the beta version, the method was renamed to [FCM.requestPushPermission()](https://github.com/andrehtissot/cordova-plugin-fcm-with-dependecy-updated/blob/v7.0.0-beta/README.md#fcmrequestpushpermission)

**Comment by andrehtissot** [comment]
I suggest you to read the beta readme first.

**Comment by andrehtissot** [comment]
Issue closed due to lack of activity. Please open a new one with new details.
