### ISSUE TITLE
FCM.onNotification it only works in the background (7.0.0-beta.2 - Ionic-5_Capacitor-2)

### ISSUE THREAD

**Issue by Radecom** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated#98]
Hello, first of all, congratulation on your excellent work making this plug-in, it is excellent!
I managed to implement your plugin in version 7.0.0-beta.2 with Ionic 5, Capacitor 2.

The functions:
`const fcmToken: string = await FCM.getToken ();`
```
FCM.onTokenRefresh ((fcmToken: string) => {
  // ...
})
```
works great, but the function:
```
FCM.onNotification ((payload: object) => {
  // ...
})
```
It has a strange behavior, the notifications that arrive while the application is in the foreground are not detected by the subscriber. But without doing anything, no changes, or anything, being in the background everything works very well, even if I close the application.
But being in the foreground, nothing happens.

Is it a bad implementation? What advice do you give me
Greetings and good vibes for you.

**Comment by andrehtissot** [comment]
Interesting @Radecom, AFAIK it wasn't working at all on Capacitor. Maybe the version 2 has improved the compatibility. Would you consider creating a hello world app with the plugins to help me debug it?

**Comment by andrehtissot** [comment]
Issue closed due to inactivity.
